### ISSUE TITLE
showing error

### ISSUE THREAD

**Issue by ngangchill** [avenirer/CodeIgniter-MY_Model#1]
first of all i would like to say thanks for this library.

 my_model   works fine when i use :

$this->blog_model->with('comment')->get_all();

but when i  use    $this->blog_model->with('comment')->get(1);       it display error...

error that shows:

A PHP Error was encountered

Severity: Warning

Message: Illegal offset type

Filename: fb_model/MY_Model.php

Line Number: 541

Backtrace:

File: /storage/sdcard0/droidphp/ci_starter/application/vendor/fb_model/MY_Model.php
Line: 541
Function: _exception_handler

File: /storage/sdcard0/droidphp/ci_starter/application/vendor/fb_model/MY_Model.php
Line: 700
Function: call_user_func_array

File: /storage/sdcard0/droidphp/ci_starter/application/vendor/fb_model/MY_Model.php
Line: 424
Function: trigger

File: /storage/sdcard0/droidphp/ci_starter/application/controllers/Pg.php
Line: 9
Function: get

File: /storage/sdcard0/droidphp/ci_starter/index.php
Line: 275
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: fb_model/MY_Model.php

Line Number: 572

Backtrace:

File: /storage/sdcard0/droidphp/ci_starter/application/vendor/fb_model/MY_Model.php
Line: 572
Function: _exception_handler

File: /storage/sdcard0/droidphp/ci_starter/application/vendor/fb_model/MY_Model.php
Line: 700
Function: call_user_func_array

File: /storage/sdcard0/droidphp/ci_starter/application/vendor/fb_model/MY_Model.php
Line: 424
Function: trigger

File: /storage/sdcard0/droidphp/ci_starter/application/controllers/Pg.php
Line: 9
Function: get

File: /storage/sdcard0/droidphp/ci_starter/index.php
Line: 275
Function: require_once

array(0) {
}

**Comment by avenirer** [comment]
Thank you for trying my MY_Model. Could you please try to download the MY_Model again? Maybe you have an older version, because on line 541 is only a curly brace, so the error couldn't have been there. If the error persists, send me again the error that you're getting. Thank you very much for your time.

**Comment by ngangchill** [comment]
thnx for quick Reply.

no luck, same result.

A PHP Error was encountered

Severity: Warning

Message: Illegal offset type

Filename: core/MY_Model.php

Line Number: 538

Backtrace:

File: /storage/sdcard0/droidphp/ci_starter/application/core/MY_Model.php
Line: 538
Function: _exception_handler

File: /storage/sdcard0/droidphp/ci_starter/application/core/MY_Model.php
Line: 697
Function: call_user_func_array

File: /storage/sdcard0/droidphp/ci_starter/application/core/MY_Model.php
Line: 421
Function: trigger

File: /storage/sdcard0/droidphp/ci_starter/application/controllers/Pg.php
Line: 9
Function: get

File: /storage/sdcard0/droidphp/ci_starter/index.php
Line: 275
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: core/MY_Model.php

Line Number: 569

Backtrace:

File: /storage/sdcard0/droidphp/ci_starter/application/core/MY_Model.php
Line: 569
Function: _exception_handler

File: /storage/sdcard0/droidphp/ci_starter/application/core/MY_Model.php
Line: 697
Function: call_user_func_array

File: /storage/sdcard0/droidphp/ci_starter/application/core/MY_Model.php
Line: 421
Function: trigger

File: /storage/sdcard0/droidphp/ci_starter/application/controllers/Pg.php
Line: 9
Function: get

File: /storage/sdcard0/droidphp/ci_starter/index.php
Line: 275
Function: require_once

array(0) {
}

**Comment by ngangchill** [comment]
my code details :
//blog_model.php

```
class Blog_model extends MY_Model
{
    public function __construct()
    {   
    $this->has_many['comment'] = "Comment_model";
    parent::__construct();
    $this->table = "blog";      
    }
}
```

//comment_model.php

```
class Comment_model extends MY_Model
 {

function __construct()
{   
    //$this->has_many['blog'] = 'Blog_model';
    parent::__construct();
}
 }
```

 ## controller
        $this->load->model('Blog_model');
    $f = $this->Blog_model->with('comment')->get(9);
         var_dump($f);

 # tables

 blog:

 | id |  cat_id | title | content | user_id | created_at  | updated_at | deleted_at

 comments:

 | id | blog_id | comment | user_id | created_at | upadated_at | deleted_at|

**Comment by avenirer** [comment]
Corrected. Thank you.

**Comment by ngangchill** [comment]
thanks.
