### ISSUE TITLE
columns omitted in insert / update if rules are not set when calling from_form()->insert();

### ISSUE THREAD

**Issue by prashantnirgun** [avenirer/CodeIgniter-MY_Model#100]
I noticed that if rules for any columns are not set for insert / update and try from_form()->insert() 
SQL is generated omits columns which are not in rules. However I tried $this->table_fields = array('title','body'); But still body columns is missing from the SQL.

//Article_model.php
$this->table_fields = array('title','body');

public $rules = array(
            'insert' => array(
                    'title' => array(
                            'field'=>'title',
                            'label'=>'Title',
                            'rules'=>'trim|required'),
    ));

it generate the following SQL omits the body columns from article table
INSERT INTO `articles` (`title`, `created_at`) VALUES ('new title', '2016-01-09 19:25:41')

If its compulsory to add rules for each columns Must be clearly mentioned in documentation.

**Comment by avenirer** [comment]
Hello @prashantnirgun . Thank you for reporting this issue. Please try now.

**Comment by serako** [comment]
Is your last commit is the good way? because now, we send a NULL value when the form don't have the field, and in the sql table if you don't accept the null value, you have an error. If you send nothing the default sql on the field take the value.

**Comment by prashantnirgun** [comment]
Something wrong happened its generating SQL 
INSERT INTO `articles` (`title`, `body`, `created_at`) VALUES (NULL, NULL, '2016-01-10 17:18:02')

I even tried out $this->_can_be_filled = array('title','body'); it again producing the same SQL

But question arises is If we have some hidden field between Form Tag and which we don't want to add in sql again its leading to issue #101 Html fields mapping to Column Name mapping. Ok we can exclude it by using $protected. 

Sorry for giving you trouble but I am bit lazy in codding my first objective is to let the table get first updated, Next is go for validated records. Situation arise because I have Tables with lot many columns so I included the Not Null columns only in my form.

**Comment by avenirer** [comment]
Well... sorry about that. I had to revert because, when you think of it it is very normal to only accept input fields that passed the default (the model's...) validation rules. Also, I wouldn't advise you to use empty validation rules. If you think of another method to do it, I am all ears...
