### ISSUE TITLE
database column_name different than html_name

### ISSUE THREAD

**Issue by serako** [avenirer/CodeIgniter-MY_Model#101]
I modifie in line 338

```
        foreach($rules as $key=>$rule)
        {
    /*
    if(in_array($rule['field'],$this->_can_be_filled))
            {
                $this->validated[$rule['field']] = $this->input->post($rule['field']);
            }
            */

    if(in_array($key,$this->_can_be_filled))
            {
                $this->validated[$key] = $this->input->post($rule['field']);
            } 
        }
```

the rule:
  'sql_column' => array(
                            'field'=>'html_field_name',
                            'label'=> 'the html field name',
                            'rules'=>'trim|required',
                            ),

Now i can have a different name on html balise than the column sql.
I'm not a expert on codeigniter, are you think it's a good way?
i tested just on ->from_form()->insert(); 

thank's lot for your MY_Model !!

**Comment by avenirer** [comment]
Hello @serako . Please do not use your proposal. Download again and try it.

**Comment by serako** [comment]
for my issue i modify the last commit (but see my comment on the issue number 100)  : 
on line 335
            foreach($this->_can_be_filled as $field)
            {
                if ( array_key_exists($field,$this->rules['insert']) )
                {
                    $this->validated[$field] = $this->input->post($this->rules['insert'][$field]['field']);
                }
                else
                {
                    $this->validated[$field] = $this->input->post('field');
                }
            }

**Comment by avenirer** [comment]
I had to revert, because I don't think it was a good idea. Please see issue #100 .

**Comment by avenirer** [comment]
Also, the thing with MY_Model is that it has to deal with default requests, and not with "exotic" requests (like having a html input name different than the column name). For other kind of usages, you can at any time using the classic ways of validating and inserting values.
