### ISSUE TITLE
error while using multiple database connections 

### ISSUE THREAD

**Issue by zawaruddin** [avenirer/CodeIgniter-MY_Model#104]
i'm using 2 group connections in database config (default and dbsia).

example : 
class Tga_model extends MY_Model
{
    public function __construct(){
    $this->_database_connection  = 'dbsia';
        $this->table = 'Userdata';
        $this->primary_key = 'id'; 
        $this->return_as = 'array';
    parent::__construct();
    }
}

when i ran this code
$user = $this->Tga->get();
 this connection still in "default" connection database, not in "dbsia".

**Comment by avenirer** [comment]
I usually name private properties starting with underscore "_". That means that _database_connection is a private property of the MY_Model, which means that you cannot overwrite it. To use a specific database connection you can either do it as is written here: https://github.com/avenirer/CodeIgniter-MY_Model#database-connection

Or change MY_Model property _database_connection and set it to public, and not private

**Comment by salain** [comment]
@avenirer 
_database_connection is a protected property, so it is visible in the child class and should work. 
Here is a solution it works, but not fully tested:

``` PHP
class Some_model extends MY_Model
{
public function __construct(){
$this->_database_connection = 'db_group';
$this->table = ......
}

// in My_Model.php
        private function _set_connection()
        {
            if(isset($this->_database_connection))
            {
                $this->_database = $this->load->database($this->_database_connection,TRUE);
            }
            else
            {
                $this->load->database();
                $this->_database = $this->db;
            }
            //isset($this->_database_connection) ? $this->load->database($this->_database_connection) : $this->load->database();
            //$this->_database = $this->db;
        }
```

**Comment by zawaruddin** [comment]
@avenirer 
_database_connection and _database is protected, then i change it to public and the result is same. 

i use 
`$this->Tga->on('dbsia')->where('npm', '25637856')->reset()->get();`
and it's run fine. but i want it run per-model not per-request.

But thanks to @salain for the solution. 
new database connection need to be return (second parameter load->database()) so the connection can change to second group connection (dbsia)

**Comment by salain** [comment]
@zawaruddin 
You should leave _database_connection and _database as protected properties.
Changing _set_connection() method as per the code above will resolve your issue. 
I have submitted a pull request for it.

**Comment by zawaruddin** [comment]
@salain 
yeah... i set  _database_connection and _database to public just for debug. after that i leave it protected.
i changed _set_connection() method as your coding solution.

Thanks :)
