### ISSUE TITLE
where n how to convert date to y-m-d before inserting / Updating into table

### ISSUE THREAD

**Issue by prashantnirgun** [avenirer/CodeIgniter-MY_Model#107]
In my form I set up date format as 
input name="birth_dt" type="text" data-date-format="DD-MM-YYYY" 

But it generate the following SQL 
INSERT INTO `members` (`member_name`, `birth_dt` )
 VALUES ('abc', '01-06-1974')

I checked in table it storing value as '0000-00-00'

How and where I have to convert the date format ? I am using from_form()->insert();
$before_create Observer is the correct way of handling this ?

**Comment by prashantnirgun** [comment]
Soft Delete is working fine I tested Is it a correct or any other better and easy alternative then this ?

**Comment by avenirer** [comment]
yes. $before_create.
