### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by leandrolopes13** [avenirer/CodeIgniter-MY_Model#108]
```
Parse error: syntax error, unexpected '[' in E:\Ampps\www\cafedelmarco\system\application\core\MY_Model.php on line 511
A PHP Error was encountered

Severity: Parsing Error

Message: syntax error, unexpected '['

Filename: core/MY_Model.php

Line Number: 511
```

**Comment by avenirer** [comment]
can i see what led to this error?

**Comment by leandrolopes13** [comment]
I solve with this.
`
$backtrace = debug_backtrace();
            if($backtrace[1]['function']!='force_delete')
            {
                $this->_where_trashed();
            }
`

**Comment by Gandavaa-zz** [comment]
Thanks solved this problem

**Comment by avenirer** [comment]
@leandrolopes13 could you do a PR, please?

**Comment by leandrolopes13** [comment]
Sorry. PR?

**Comment by avenirer** [comment]
pull request...

**Comment by leandrolopes13** [comment]
i dont use git here. :(

_Leandro Lopes_

2016-02-05 11:06 GMT-02:00 Adrian Voicu notifications@github.com:

**Comment by leandrolopes13** [comment]
Fixed?

**Comment by hisyamyahya** [comment]
thank you @leandrolopes13  for solved this problem
