### ISSUE TITLE
has_many_pivot is not returning data

### ISSUE THREAD

**Issue by papakay** [avenirer/CodeIgniter-MY_Model#11]
I used the has_many_pivot relationship but was not returning any data.
I'm using Codeigniter 2.2.0.

With the help of Develbar tool, i saw the queries generated for the has_many_pivot method and when i tried the the queries raw creating a method in my model class, it returned data. Please see the attached images.

Thank you

![Upl
![screen shot 2015-04-19 at 7 14 29 pm](https://cloud.githubusercontent.com/assets/5013738/7220678/d437be2c-e6c8-11e4-9a46-ce3370d237df.png)
![screen shot 2015-04-19 at 7 14 58 pm](https://cloud.githubusercontent.com/assets/5013738/7220679/d43c2b24-e6c8-11e4-8b3b-2673bcc7b265.png)
![screen shot 2015-04-19 at 7 15 07 pm](https://cloud.githubusercontent.com/assets/5013738/7220680/d442adaa-e6c8-11e4-96d3-b452d689f118.png)
![screen shot 2015-04-19 at 7 15 22 pm](https://cloud.githubusercontent.com/assets/5013738/7220681/d44d2b18-e6c8-11e4-9f51-5d09e78e7a55.png)

oading Screen Shot 2015-04-19 at 7.13.40 PM.png . . .]()

**Comment by avenirer** [comment]
Try to download the model again and tell me if it works. But first you should read the following:

If you have a programs table and a users table and want to join them with the help of a pivotal table with programs->id and users->user_id (and not users->id), you should create the following fields inside the "programs_users" table: "program_id" and "user_user_id" (I sure hope that makes sense, @papakey ).

**Comment by papakay** [comment]
Thank you so much!!!!

It should work.......

**Comment by papakay** [comment]
Ooops!!!!!!!!!! Seems something is not still working, i downloaded another the model again and when i ran it this is the query generated for the pivot

SELECT \* FROM (`programs`) RIGHT JOIN `programs_users` ON `programs`.`id` = `programs_users`.`program_id` RIGHT JOIN `users` ON `programs_users`.`user_user_id` = `users`.`user_id`

but nothing was returned.

However if i add this query in a method inside my User_model, it's returning results.

What could be the issue please

**Comment by papakay** [comment]
In my users table, i set id as local primary key but i want to user_id as the foreign key from programs_users table. Could that have been an issue?

**Comment by avenirer** [comment]
Indeed that was an issue, but I think it wasn't the main problem. It only added to the main issue. And yet what you wanted was a logical request. That is why I mentioned that you should change something inside the programs_users table (even if that didn't solve your problem). Please try again. I've added a where_in in the query. If it still doesn't work I will create the tables just like yours and do it on my test framework.

**Comment by papakay** [comment]
![screen shot 2015-04-20 at 9 17 10 am](https://cloud.githubusercontent.com/assets/5013738/7226299/8b07b582-e73f-11e4-86b3-d09eecd88beb.png)
![screen shot 2015-04-20 at 9 17 31 am](https://cloud.githubusercontent.com/assets/5013738/7226300/8b0a2c72-e73f-11e4-9960-060fff1d1f0f.png)

Hello Mr Adrian, thanks for your support although no luck yet with it. It
is still not showing the user's program.

The queries generated now is this

SELECT \* FROM (`programs`) RIGHT JOIN `programs_users` ON `programs`.`id` =
`programs_users`.`program_id` RIGHT JOIN `users` ON
`programs_users`.`user_user_id` = `users`.`user_id` WHERE `users`.`user_id`
IN ('7e0e5eec-c7da-5cf4-a16d-e76f69952910')

I had earlier modified the users table.

_SET NAMES utf8;_
_SET FOREIGN_KEY_CHECKS = 0;_

_-- ----------------------------_
_--  Table structure for `programs`_
_-- ----------------------------_
_DROP TABLE IF EXISTS `programs`;_
_CREATE TABLE `programs` (_
-  `id` int(11) NOT NULL AUTO_INCREMENT,*
-  `programs` varchar(100) DEFAULT NULL,*
-  PRIMARY KEY (`id`)*
  _) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;_

_-- ----------------------------_
_--  Records of `programs`_
_-- ----------------------------_
_BEGIN;_
_INSERT INTO `programs` VALUES ('1', 'Meals'), ('2', 'Bus Services'), ('3',
'Afterschool Care');_
_COMMIT;_

_-- ----------------------------_
_--  Table structure for `programs_users`_
_-- ----------------------------_
_DROP TABLE IF EXISTS `programs_users`;_
_CREATE TABLE `programs_users` (_
-  `id` int(11) NOT NULL AUTO_INCREMENT,*
-  `program_id` varchar(200) DEFAULT NULL,*
-  `user_user_id` varchar(200) DEFAULT NULL,*
-  PRIMARY KEY (`id`)*
  _) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;_

_-- ----------------------------_
_--  Records of `programs_users`_
_-- ----------------------------_
_BEGIN;_
_INSERT INTO `programs_users` VALUES ('1', '2',
'7e0e5eec-c7da-5cf4-a16d-e76f69952910');_
_COMMIT;_

_-- ----------------------------_
_--  Table structure for `users`_
_-- ----------------------------_
_DROP TABLE IF EXISTS `users`;_
_CREATE TABLE `users` (_
-  `id` int(11) NOT NULL AUTO_INCREMENT,*
-  `user_id` varchar(200) DEFAULT NULL,*
-  `username` varchar(100) DEFAULT NULL,*
-  `email` varchar(200) DEFAULT NULL,*
-  `password` varchar(255) DEFAULT NULL,*
-  `active` tinyint(5) DEFAULT '0',*
-  `pin` varchar(200) DEFAULT NULL,*
-  `level` tinyint(5) DEFAULT '0',*
-  `logo` varchar(255) DEFAULT 'default.png',*
-  `name` varchar(200) DEFAULT NULL,*
-  `description` text,*
-  `mission` text,*
-  `vision` text,*
-  `sex_grouping` varchar(50) DEFAULT NULL,*
-  `schooling` varchar(50) DEFAULT NULL,*
-  `teacher_std_ration` varchar(50) DEFAULT NULL,*
-  `class_size` varchar(50) DEFAULT NULL,*
-  `fees_lower` varchar(50) DEFAULT NULL,*
-  `fees_higher` varchar(50) DEFAULT NULL,*
-  `year` varchar(50) DEFAULT NULL,*
-  `address` varchar(250) DEFAULT NULL,*
-  `website` varchar(100) DEFAULT NULL,*
-  `password_reset_status` int(11) DEFAULT '0',*
-  `password_reset_pin` varchar(200) DEFAULT NULL,*
-  `password_reset_date` datetime DEFAULT NULL,*
-  `published` int(5) DEFAULT '0',*
-  `last_login` datetime DEFAULT NULL,*
-  `deleted` tinyint(4) DEFAULT NULL,*
-  `deleted_at` datetime DEFAULT NULL,*
-  `created_at` datetime DEFAULT NULL,*
-  `modified_at` datetime DEFAULT NULL,*
-  PRIMARY KEY (`id`)*
  _) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;_

_-- ----------------------------_
_--  Records of `users`_
_-- ----------------------------_
_BEGIN;_
_INSERT INTO `users` VALUES ('2', '7e0e5eec-c7da-5cf4-a16d-e76f69952910',
'roemics', 'papakay19@gmail.com papakay19@gmail.com',
'$2a$12$ev.SViQk.JzGQu.ZjWKNDud.tQme//IwC4y5oq1YkMaQMeXJ8ltbS', '1', null,
'1', 'user.jpg', 'Kehinde Alabi', null, null, null, null, null, null, null,
null, null, null, null, null, '0', null, null, '0', '2015-04-20 08:17:28',
'0', null, '2015-04-17 05:27:54', null);_
_COMMIT;_

_SET FOREIGN_KEY_CHECKS = 1;_

Atttached is the screenshot of the tables

Thank you greatly!

On Mon, Apr 20, 2015 at 9:10 AM, Adrian Voicu notifications@github.com
wrote:

> Indeed that was an issue, but I think it wasn't the main problem. It only
> added to the main issue. And yet what you wanted was a logical request.
> That is why I mentioned that you should change something inside the
> programs_users table (even if that didn't solve your problem). Please try
> again. I've added a where_in in the query. If it still doesn't work I will
> create the tables just like yours and do it on my test framework.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/avenirer/CodeIgniter-MY_Model/issues/11#issuecomment-94388408
> .

## 

Best Regards,
_ALABI Kehinde Temidayo_

**Comment by avenirer** [comment]
please, make the field `program_id` varchar(200) DEFAULT NULL,\* to be integer and not varchar. Maybe that is the problem.

**Comment by papakay** [comment]
I have just tried that now but no luck yet.

Thanks.

On Mon, Apr 20, 2015 at 10:24 AM, Adrian Voicu notifications@github.com
wrote:

> please, make the field program_id varchar(200) DEFAULT NULL,\* to be
> integer and not varchar. Maybe that is the problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/avenirer/CodeIgniter-MY_Model/issues/11#issuecomment-94405120
> .

## 

Best Regards,
_ALABI Kehinde Temidayo_

**Comment by papakay** [comment]
This is my User_model

<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class User_model extends MY_Model
{

public function __construct()
    {
        $this->timestamps = TRUE;
        $this->has_many_pivot['programs'] =
 array('Program_model','id','user_id');
        parent::__construct();
    }

}

and the call within the controller is this

$user = $this->user_model->with('programs')->paginate(10, $total_users);

On Mon, Apr 20, 2015 at 10:37 AM, Alabi Kehinde papakay19@gmail.com wrote:

> I have just tried that now but no luck yet.
> 
> Thanks.
> 
> On Mon, Apr 20, 2015 at 10:24 AM, Adrian Voicu notifications@github.com
> wrote:
> 
> > please, make the field program_id varchar(200) DEFAULT NULL,\* to be
> > integer and not varchar. Maybe that is the problem.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/avenirer/CodeIgniter-MY_Model/issues/11#issuecomment-94405120
> > .
> 
> ## 
> 
> Best Regards,
> _ALABI Kehinde Temidayo_

## 

Best Regards,
_ALABI Kehinde Temidayo_

**Comment by avenirer** [comment]
Maybe I don't understand but on my test it works... I must be missing something from your explanations.

**Comment by avenirer** [comment]
Does this query generate anything in your mysql client? SELECT \* FROM (`programs`) RIGHT JOIN `programs_users` ON `programs`.`id` =
`programs_users`.`program_id` RIGHT JOIN `users` ON
`programs_users`.`user_user_id` = `users`.`user_id` WHERE `users`.`user_id`
IN ('7e0e5eec-c7da-5cf4-a16d-e76f69952910')

**Comment by papakay** [comment]
Yes it did! I sent you that query earlier. But it wasn't showing user's
program from the output result generated.

On Mon, Apr 20, 2015 at 10:52 AM, Adrian Voicu notifications@github.com
wrote:

> Does this query generate anything in your mysql client? SELECT \* FROM (
> programs) RIGHT JOIN programs_users ON programs.id =
> programs_users.program_id RIGHT JOIN users ON
> programs_users.user_user_id = users.user_id WHERE users.user_id
> IN ('7e0e5eec-c7da-5cf4-a16d-e76f69952910')
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/avenirer/CodeIgniter-MY_Model/issues/11#issuecomment-94410860
> .

## 

Best Regards,
_ALABI Kehinde Temidayo_

**Comment by papakay** [comment]
Here is the query generated

SELECT \* FROM (`programs`) RIGHT JOIN `programs_users` ON `programs`.`id` = `programs_users`.`program_id` RIGHT JOIN `users` ON `programs_users`.`user_user_id` = `users`.`user_id` WHERE `users`.`user_id` IN ('7e0e5eec-c7da-5cf4-a16d-e76f69952910')

And the output result is this

![screen shot 2015-04-20 at 11 02 27 am](https://cloud.githubusercontent.com/assets/5013738/7227993/fea91820-e74c-11e4-90b7-386cb6f93879.png)

I was expecting the program index as well that will show all the programs related to this particular user.

It's only show the user's record only!

And this is what i have inside my controller

$user = $this->user_model->with('programs')->paginate(10, $total_users);

**Comment by papakay** [comment]
I hope it has nothing to do with my PHP version. I use PHP 5.5.19

**Comment by papakay** [comment]
Please what do you think can be done to fix this issue.

**Comment by avenirer** [comment]
give it a try now

**Comment by papakay** [comment]
Okay i will

**Comment by papakay** [comment]
I just did  but no luck.

**Comment by avenirer** [comment]
could you send me an email with a zip file with your controller, models and the sql file?

**Comment by papakay** [comment]
Thanks so much, i have sent it to you.

**Comment by papakay** [comment]
It works fine now! Thanks. I resolved to using "id" instead of "user_id" as the foreign key for my pivot table. Thanks for your support i really appreciate. Cheers!

**Comment by avenirer** [comment]
Sorry if it didn't work your way :)
