### ISSUE TITLE
from_form - Validating an Array (other than $_POST) is missing

### ISSUE THREAD

**Issue by aiamk** [avenirer/CodeIgniter-MY_Model#110]
Dear @avenirer  thank you for your efforts :)

Some times we need to validate values from JSON Request for example.

http://www.codeigniter.com/user_guide/libraries/form_validation.html#id25

http://www.codeigniter.com/user_guide/libraries/form_validation.html#validating-an-array-other-than-post

Kind Regards

**Comment by salain** [comment]
@aiamk 
There is a few ways to get around this
Make your json request as a post instead of get. (preferred) 
OR 
pass your decoded array to $_POST = $your_array 
OR 
use form_validation->set_data($your_array) then  call from_form() with your array as the second parameter.

**Comment by aiamk** [comment]
Thank you @salain , I meant to have this method within the model itself instead of populate manually:

`
foreach($data as $key => $val)
{
     $_POST[$key] = $val;
}
`
