### ISSUE TITLE
logic error update()

### ISSUE THREAD

**Issue by jaycom** [avenirer/CodeIgniter-MY_Model#112]
```
// now let's see if the array is a multidimensional one (multiple rows insert)
$multi = FALSE;
foreach ($data as $element) {
   $multi = (is_array($element)) ? TRUE : FALSE;
}
```

PS:   This code not only at update function, I find more than one, but I don't know how many.

In this code, only check the last one element is array or not, It will miss the other element is array or not.
What this code purpose?
You want to check, if all element is array, then the $data is multi?

**Comment by avenirer** [comment]
I only needed to find out if the array is a multidimensional one... I thought that if at least an element in the array is an array, that would mean that the parent array is a multidimensional. But you are right, there is a logical error in that code. Thank you.

**Comment by jaycom** [comment]
ok
