### ISSUE TITLE
[has_many_pivot] is only return the PK and LOCAL PK

### ISSUE THREAD

**Issue by mortalkiller** [avenirer/CodeIgniter-MY_Model#114]
Hi, 

First of all thanks so much for this script :).

I don't know if I'm doing something wrong ou if is a issue.

I have 3 tables, plants with PK id, plants_properties_type with PK id as well and finally I have a pivot table call plants_properties with PK id, plant_id and property_id. 

However de results only return the fields ID and PLANT_ID

I'm doing something wrong or is a bug? 

Thank you so much.

**Comment by avenirer** [comment]
You need to pass the fields you want returned

``` php
...->with_plants('fields:field1,field2,field3')->get_all();
```

**Comment by mortalkiller** [comment]
Hi, when I ser the fields the script contact the F table, I will show you de code

**Comment by mortalkiller** [comment]
So here is:

I've 3 tables

Plants, Attributes and Attributes_Plants

**Plants_model.php**

```
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Plants_model extends MY_Model {

    public function __construct()
    {
    $this->table = 'plants';
        $this->primary_key = 'id';
    $this->has_many_pivot['proprer'] = array(
            'foreign_model'=>'Attributes_model',
            'pivot_table'=>'attributes_plants',
            'local_key'=>'id',
            'pivot_local_key'=>'plant_id',
            'pivot_foreign_key'=>'attribute_id',
            'foreign_key'=>'id');

        parent::__construct();
    }
}

```

**Attributes_model.php**

```
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Attributes_model extends MY_Model {

    public function __construct()
    {
            $this->table = 'attributes';
        $this->primary_key = 'id';

        parent::__construct();
    }

}
```

My pivot table structure:

```
1   id  int(11) PRIMARY 
2   plant_id    int(11) INDEX FK plants.id      
3   attribute_id    int(11) INDEX FK attributes.id
4   value   varchar(255)    utf8_unicode_ci
```

**Plants_controller.php**

`$data['plants_with_teste'] = $this->plants_model->with_proprer()->get(2);`

And when I print the object, the result is:

```
["proprer"]=>
    object(stdClass)#259 (2) {
      ["1"]=>
      object(stdClass)#258 (2) {
        ["id"]=>
        string(1) "1"
        ["plant_id"]=>
        string(1) "2"
      }
      ["2"]=>
      object(stdClass)#257 (2) {
        ["id"]=>
        string(1) "2"
        ["plant_id"]=>
        string(1) "2"
      }
    }
```

What I'm doing wrong???

**Comment by avenirer** [comment]
As I mentioned in the comment before you need to name the fields you want from the related table: ...with_proper('fields:field1,field2,...,...,field_whatever')...

**Comment by mortalkiller** [comment]
Well....

I change to 

`$data['plants_with_teste'] = $this->plants_model->with_proprer("fields:plant_id,attribute_id,value")->get(2);`

and I get the error:

```
Error Number: 1054

Unknown column 'attributes.plant_id' in 'field list'

SELECT `attributes`.`id`, `attributes_plants`.`plant_id`, `attributes`.`plant_id`, `attributes`.`attribute_id`, `attributes`.`value` FROM `attributes` LEFT JOIN `attributes_plants` ON `attributes`.`id` = `attributes_plants`.`attribute_id` LEFT JOIN `plants` ON `attributes_plants`.`plant_id` = `plants`.`id` WHERE `attributes_plants`.`plant_id` IN('2')

Filename: core/MY_Model.php

Line Number: 1051
```

It seems that the fields are set for the foreign table insted of the pivot.... is this supposed?

**Comment by avenirer** [comment]
Will take a look today...

**Comment by avenirer** [comment]
Will take a look today...

**Comment by mortalkiller** [comment]
Ok! thanks! :+1:

**Comment by Tpojka** [comment]
Shouldn't you have same model structures for each `Plants_model` and `Attributes_model`? 
Saying that Attributes_model should be something like:
    `<?php
    defined('BASEPATH') OR exit('No direct script access allowed');

```
class Attributes_model extends MY_Model
{
    public function __construct()
    {
        parent::__construct();

        $this->table = 'attributes';
        $this->primary_key = 'id';
        $this->has_many_pivot['plants'] = array(
            'foreign_model'=>'Plants_model',
            'pivot_table'=>'attributes_plants',
            'local_key'=>'id',
            'pivot_local_key'=>'attribute_id',
            'pivot_foreign_key'=>'plant_id',
            'foreign_key'=>'id');
    }
}`
```

Also, try to follow @avenirer proposition for naming convention (i.e. models in singular `Attribute_m`).

**Comment by mortalkiller** [comment]
@Tpojka so... should I define the pivot table in the attributes model as well?

**Comment by salain** [comment]
it may be required to have the "pivot", I am not sure but it would be a good thing so you could query the "attributes" table with the related "plants". 

As for your issues/errors. You are requesting the fields from your pivot table :

``` php
$this->plants_model->with_proprer("fields:plant_id,attribute_id,value")->get(2);
```

The fields should be fields from your "attributes" table.

``` php
$this->plants_model->with_proprer("fields:attributes-field1,attributes-field2,etc...")->get(2);
```

The pivot table is only to hold the ids to link the 2 tables that have a many to many relation.
I would also say the the value field in your pivot table should be in the "plants" or "attributes" table.

**Comment by avenirer** [comment]
Oh... thank you @salain. I didn't noticed that @mortalkiller wanted fields from pivot table (which is not possible...).

**Comment by mortalkiller** [comment]
@salain  Thanks, but the relationship that I need is Plants N:N Attributes so the structure I choose was, Tables:
Plants (The table of the flower)
Attriburtes (The table of the possible attributes, for instance, sow dept - This is a dynamic attribute, for plant A could be 1 for plant B could be 2)
Plants_Attributes (Have the plant_id, attribute_id and the value)

So I thinks you could change, (or if you agree I can change and sent you the code) to allow you define the table in the fields like for instance:

`$this->plants_model->with_proprer("fields:attributes.field1,attributes.field2")->get(2);`

In that way what I need will be possible and I think this makes sense.

@avenirer  what you think? 

Thanks!

**Comment by salain** [comment]
@mortalkiller 
First the pivot table should be Attributes_Plants (alphabetical order, read the comments in MY_Model header)
Second you don't need (should not have) the value field in the pivot table as this is part of the Attributes.

So lets assume the Attributes table is:
  id int(11) PRIMARY 
  name  varchar(255)  // attribute name  
  value  varchar(255)  // attribute value  
  etc...

To get all the fields for plant id 2 with all of its attributes you would write :

``` php
$this->plants_model->with_proprer("fields:name,value")->get(2);
```

The problem you are having is you use the pivot table as a data table when it should only be use as a link between plants and attributes. 

I hope this helps.

**Comment by avenirer** [comment]
@salain regarding the name of the pivot table, that rule doesn't apply anymore, because he defined the relationship the right way (by also mentioning the pivotal table name).
Regarding the fact that a pivotal table should be a **pivotal table** and not anything else you are absolutely right.

@mortalkiller ok... try now with fields:table.field and tell me if it works

**Comment by salain** [comment]
@avenirer noted for the naming rule and thank you for adding the option to allow the table in the fields.

**Comment by salain** [comment]
@avenirer 
You need to make the same change to allow the table name in the fields on line 1138.

**Comment by avenirer** [comment]
@salain thank you for noticing that line. I am under the impression that i need more DRY-ness for this...

**Comment by mortalkiller** [comment]
@avenirer it works! thank you so mutch! :+1:

**Comment by avenirer** [comment]
You're welcome.
