### ISSUE TITLE
No method with that name (reset) in MY_Model or CI_Model.

### ISSUE THREAD

**Issue by technical-hostingcastle** [avenirer/CodeIgniter-MY_Model#116]
I have this on my controller:

$query = $this->livecalls_model->on('db_server')->as_array()->get();
$this->livecalls_model->reset();

And this give me error: No method with that name (reset) in MY_Model or CI_Model.

But according to the readme documentation:

> After this, I would advise you to do a $this->user_model->reset(); in order to reset the database connection to the model's (or application's) default.

**Comment by avenirer** [comment]
Sorry about that... I forgot to update manual. It is "reset_connection()"

**Comment by technical-hostingcastle** [comment]
Thanks for a speedy reply.
