### ISSUE TITLE
delete method recognize relationship ?

### ISSUE THREAD

**Issue by prashantnirgun** [avenirer/CodeIgniter-MY_Model#120]
I setup a relation between table A with using (has one) B table.  And in Table B (has_many) A.
Now I want to delete a row from Table B. It allow to delete a row. What should I do so that It will stop / warn me if there is any records in table A?

//Controller B.php
$this->model->delete($id);

I believe it should respect the relationship or do i have to write a manual code before deleting the record?

**Comment by avenirer** [comment]
Manual code.
