### ISSUE TITLE
Getting from_form to work with insert/update.

### ISSUE THREAD

**Issue by louiswalch** [avenirer/CodeIgniter-MY_Model#122]
This is an amazing model, so happy I stumbled upon it and your tutorials. Having problems getting the from form to work. With the example below, when I submit the form, it refreshes the page and shows empty form with var_dump 'false' for id. Even when name is filled out properly.

```
class Product_model extends MY_Model { 

    public $protected = array('product_id');
    public $primary_key = 'product_id';

    public $rules = array(
        'insert' => array(
            'name' => array(
                'field'=>'Name',
                'label'=>'Name',
                'rules'=>'trim|required'),
        ),
        'update' => array(
            'name' => array(
                'field'=>'Name',
                'label'=>'Name',
                'rules'=>'trim|required'),
        ),
    );
}


class Products extends Admin_Controller {

    public function create() {

        $id = $this->product_model->from_form()->insert();
        if ($id === FALSE) {

var_dump($id);

            $this->load->view('product/create');

        } else {

var_dump($id);

            echo  $id;
        }

    }

```

**Comment by avenirer** [comment]
I think the input field name should be the same as the field in your table. Try with 'field'=>'name' and not 'field'=>'Name'

**Comment by louiswalch** [comment]
Thanks, that was the issue! 

Would you mind taking a glance at my edit method too. It works to query for db contents and show edit form, but when submitting is says it's saving but doesn't.

```
    public function edit($id=false) {

        if ($id == FALSE) {
            show_error('You did not specifcy an item to edit.');
        }

        $rules = $this->product_model->rules['update'];
        $this->form_validation->set_rules($rules);

        if ($this->form_validation->run()===FALSE) {

            // User is editing the item. Retreive data from DB and show edit form.

            $item = $this->product_model->get($id);

            if ($item == FALSE) {
                show_error('Item '.$id.' count not be found.');
            }

            $this->load->view('admin/products/edit', array('item'=>$item));

        } else {

            // User is submitted an edit. Save it to the DB and the redirect back to edit (or list) screen.

echo '<pre>' . print_r($this->input->post(), true). '</pre>';
echo '<p>!!UPDATING!!</p>';

            $this->product_model->from_form()->update(NULL, array( $this->product_model->primary_key => $id ));

echo $this->db->last_query();
echo '<p>!!ALL DONE!!</p>';

            // redirect('admin/products/edit/'.$id, 'refresh');

        }
```

For this code, it outputs the following. You can see that the `sku` field is posted, but not saved to database.

```
Array
(
    [name] => asda
    [sku] => adsf
    [product_id] => 5
    [submit] => Submit
)
!!UPDATING!!

UPDATE `products` SET `name` = 'asda', `updated_at` = '2016-03-17 09:28:46' WHERE `product_id` = '5'
!!ALL DONE!!
```

**Comment by avenirer** [comment]
unfortunately, you need to add sku to your validation rules i usually add a "trim" when i don't need validation.

**Comment by louiswalch** [comment]
Ahh ok. Does it got through another validation in from_form? If that's the case maybe I should just do a direct update call from controller instead of routing through from_form.

**Comment by avenirer** [comment]
well... from_form() was actually added for the lazy people. It is up to you whether you use it or not. :)

**Comment by mukund-indianic** [comment]
I am facing issue with from_form() while update result. I tried to set $rules['update'] dynamically 

Model: 

```
    public $table = 'users'; // you MUST mention the table name
    public $primary_key = 'id'; // you MUST mention the primary key
    //public $fillable = array(); // If you want, you can set an array with the fields that can be filled by insert/update
    public $protected = array(); // ...Or you can set an array with the fields that cannot be filled by insert/update
    public $rules = [
        'insert' => [], 
        'update' => []
    ];

   public $validation_config = [
        'update' => [
            'first_name' => [
                    'field'=>'first_name',
                    'label'=>'lang:first_name',
                    'rules'=>'trim|required|xss_clean'
                ],
            'last_name' => [
                    'field'=>'last_name',
                    'label'=>'lang:last_name',
                    'rules'=>'trim|required|xss_clean'
                ],
            'date_of_birth' => [
                    'field'=>'date_of_birth',
                    'label'=>'lang:date_of_birth',
                    'rules'=>'trim|xss_clean'
                ],
            'gender' => [
                    'field'=>'gender',
                    'label'=>'lang:gender',
                    'rules'=>'trim|xss_clean|in_list[male,female]'
                ],
            'status' => [
                    'field'=>'status',
                    'label'=>'lang:status',
                    'rules'=>'trim|xss_clean|in_list[active,inactive]'
                ]
        ]
    ];

public function set_validation_rules($rule_set = '', $operation = 'update'){
        $this->rules[$operation] = $this->validation_config[$rule_set];
    }
```

In controller:
$this->user_model->set_validation_rules('update');`
$res = $this->user_model->from_form()->update(NULL, array('id' => $id));`
It returns false

When I debug $rules it prints $this->user_model->rules perfectly, but when I debug with MY_Model, it is empty

**Comment by avenirer** [comment]
assuming you have CI 3... xss_clean is no longer a valid rule...

**Comment by mukund-indianic** [comment]
Ya I know, I have added security helper, just updated my query

When I try to assign rules, dynamically it is not working

**Comment by avenirer** [comment]
what is the array array('id' => $id) for?

**Comment by avenirer** [comment]
I think that array should be the third parameter, not second, and not in update() method: take a look here

https://github.com/avenirer/CodeIgniter-MY_Model#update-directly-from-form-using-from_form-method

`php $this->user_model->from_form(NULL,NULL,array('user_id'))->update(); // where user_id is an input element`

**Comment by mukund-indianic** [comment]
`$this->user_model->from_form()->update(NULL, array('id' => $id));`
`array('id' => $id)` is my where condition
NULL is my data and I am expecting to get data using `from_form()`
Using `$this->user_model->set_validation_rules('update')` I am dynamically updating `$rules`

I am try to debug inside update function:

```
if(!isset($data) && $this->validated!=FALSE)
        {
            $data = $this->validated;
            $this->validated = FALSE;
        }
        elseif(!isset($data))
        {
            $this->_database->reset_query();
            return FALSE;
        }
```

According to above condition, I will get always false, won't I?

**Comment by avenirer** [comment]
use the format mentioned in the user guide.

**Comment by mukund-indianic** [comment]
Ya it worked, Tx.

**Comment by mukund-indianic** [comment]
I have another issue related update:
When I try to update with following rules, validation always returns true:

```
$rules = [
            'new_password' => [
                'field' => 'new_password',
                'label' => 'lang:new_password',
                'rules' => 'trim|required|min_length[6]|max_length[16]'
            ],
            'confirm_password' => [
                'field' => 'confirm_password',
                'label' => 'lang:confirm_password',
                'rules' => 'trim|required|matches[new_password]'
            ],
        ];

$this->user_model->update(['password' => $pwd, ['id' => $id]);
```

Can you please let me know what could be the reason?

**Comment by avenirer** [comment]
Maybe because you are not using from_form()?...

**Comment by mukund-indianic** [comment]
Yes, I m not using from_form
Is it compulsory to use from_form to work $rules?

**Comment by GarageTech** [comment]
Hi!
Have the similar problem with from_form().
I copy full example from your page:
https://avenir.ro/how-to-edit-a-row-of-data-with-a-form-in-codeigniter/

But problem is - changes take all records in table. No 'id' field pass to MySQL.
When i add profiler to script i see that sql query run like:
UPDATE `groups` SET `name` = '4444'
WHERE 0 = 'id'

If i write:
$this->groups_model->from_form(NULL,array('id' => $id),array('id'))->where_id($id)->update()
all is ok. I add where_id($id) in chain.

Maybe from_form itself have some problems?
All software is latest - apache 2.4 php 7.3.0, codeigniter 3.1.9

Can you help?
