### ISSUE TITLE
if mysql function() used in field() was recognised as column 

### ISSUE THREAD

**Issue by prashantnirgun** [avenirer/CodeIgniter-MY_Model#123]
Hi

I want to the following query to be generated 
select id, concat(salutation, '  ', member_name) as name from member ;

so i write the code
$this->model->field('id, concat(salutation, \' \ ', member_name) as name')->get_all();

it generate the following code
select member.id, ,member.concat(salutation, '  ', member_name) as name from member ;

its considering concat() mysql function as column. Please note I used table relation also.

**Comment by salain** [comment]
@prashantnirgun 
To over come this you need to change your parameter to the fields method to an array and also add the table name to one (or all of the fields in the concat function.

``` php
 $this->model->field(array('id','concat(table.salutation, \' \', member_name) as name'))->get_all();
```

If you look at the implementation of the fields method you will see why you have to do it this way.

**Comment by prashantnirgun** [comment]
thanks it works
