### ISSUE TITLE
how to use Between in where clause for date column?

### ISSUE THREAD

**Issue by prashantnirgun** [avenirer/CodeIgniter-MY_Model#124]
Hi

Is there any way out to set between condition for date column ?
$this->db->where('order_date BETWEEN "'. date('Y-m-d', strtotime($start_date)). '" and "'. date('Y-m-d', strtotime($end_date)).'"');

I know this could be done using following
$this->model->where(array('order_date >=' =>  $start_date, 'order_date <=' => $end_date));

**Comment by salain** [comment]
https://github.com/avenirer/CodeIgniter-MY_Model#wherefield_or_array--null-operator_or_value--null-value--null-with_or--false-with_not--false-custom_string--false

``` php
$this->model->where($custom_where_string,NULL,NULL,FALSE,FALSE,TRUE);
```
