### ISSUE TITLE
Help in with_*('filed:column','where:column = value) giving error

### ISSUE THREAD

**Issue by prashantnirgun** [avenirer/CodeIgniter-MY_Model#125]
Hi

I was trying to put where clause in with_members() its giving the error. Please help me I stuck in between
Problem : I need to generate following SQL 
SELECT \* from loan l join member m on ( l.member_id = m.id) WHERE m.member_name like 'Nisha%'

//Loan Model
 $this->has_one['members']=array('foreign_model'=>'Members_model','foreign_key'=>'id','local_key'=>'member_id');
$this->has_one['loan_types']=array('foreign_model'=>'loan_types_model','foreign_key'=>'id','local_key'=>'loan_type');

//loan Controller
$this->loan_model->
with_members('fields:member_name', 'where:member_name like \'Nisha%\'')->
with_loan_types('fields:scheme_name')->
fields(array('id','lf','member_id','loan_type'))->  
order_by('id','desc')->limit(100)->get_all();

//output
A PHP Error was encountered
Severity: Notice
Message: Undefined index: where
Filename: core/MY_Model.php
Line Number: 1124

Backtrace:
File: /var/www/html/support.local/public_html/application/core/MY_Model.php
Line: 1124
Function: _error_handler

File: /var/www/html/support.local/public_html/application/core/MY_Model.php
Line: 294
Function: join_temporary_results

File: /var/www/html/support.local/public_html/application/core/MY_Model.php
Line: 955
Function: _prep_after_read

File: /var/www/html/support.local/public_html/application/controllers/Loans.php
Line: 125
Function: get_all

File: /var/www/html/support.local/public_html/index.php
Line: 292
Function: require_once

**Comment by prashantnirgun** [comment]
is there any problem with subject line ?

**Comment by avenirer** [comment]
Try doing it like this and tell me if it works, please:

``` php
$this->loan_model->
with_members('fields:member_name|where:`member_name` like \'Nisha%\'')->............;
```

**Comment by andresen007** [comment]
Hey I have a smiliar problem.

**Model:**
class Hold_model extends MY_Model
{
    public $table = 'hold'; 
    public $primary_key = 'id'; 
    public function __construct()
    {
        $this->has_one['bruger'] = array('Bruger_model', 'vucID', 'kursist_id');
        $this->has_one['logbog'] = array('Logbog_model', 'kursist_id', 'kursist_id');
        parent::__construct();
    }
}

**Controller:**
$data['hold'] = $this->Hold_model->where('hold_id',$id)
                                            ->with_bruger('fields:fornavn,efternavn,status,status_start,status_slut,telefon')
                                             ->with_logbog('where:hold_id='.$id.'', 'order_by:id,ASC')
                                             ->get_all();
- if with_logbog is setup with 'where:hold_id='.$id.'', 'order_by:id,ASC' it will break if there is no match. 
- if with_logbog is setup empty it will return a empty array if there is no match, but if there are a match it can come from another "hold_id" and that dont make sens in this case!

picture of the two situation: http://imgur.com/a/xOkGp 
1. picture with no where clause. 
2. Picture with where clause.

Valisa dont have a "log" on this "hold_id", but have the log from another "hold_id", so it should be an empty array, but no it just break it and "Valisa" is not in the main-array.

I dont understand why it will break and why it is not making a empty array. I need to set Where clause in "with_logbog".

Thank you for all of ur work !!!

**Comment by prashantnirgun** [comment]
it breaks I try out all possible values. The only difference is with_model(field:1,2,3|where = 'val') 
with contain (fields and where ).

I had a question with__() is performance hogging ? 
I found it generate array() for each with__ and it contain the values n number of times where n is the row count of main model of query?

**Comment by avenirer** [comment]
This is weird behaviour... In my tests  (Test controller) it works without any problems. Regarding the "performance hogging" with each "with_*()" method it creates another query. In your particular case it creates three queries.

**Comment by andresen007** [comment]
Hey Avenirer,

yes, but it break if there are no "result" with the "where clause" - Do I my a mistake in the ->with_logbog('where:hold_id='.$id.'', 'order_by:id,ASC') ? 

What do u else need to solve the problem :) ?

**Comment by avenirer** [comment]
@andresen007 I don't know if your issue is the same with @prashantnirgun . But... did you escape the quotes, because i see you have two quotes after $id... also, what do you mean by "it will break if there is no match"? If by "break" you mean that the result isn't returned, this is normal. Because you have an exclusive where in there. If you want to appear you should do a non-exclusive where ('non_exclusive_where:...');

**Comment by andresen007** [comment]
Hey,

if I do a 'non_exclusivist_where:hold_id=5' it just take a random entry from another "hold_id" if there is no match for "hold_id=5 ?!

See picture:
http://imgur.com/1yr7q2u

I really dont understand how "non_exclusivist_where" works !  :(

**Comment by andresen007** [comment]
Hey again,

I misunderstand ur question: If by "break" you mean that the result isn't returned, this is normal. 

The main array breaks, as you see in the picture: http://imgur.com/a/xOkGp (second picture), the entry with "Valisa" is not in the main-array because there are no entry with her in the "logbog".

**Comment by avenirer** [comment]
You are showing me an interface. you are not showing me an array... or an object result. Also, I guess in the manual is written "non_exclusivist_where"... but it is actually "non_exclusive_where:...".
