### ISSUE TITLE
Rows with soft delete still shows when getting data from the DB

### ISSUE THREAD

**Issue by papakay** [avenirer/CodeIgniter-MY_Model#13]
![screen shot 2015-04-21 at 7 03 14 am](https://cloud.githubusercontent.com/assets/5013738/7247299/026ce276-e800-11e4-8103-6b12819aa0cf.png)

After setting $this->soft_deletes to true and used $this->user_model->delete(3), the row with the id still shows up when getting result.

I confirmed that deleted_at and updated_at were not NULL.

Please what could have caused this?

Thank you.

**Comment by avenirer** [comment]
With what are you getting the result? get_all()? get()? paginate()?

**Comment by papakay** [comment]
paginate()

**Comment by avenirer** [comment]
please, try now...

**Comment by papakay** [comment]
I have tried and the result is still the same. 
Below are the queries generated.

SELECT COUNT(*) AS `numrows` FROM (`users`) WHERE deleted_at IS NULL
SELECT \* FROM (`users`) LIMIT 10
SELECT \* FROM (`type_users`) WHERE `user_id` IN ('2', '3') 
SELECT \* FROM (`programs`) RIGHT JOIN `programs_users` ON `programs`.`id` = `programs_users`.`program_id` RIGHT JOIN `users` ON `programs_users`.`user_id` = `users`.`id` WHERE `users`.`id` IN ('2', '3')

i think

SELECT \* FROM (`users`) LIMIT 10
should have carried something like this  SELECT \* FROM (`users`) WHERE deleted_at IS NULL LIMIT 10

**Comment by avenirer** [comment]
could you try again now? :D

**Comment by papakay** [comment]
Worked fine now! Thanks.
