### ISSUE TITLE
Pivot table relationships - How to query?

### ISSUE THREAD

**Issue by louiswalch** [avenirer/CodeIgniter-MY_Model#131]
I have a inventory model which is related to a pivot table to allow for assigning categories to the products. Is there a streamlined way to query for results for only products contained within a specific (or set of) categories?

```

        $this->has_many_pivot['categories'] = array(
            'foreign_model'     => 'category_model',
            'pivot_table'       => 'inventory_to_categories',
            'local_key'         => 'inventory_id',
            'pivot_local_key'   => 'inventory_id',
            'pivot_foreign_key' => 'category_id',
            'foreign_key'       => 'category_id',
            );
```

**Comment by avenirer** [comment]
``` php
$category_with_products = $this->category_model->with_products('fields:product_name,product_sku')->get($category_id);
print_r($category_with_products);
```

**Comment by louiswalch** [comment]
Thanks for the reply. I am hoping do to this by running query through the inventory_model because I will eventually have to join in other tables to match against as well (e.g. manufacturer, color). Is there an easy way to do that?

**Comment by avenirer** [comment]
i don't understand your question... but if that is in your inventory you do it through inventory_model

``` php
$products = $this->inventory_model->with_......
```

**Comment by louiswalch** [comment]
I am trying to get products which are linked only to a certain category, but need to query through the inventory model.

**Comment by avenirer** [comment]
``` php
$products = $this->inventory_model->with_products('fields:product_name,product_sku|where:`categories`.`id`=\''.$category_id.'\'')->get($inventory_id);
print_r($products);
```

**Comment by louiswalch** [comment]
Sorry, I think I should detail more what I am trying to do to clear things up. I have the following tables:

**inventory**
- inventory_id
- name

**categories**
- category_id
- name

**inventory_to_category**
- inventory_id
- category_id

I then have an `inventory_model` which has a pivot table to allow inventory products to have categories:

```
$this->has_many_pivot['categories'] = array(
    'foreign_model'     => 'category_model',
    'pivot_table'       => 'inventory_to_categories',
    'local_key'         => 'inventory_id',
    'pivot_local_key'   => 'inventory_id',
    'pivot_foreign_key' => 'category_id',
    'foreign_key'       => 'category_id',
    );
```

Then saying I have an array which contains ids of category ids.

```
$show_only = array(4,5);
```

I would like to query inventory_model to show only items inside it which have been linked to those categories referenced by `show_only`.

**Comment by avenirer** [comment]
Can a category be part of more than one inventory?

**Comment by louiswalch** [comment]
Yes. And an inventory can be in more then one category.

**Comment by avenirer** [comment]
I guess it would be easier for you (and me...) to create a separate method in your model and join the tables.

**Comment by louiswalch** [comment]
Ok, let me try that.
