### ISSUE TITLE
order_by in relations problem

### ISSUE THREAD

**Issue by xprezesx** [avenirer/CodeIgniter-MY_Model#132]
You have an array if you return data in object and wanna order_by in RELATIONSHIPS using ->with_ method.

Change method _build_sorter in something like this:

```
private function _build_sorter($data, $field, $order_by, $sort_by = 'DESC')
{
    usort($data, function($a, $b) use ($field, $order_by, $sort_by) {
        $array_a = (array) $a[$field];
        $array_b = (array) $b[$field];
        return strtoupper($sort_by) ==  "DESC" ? ((array) $array_a[$order_by] < (array) $array_b[$order_by]) : ((array) $array_a[$order_by] > (array) $array_b[$order_by]);
    });

    return $data;
}
```

(CONVERT type to ARRAY)

**Comment by avenirer** [comment]
Thank you @xprezesx. Please verify if it works. Also, @afbora, considering you did the _build_sorter() method, could you verify if everything works?

**Comment by xprezesx** [comment]
Yes. It's works now. Thanks @avenirer .
