### ISSUE TITLE
how can I do a where in statement?

### ISSUE THREAD

**Issue by bvfbarten** [avenirer/CodeIgniter-MY_Model#134]
Because of the magic where_\* function, it appears that doing a where_in like codeigniter does is broken.  Is there an alternative to this?  Since where_\* is deemed as buggy, could we just switch it to CodeIgniter's default behavior?

**Comment by salain** [comment]
Hi,
Look at the last example will give you a where_in just like CI. [where example](https://github.com/avenirer/CodeIgniter-MY_Model#examples-2)

**Comment by bvfbarten** [comment]
Thank you, Salain!
