### ISSUE TITLE
Relationships

### ISSUE THREAD

**Issue by ghost** [avenirer/CodeIgniter-MY_Model#14]
This don't work:
<code>foreach ($sub_results as $result) {
    $subs[$result[$foreign_key]][] = $result;
}</code>
This does:
<code>
foreach($sub_results as $key => $result)
{
    $subs[$local_key_values[$key]][] = $result;
}
</code>

**Comment by avenirer** [comment]
Hello. Could you give me an example where it didn't work?

**Comment by francisalfanta** [comment]
I believe if you did not place any as_array () or as_object () in $sub_results you will get a problem.

**Comment by avenirer** [comment]
Well... Before doing anything with the data , that data is transformed. So I don't think there is a problem. But if you find one, tell me about it, and we will try to solve it together. :+
