### ISSUE TITLE
Set custom language on the "rules"

### ISSUE THREAD

**Issue by hossj** [avenirer/CodeIgniter-MY_Model#141]
When we set rules for input fields, how can I for example instead of the "Title" label place $this->lang->line('title') so that the validation happens accordingly to language?

Right now I am getting an error when passing on any variable.

**Comment by avenirer** [comment]
what error are you getting?

**Comment by hossj** [comment]
Thanks for the quick reply.
It is not possible to pass on a variable.

'field'=>'title',
'label'=>$this->lang->line('title'),
rules'=>'trim|required'),

I get a syntax error:

A PHP Error was encountered
Severity: Parsing Error
Message: syntax error, unexpected '$this' (T_VARIABLE)
Filename: models/Article_model.php
Line Number: 25
Backtrace:

**Comment by avenirer** [comment]
https://www.codeigniter.com/userguide3/libraries/form_validation.html#translating-field-names

**Comment by avenirer** [comment]
...or I think you should first load the language inside the model:

$idiom = $this->session->get_userdata('language');
$this->lang->load('error_messages', $idiom);

https://www.codeigniter.com/userguide3/libraries/language.html#example-of-switching-languages

**Comment by hossj** [comment]
Perfect!
I really should have reviewed that prior to asking. Thanks a lot.
