### ISSUE TITLE
Feature Request Drop down with optgroup

### ISSUE THREAD

**Issue by prashantnirgun** [avenirer/CodeIgniter-MY_Model#145]
Thanks for creating the wonderful library. My request to you is to create the function which will generate the drop down with optgroup.
<xmp>
<select>
<optgroup label="Swedish Cars">
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
  </optgroup>
  <optgroup label="German Cars">
    <option value="mercedes">Mercedes</option>
    <option value="audi">Audi</option>
  </optgroup>
</select>
</xmp>

**Comment by avenirer** [comment]
That would be a bit too specific...
