### ISSUE TITLE
update with protected field

### ISSUE THREAD

**Issue by salain** [avenirer/CodeIgniter-MY_Model#147]
Hi, 

This maybe just a misunderstanding on my part.
if I set primary key as protected in the constructor 
When I try to update a batch of records with the id as the record reference 

``` php
 public function __construct()
    {
        $this->table = 'status';
        $this->primary = 'id';
        $this->protected =array('id');
   ....
}
function reorder(){
$data = array(array('id' => 3, 'order' => 1),array('id' => 4, 'order' => 2),array('id' => 6, 'order' => 3),array('id' => 4, 'order' => 4));

$this->update($data,'id');
....
```

I get an error Undefined index: id from MY_Model update method. 

is there a workaround or do I have to loop on the array and update one record at the time?

``` php
foreach($data as $item){
  $id = array_shift($item);
  $this->update($item,$id);
}
```

Thank you
Salain

**Comment by avenirer** [comment]
Yes... I don't remember why I didn't use update_batch() for the update of multiple data, but something didn't work right at that time. It needs an update here...

**Comment by salain** [comment]
Thanks.
I will see if I can come up with a solution
