### ISSUE TITLE
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 523800 bytes)

### ISSUE THREAD

**Issue by PandaTwo** [avenirer/CodeIgniter-MY_Model#15]
Hi.
first thx dev share My_Model

i add to model for my probject, i get error like issues title.

i try change php.ini  item "memory_limit" ,but it's not work.

hope you Know what I mean.

myCI version:2.2.

**Comment by avenirer** [comment]
Hello, if you got that error, the problem must be somewhere else. Show me the code that resulted in that error: the model and controller.
