### ISSUE TITLE
working with date_add()

### ISSUE THREAD

**Issue by svennd** [avenirer/CodeIgniter-MY_Model#158]
With this query I get 1 result back on the mysql console : 
`select date_dive from table where date_dive > DATE_ADD(NOW(), INTERVAL -3 DAY);`

However with my_model I get nothing... should I write a query myself or can it be done using this library ? This was what I tried :
`$this->model->where('date_dive >' , 'DATE_ADD(NOW(), INTERVAL -3 DAY)')->get_all();`

**Comment by seicke** [comment]
Try

`... ->where('date_drive > DATE_ADD(NOW(), INTERVAL -3 DAY)', null, null, false, false, true)-> ...
`

**Comment by svennd** [comment]
That will probably work, but since I used agregate functions, I just wrote my own query seperatly.

Thanks !
