### ISSUE TITLE
issue to retrieve json encoded result for non UTF8 charter like spanish "ñ"

### ISSUE THREAD

**Issue by gargolan** [avenirer/CodeIgniter-MY_Model#16]
The methods get() return null for charter like ñ á, é etc. I resolve this adding an method for encoding utf8.
    public function _prep_after_read($data, $multi = TRUE)
    {
        // let's join the subqueries...
        $data = $this->join_temporary_results($data);
        $this->_database->reset_query();
        if($this->return_as == 'object')
        {
            $data = $this->utf8_encode_all($data); //Call to utf8 encode;
            $data = json_decode(json_encode($data), FALSE);
        }
        return $data;
    }

```
private function utf8_encode_all($dat){ // -- It returns $dat encoded to UTF8

    if (is_string($dat)) return utf8_encode($dat);
    if (!is_array($dat)) return $dat;
    $ret = array();
    foreach($dat as $i=>$d) $ret[$i] = $this->utf8_encode_all($d);
    return $ret;
}
```

and works fine. Thank  you  very much for your a good job.

**Comment by avenirer** [comment]
As I know, the json_encode() is already encoding data in UTF8. Maybe the problem is at the database... The tables should be utf encoded...?
