### ISSUE TITLE
Like OR Like How to ?

### ISSUE THREAD

**Issue by codeigniterd** [avenirer/CodeIgniter-MY_Model#163]
$where.= " AND ( movie LIKE '".$search."%' OR year LIKE '".$search."%' OR genre LIKE '".$search."%' ) ";
I have a query like this ?

How do it write this using the model ?

**Comment by emrahoruc** [comment]
Check out this, https://www.codeigniter.com/userguide3/database/query_builder.html#query-grouping

``` php
$this->db->group_start();
    $this->db->like('movie', $search, 'both');
    $this->db->or_like('year', $search, 'both');
    $this->db->or_like('genre', $search, 'both');
$this->db->group_end();
```

**Comment by codeigniterd** [comment]
@zilzurna I have code in controller like this How do i modify it ?

$userDetails = $this->user_model->as_array()->where('user_fname like ', '%'.$search.'%' )->where('user_mname like ', '%'.$search.'%' )->where('user_lname like ', '%'.$search.'%' )->where('user_dob like ', '%'.$search.'%')->where('user_email like ', '%'.$search.'%' )->where('user_phone1 like ', '%'.$search.'%' )->order_by($orderKey, $orderValue)->limit($limit)->get_all();

Thanks for previous reply.

**Comment by emrahoruc** [comment]
It will be like this;

``` php
$this->db->group_start()
    ->like('user_fname', $search, 'both')
    ->or_like('user_mname', $search, 'both')
    ->or_like('user_lname', $search, 'both')
    ->or_like('user_dob', $search, 'both')
    ->or_like('user_email', $search, 'both')
    ->or_like('user_phone1', $search, 'both')
->group_end();
$userDetails = $this->user_model->as_array()
    ->order_by($orderKey, $orderValue)
    ->limit($limit)
->get_all();
```

**Comment by codeigniterd** [comment]
Awesome @zilzurna ! Thanks a Lot.
I am closing this issue now !!

**Comment by emrahoruc** [comment]
@codeigniterd , you're welcome. :+1:
