### ISSUE TITLE
RAND() selection

### ISSUE THREAD

**Issue by papakay** [avenirer/CodeIgniter-MY_Model#164]
Hi, i want to appreciate the great effort you have put into this library. Very intuitive and useful.

Please i want to know if there is a way to randomise record selection from the database.

Thank you

**Comment by emrahoruc** [comment]
It is simple, just like this.

``` php
$rand_user = $this->Users_model->order_by('rand()')->get();
/*
SELECT *
FROM `users`
ORDER BY rand() ASC
 LIMIT 1
*/
```

**Comment by papakay** [comment]
Thanks @zilzurna for this nice tip. It worked!

**Comment by emrahoruc** [comment]
@papakay not at all :+1:
