### ISSUE TITLE
Getting the Has_many_pivot record

### ISSUE THREAD

**Issue by papakay** [avenirer/CodeIgniter-MY_Model#165]
Hello, please i have the following tables tags, uploads and tags_uploads with respective model name Tag and Upload.

In my Upload model i have a line as below
`$this->has_many_pivot['tags'] = array(
            'foreign_model'=>'Tag',
            'pivot_table'=>'tags_uploads',
            'local_key'=>'id',
            'pivot_local_key'=>'uploads_id',
            'pivot_foreign_key'=>'tags_id',
            'foreign_key'=>'id');`

Also in my Tag model i have this
`$this->has_many_pivot['uploads'] = 'Upload';`

When i use this `$this->Upload->with_tags()->limit(4,0)->get_all();` in my controller it returns an object node tags however the result only include the tag id, i want the other fields (columns) on tags table to be returned as well

Please how do i achieve this? Thank you.

**Comment by Tpojka** [comment]
Use full code syntax for has_many_pivot relation described [here](https://github.com/avenirer/CodeIgniter-MY_Model#has-many-pivot-relationship-property) and set last array key to TRUE `'get_relate'=>TRUE`.

**Comment by papakay** [comment]
Thanks immensely @Tpojka , it worked.
