### ISSUE TITLE
with_*('fields:...') and 'with'=>array('relation'=>'companies','fields'=>'name,phone_number') 

### ISSUE THREAD

**Issue by papakay** [avenirer/CodeIgniter-MY_Model#166]
Hello, thanks for your support so far. It has been amazing how swiftly you respond to issues. I appreciate you so much.

Please after following guide in this section https://github.com/avenirer/CodeIgniter-MY_Model#working-with-relationships, i decided to implement it in my code but i'm experiencing some errors.

I have this line in my controller `$this->Upload->with_tags()->with_users('fields:id,last_name,first_name,username', 'with'=>array('relation'=>'tags','fields'=>'name,slug'))->limit(4,0)->order_by('rand()')->get_all();` I got this error `A PHP Error was encountered
Severity: Parsing Error
Message: syntax error, unexpected '=>' (T_DOUBLE_ARROW)
Filename: controllers/HomeController.php
Line Number: 14
Backtrace:` And  when i removed `'with'=>array('relation'=>'tags','fields'=>'name,slug')` from the with_users() arguments, the users node still returns all the fields in the users table instead of only the indicate fields (in the argument).

My Upload model construct looks like this `$this->table = 'uploads';
        $this->primary_key = 'id';
        $this->soft_deletes = false;
    $this->timestamps = array('created_at', 'modified_at');
        $this->has_many_pivot['tags'] = array(
            'foreign_model'=>'Tag',
            'pivot_table'=>'tags_uploads',
            'local_key'=>'id',
            'pivot_local_key'=>'uploads_id',
            'pivot_foreign_key'=>'tags_id',
            'foreign_key'=>'id',
            'get_relate'=>TRUE
        );
        $this->has_many_pivot['users'] = array(
            'foreign_model'=>'User',
            'pivot_table'=>'uploads_users',
            'local_key'=>'id',
            'pivot_local_key'=>'uploads_id',
            'pivot_foreign_key'=>'users_id',
            'foreign_key'=>'id',
            'get_relate'=>TRUE
        );`

and my User model construct looks like this `$this->table = 'users';
        $this->primary_key = 'id';
        $this->soft_deletes = false;
        $this->timestamps = array('created_at', 'modified_at');
        $this->has_many_pivot['tags'] = array(
            'foreign_model'=>'Tag',
            'pivot_table'=>'users_tags',
            'local_key'=>'id',
            'pivot_local_key'=>'uploads_id',
            'pivot_foreign_key'=>'users_id',
            'foreign_key'=>'id',
            'get_relate'=>TRUE
        );`

Please how can i resolve this. Thank you.

**Comment by emrahoruc** [comment]
It is just a php syntax error, use this.

``` php
$this->Upload->with_tags()->with_users([
   'fields' => 'id,last_name,first_name,username',
   'with' => [
      'relation'=>'tags',
      'fields'=>'name,slug'
   ]
])->limit(4,0)->order_by('rand()')->get_all();
```

**Comment by papakay** [comment]
@zilzurna thanks for sharing your knowledge. I have tried the options provided but not working as expected. No errors but it still returns all the columns in the users table (instead of the specified fields). Also it's not returning the users tags.

Please what can i do to get this working?

**Comment by Tpojka** [comment]
Maybe not related to current issue, but shouldn't be in `User_m.php` - `$this->has_many['uploads']` and in `Upload_m.php` - `$this->has_one['user']` (since, afaik, there is no way one file is uploaded by more than one user)?

**Comment by papakay** [comment]
Thanks for your swift responses.

I have tried the option above @Tpojka but it seems not to be working well for me - `User_m.php - $this->has_many['uploads']` and `Upload_m.php - $this->has_one['user']`.  Please find attached my table schema
![db_relationship](https://cloud.githubusercontent.com/assets/5013738/18034160/996aab82-6d2d-11e6-99b9-7cf3866a39c6.png)

Please what could i be doing wrong?

**Comment by Tpojka** [comment]
I think your `Upload_m.php` model should have property like:
`$this->has_one['user'] = array('foreign_model'=>'User_m','foreign_table'=>'users','foreign_key'=>'user_id','local_key'=>'id');`

and in `User_m.php`
`$this->has_many['uploads'] = array('foreign_model'=>'Upload_m','foreign_table'=>'uploads','foreign_key'=>'upload_id','local_key'=>'id');`

Check naming convention you are using regarding file names etc. 
This is more about design architecture but no bug tracking which github is supposed to be. 
If you feel this design pattern I propose could fit your business model, make it that way and then you can see if you have problem with `MY_Model.php` file.

**Comment by papakay** [comment]
Thank you so much for the assistance rendered.
