### ISSUE TITLE
Using LIKE for two columns

### ISSUE THREAD

**Issue by papakay** [avenirer/CodeIgniter-MY_Model#168]
Hello,

Please i'm working on a search future within my app however i'm not getting the desired results.

I want to be able to use LIKE in two columns. Please see below my code

**$condition = array(
                'published' => 1,
                'is_public' => 1,
                'title LIKE' => '%'.$keyword.'%',
                'description LIKE' => '%'.$keyword.'%'
            );
            $query = $this->Upload->with_tags()->where($condition)->order_by('title', 'ASC')->get_all();**

Either of the LIKE works but not both.

Please how can i implement this for both.

Thank you.

**Comment by emrahoruc** [comment]
Check out this,
https://github.com/avenirer/CodeIgniter-MY_Model/issues/163

**Comment by papakay** [comment]
Thanks @zilzurna  it worked

**Comment by emrahoruc** [comment]
@papakay, you're welcome. 👍
