### ISSUE TITLE
paginate() returns nothing

### ISSUE THREAD

**Issue by ngangchill** [avenirer/CodeIgniter-MY_Model#17]
there are 2 posts within the date range.   when i replace paginate() method with get_all()  it returns 2 posts.

Model:

```
 if ($month) {
           $next_month = $month + 1;
           $from = date("Y-m-d H:i:s", mktime(0, 0, 0, $month, 0, $year));
           $to = date("Y-m-d H:i:s", mktime(23, 59, 59, $next_month, 0, $year));
        } else {
           $from = date("Y-m-d H:i:s", mktime(0, 0, 0, 1, 0, $year));
           $to = date("Y-m-d H:i:s", mktime(0, 0, 0, 1, 0, ($year + 1)));
        }
          $total_rows = $this->where(array('dateCreated >' => $from,'dateCreated <' => $to, 'published' > 1))->count();


     $data['posts'] = $this->where(array('dateCreated >' => $from,'dateCreated <' => $to, 'published' > 1))
           ->fields('(SELECT COUNT(*) from blog_comments where blog_comments.postID = blog_posts.postID and deleted = 0 and active = 1) AS numComments, blog_posts.*', FALSE)
            //->order_by('dateCreated', 'desc')
            ->paginate(1,$total_rows);


    $data['all_links'] = $this->all_pages; // will output links to all pages like this model: "< 1 2 3 4 5 >". It will put a link if the page number is not the "current page"
    $data['older'] = $this->previous_page; // will output link to the previous page like this model: "<". It will only put a link if there is a "previous page"
    $data['newer'] = $this->next_page; //

    return $data;
```
## result:

```
     Dump => array(4) {
     ["posts"] => bool(false)
    ["all_links"] => string(270) "<12>"
    ["older"] => string(69) "<"
    ["newer"] => string(69) ">"
    }
```

**Comment by ngangchill** [comment]
there are 2 posts within the date range.   when i replace paginate() method with get_all()  it returns 2 posts.

**Comment by avenirer** [comment]
where(array('dateCreated >' => $from,'dateCreated <' => $to, 'published' > 1)). ...well... I don't think that is a good array (look at "published")....

**Comment by ngangchill** [comment]
i removed 'published' from the array   but it returns same result.

```
    $data['posts'] = $this->where(array('dateCreated >' => $from,'dateCreated <' => $to))
            ->fields('(SELECT COUNT(*) from blog_comments where blog_comments.postID = blog_posts.postID and deleted = 0 and active = 1) AS numComments, blog_posts.*', FALSE)
            ->paginate(1,$total_rows);
```

**Comment by avenirer** [comment]
well... I must say that your way of using MY_Model is very original... How in the world did you manage to put an entire query in the fields() method?

**Comment by ngangchill** [comment]
i have some other method in Blog_m.php which  works fine such. i cant feagure it out why this is happening.

 i will rewrite this function and i need ur help.  give me some idea how can i do this.

with_*() method i will get the posts table  along with comment table but i need all fields from posts table and only  comments row that is related with every posts as comments_ count from the comments table

**Comment by avenirer** [comment]
why don't you ask for a single field from comments_count and when outputing, instead of doing a foreach do a sizeof()? Or you can create a post_get callback.
