### ISSUE TITLE
Two table join and seach functionalities

### ISSUE THREAD

**Issue by codeigniterd** [avenirer/CodeIgniter-MY_Model#172]
I have to tables as follows

```
CREATE TABLE `tbl_blog_post` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `subtitle` varchar(255) DEFAULT NULL,
  `article` text,
  `author_id` int(11) NOT NULL,
  `date_published` date DEFAULT NULL
);
```

```
CREATE TABLE `tbl_user` (
  `id` bigint(20) NOT NULL,
  `user_username` varchar(255) NOT NULL,
  `user_password` text NOT NULL,
  `user_title` varchar(10) DEFAULT NULL,
  `user_fname` varchar(255) NOT NULL,
  `user_mname` varchar(255) DEFAULT NULL,
  `user_lname` varchar(255) NOT NULL,
  `user_dob` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

Here author_id of tbl_blog_post table has one to one relationship with id of tbl_user table.

I want ot seach all tbl_blog_post data with user which user_fname is 'Neil' or  user_mname is 'xxx' and/or title is like 'xxxx' .

I have got this so far.

```
$this->db->group_start()
    ->like('title', $search, 'both')
->group_end();

$condition = array(
    'user_fname LIKE' => '%'.$search.'%',
    'user_mname LIKE' => '%'.$search.'%',
    'user_lname LIKE' => '%'.$search.'%',
);

$blogDetails = $this->blog_model->with_author_id()->where($condition)->as_array()->order_by($orderKey, $orderValue)->limit($limit_h, $limit_l)->get_all();
```

But not getting desired result.

In Model Page

```
class Blog_model extends Back_Model {

    public $table = 'tbl_blog_post';
    public $primary_key = 'id';
    public $fillable = array();
    public $protected = array();
    public function __construct()
    {
        $this->has_one['author_id'] = array('foreign_model'=>'Login_model','foreign_table'=>'user','foreign_key'=>'id','local_key'=>'author_id');
        parent::__construct();
    }

}
```

Query is not working.. @zilzurna

**Comment by codeigniterd** [comment]
No Reply Guys !!

**Comment by avenirer** [comment]
Where did you put that group_start?

**Comment by codeigniterd** [comment]
@avenirer 
It is written as follows..

```
$search = 'Search Phrase';
$this->load->model('blog_model');

$this->db->group_start()
    ->like('title', $search, 'both')
    ->or_like('featured', $search, 'both')
    ->or_like('date_published', $search, 'both')
->group_end();

$condition = array(
    'user_fname LIKE' => '%'.$search.'%',
    'user_mname LIKE' => '%'.$search.'%',
    'user_lname LIKE' => '%'.$search.'%',
);

$blogDetails = $this->blog_model->with_author_id()->where($condition)->as_array()->order_by($orderKey, $orderValue)->limit($limit_h, $limit_l)->get_all();
```

**Comment by salain** [comment]
Your $condition array is a where clause for the tbl_user, so it has to be a parameter of the with_author_id method.  [Look here for the usage](https://github.com/avenirer/CodeIgniter-MY_Model#working-with-relationships)

**Comment by avenirer** [comment]
Not really related to your issue (as @salain told you, read the instructions), but the way you've set the $condition, will most likely return nothing. For example, if you search something like "Neil" you won't get any results as the final query will end up searching for a record that has in the first name a string "Neil" AND in the middle name a string "Neil" AND in the last name a string named... also... "Neil". So it would indeed be a good idea to RTFM.

**Comment by codeigniterd** [comment]
I have tried all way but not got any success.

```
CREATE TABLE `tbl_blog_post` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `subtitle` varchar(255) DEFAULT NULL,
  `article` text,
  `author_id` int(11) NOT NULL,
  `date_published` date DEFAULT NULL
);

CREATE TABLE `tbl_user` (
  `id` bigint(20) NOT NULL,
  `user_username` varchar(255) NOT NULL,
  `user_password` text NOT NULL,
  `user_title` varchar(10) DEFAULT NULL,
  `user_fname` varchar(255) NOT NULL,
  `user_mname` varchar(255) DEFAULT NULL,
  `user_lname` varchar(255) NOT NULL,
  `user_dob` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

Here author_id of tbl_blog_post foreign key id of tbl_user table.

I want ot seach all tbl_blog_post data with user which user_fname is 'Neil' or user_mname is 'xxx' or title is like 'xxxx' .
How do i get this ? @avenirer @salain 

actually i have e search box which took free text input and i have to search the data containing that free text in all area like in article, fname, mname, lname title , subtitle etc etc
