### ISSUE TITLE
question : how to mix personnal function and with_

### ISSUE THREAD

**Issue by stefanKBL** [avenirer/CodeIgniter-MY_Model#173]
Hi, 
i try to call from controller a dedicated function (into model with specific query builder) and want to add the with_ method.
ex. 2 models : posts and comments, both extends of course MY_MODEL
relation has_many into posts model is ok to comments model.
$this->has_many['comments'] = array('foreign_model'=>'posts_comments_model','foreign_table'=>'posts_comments','foreign_key'=>'post_id','local_key'=>'id');

so in controller i need to do something like
$posts = $this->posts_model->mydedicatedfunction($param1,$paramN)->with_comments()->get();

but return message is 
Call to undefined method CI_DB_mysqli_result::with_comments()

**Comment by salain** [comment]
I think the issue is with chaining. 
The method mydedicatedfunction must return $this object for chaining to work.
A quick test to try this 

``` php
$this->posts_model->mydedicatedfunction($param1,$paramN);
$posts = $this->posts_model->with_comments()->get();
```

If this works then just add return $this in your method

``` php
public function  mydedicatedfunction($param1,$paramN){
 //do something with the param

return $this;
}
```

**Comment by stefanKBL** [comment]
thanks. i'll try this.

**Comment by stefanKBL** [comment]
not working, because $params of mydedicatedfunction are result of the $post return.
Never mind, i dit it with another method : first get $post via my_model and then access another method with params.
Thanks
