### ISSUE TITLE
Incorrect function call

### ISSUE THREAD

**Issue by sjarifHD** [avenirer/CodeIgniter-MY_Model#180]
When I try your sample use `MY_Model.php` I get error when using `with_*()`

After I look at `MY_Model.php`, I found incorrectness when call a function in `_set_relationships()` function.  There is: 
`$model = _parse_model_dir($foreign_model);`

and it should be:
` $model = $this->_parse_model_dir($foreign_model);`

**Comment by avenirer** [comment]
Thank you for noticing that.
