### ISSUE TITLE
GET return false when geometry field

### ISSUE THREAD

**Issue by stefanKBL** [avenirer/CodeIgniter-MY_Model#181]
With table having POINT type column (populated via mysql function POINT(lat,lng)
using $this->table_model->get($id); return FALSE;
Query output is ok (SELECT * FROM ...) but result empty.

Running CI method $this->db->where(...)->get(table)->row() return the row.
Looking at the returned row, looks like "POINT column" has BINARY format that doesnt please to My_model. Same if using GEOMETRY or POINT.

`SELECT *
FROM `test`
stdClass Object
(
    [id] => 1
    [coordinates] => )@������@
)
`

**Comment by avenirer** [comment]
Hello.

If you use the model without MY_Model (I mean here, by extending CI_Model and not MY_Model), does it show your data?

**Comment by stefanKBL** [comment]
Hello. 
Yes it shows, the result is what i posted after the select query.
`stdClass Object ( [id] => 1 [coordinates] => ���������������)@�������@ )`
Not really usefull as the coordinates field is only used by MySQL, so I can filtered it with a field declaration in my MY_MODEL request. I am just trying to understand why; Non-blocking problem.
