### ISSUE TITLE
many-to-many relation articles and users not working

### ISSUE THREAD

**Issue by shinokada** [avenirer/CodeIgniter-MY_Model#183]
In the Article_model which is in the download files, it has `has_many_pivot`,

    $this->has_many_pivot['authors'] = array(
            'foreign_model'=>'User_model',
            'pivot_table'=>'articles_users',
            'local_key'=>'id',
            'pivot_local_key'=>'article_id',
            'pivot_foreign_key'=>'user_id',
            'foreign_key'=>'id'
            );

For the reverse relation, I added `has_many_pivot` in the User_model.

    $this->has_many_pivot['articles'] = array(
            'foreign_model'=>'Article_model',
            'pivot_table'=>'articles_users',
            'local_key'=>'id',
            'pivot_local_key'=>'user_id',
            'pivot_foreign_key'=>'article_id',
            'foreign_key'=>'id'
            );

And this one in Test.php

    $data['users_with_count_many_articles'] = $this->user_model->with_articles('fields:*count*')->get_all();

And view is this one.

     <?php print_r($users_with_count_many_articles);?>

However this gives an error in Test.php

> Error Number: 1064
> 
> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') as counted_rows, `articles`.`id` FROM `articles` LEFT JOIN `articles_users` ON' at line 1
> 
> SELECT `articles`.`id`, `articles_users`.`user_id`, COUNT(`articles`*) as counted_rows, `articles`.`id` FROM `articles` LEFT JOIN `articles_users` ON `articles`.`id` = `articles_users`.`article_id` LEFT JOIN `users` ON `articles_users`.`user_id` = `users`.`id` WHERE `articles_users`.`user_id` IN('1', '2', '3', '4', '5')
> 
> Filename: core/MY_Model.php
> 
> Line Number: 1235

What am I doing wrong?

**Comment by avenirer** [comment]
Thank you for reporting that. Try now.

**Comment by shinokada** [comment]
Thanks for a quick reply.

I get this error now.


> Error Number: 1064
> 
> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*) as counted_rows, `articles`.`id` FROM `articles` LEFT JOIN `articles_users` O' at line 1
> 
> SELECT `articles`.`id`, `articles_users`.`user_id`, COUNT(`articles`.*) as counted_rows, `articles`.`id` FROM `articles` LEFT JOIN `articles_users` ON `articles`.`id` = `articles_users`.`article_id` LEFT JOIN `users` ON `articles_users`.`user_id` = `users`.`id` WHERE `articles_users`.`user_id` IN('1', '2', '3', '4', '5')
> 
> Filename: core/MY_Model.php
>

**Comment by avenirer** [comment]
how about now?...

**Comment by shinokada** [comment]
Now I get this.

> Error Number: 1140
> 
> In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'ci312.articles.id'; this is incompatible with sql_mode=only_full_group_by
> 
> SELECT `articles`.`id`, `articles_users`.`user_id`, COUNT(`articles`.`id`) as counted_rows, `articles`.`id` FROM `articles` LEFT JOIN `articles_users` ON `articles`.`id` = `articles_users`.`article_id` LEFT JOIN `users` ON `articles_users`.`user_id` = `users`.`id` WHERE `articles_users`.`user_id` IN('1', '2', '3', '4', '5')
> 
> Filename: core/MY_Model.php

**Comment by shinokada** [comment]
It doesn't show all articles. User1 should have 5 articles and others also have some as shown in the image below.

```
Array
(
    [0] => Array
        (
            [id] => 1
            [username] => user1
            [email] => user1@user.com
            [password] => mypass
            ...
            [deleted_by] => 
            [articles] => Array
                (
                    [1] => stdClass Object
                        (
                            [id] => 1
                            [title] => First article title
                        )

                )

        )

    [1] => Array
        (
            [id] => 2
            [username] => user2
            [email] => user2@user.com
            [password] => nopass
            ...
            [deleted_by] => 
        )

    [2] => Array
        (
            [id] => 3
            [username] => avenirer
            [email] => user3@user.com
            [password] => nopass
            ...
            [deleted_by] => 
        )

    [3] => Array
        (
            [id] => 4
            [username] => administrator
            [email] => user4@user.com
            [password] => mypass
            ...
            [deleted_by] => 
        )

    [4] => Array
        (
            [id] => 5
            [username] => user5
            [email] => user5@user.com
            [password] => nopass
            ...
            [deleted_by] => 
        )

)
```

![screen shot 2016-11-25 at 7 19 24 am](https://cloud.githubusercontent.com/assets/147320/20610637/9d7f6be8-b2df-11e6-9cfe-255b64693ca6.png)

**Comment by avenirer** [comment]
Didn't you want to count the rows?

**Comment by shinokada** [comment]
Actually I want to pull all articles by each user.

**Comment by shinokada** [comment]
Actually I wanted tags instead of users, which has many-to-many relations. So in this case let's say that every article has several authors in order to use many-to-many relations. So I want to find all author/uses for articles.

**Comment by avenirer** [comment]
I still do not understand what you want. What are tags? If you want to find all authors for articles, maybe you should query the articles and not the authors. I will close this issue, as it evolved to something else...

**Comment by shinokada** [comment]
Ok, it is solved.

I just need to take out count. And it shows all. Thank you for your help.

        $data['users_with_count_many_articles'] = $this->user_model->with_articles()->get_all();

```
 Array
(
    [0] => Array
        (
            [id] => 1
            [username] => user1
            [email] => user1@user.com
            [password] => mypass
            ....
            [articles] => Array
                (
                    [1] => stdClass Object
                        (
                            [id] => 1
                            [title] => First article title
                        )

                    [2] => stdClass Object
                        (
                            [id] => 2
                            [title] => Another article title
                        )

                    [3] => stdClass Object
                        (
                            [id] => 3
                            [title] => One more article title
                        )

                    [5] => stdClass Object
                        (
                            [id] => 5
                            [title] => How about this article title
                        )

                    [15] => stdClass Object
                        (
                            [id] => 15
                            [title] => 10 How about this article title
                        )

                )

        )

    [1] => Array
        (
            [id] => 2
            [username] => user2
            [email] => user2@user.com
            [password] => nopass
            .....
            [articles] => Array
                (
                    [7] => stdClass Object
                        (
                            [id] => 7
                            [title] => Two article title
                        )

                    [8] => stdClass Object
                        (
                            [id] => 8
                            [title] => Three article title
                        )

                    [13] => stdClass Object
                        (
                            [id] => 13
                            [title] => 8 How about this article title
                        )

                    [14] => stdClass Object
                        (
                            [id] => 14
                            [title] => 9 How about this article title
                        )

                    [1] => stdClass Object
                        (
                            [id] => 1
                            [title] => First article title
                        )

                )

        )
    ....
}
```
