### ISSUE TITLE
What is the best way to insert and update articles_users pivot table?

### ISSUE THREAD

**Issue by shinokada** [avenirer/CodeIgniter-MY_Model#184]
In your download, Article_model and User_model has many-to-many relations and they have a pivot table called `articles_users`.

I am wondering what is the best way to inert and update articles_users table.

Do I need to create another model called Atricles_users_model? Or any method to sync the table? Or is there better way to do it?

Thanks.

**Comment by avenirer** [comment]
I wouldn't create a new model for a pivot table. Don't add complexity when there is no need for complexity.

**Comment by shinokada** [comment]
So what do you suggest? Does MY_Model have function for this purpose?

**Comment by dgvirtual** [comment]
The process in real life would usually be this: you write an article to the database; on completion of the operation, you would get an article ID and you would perhaps have the user ID stored in a session variable. So you would run another insert operation on articles_users table to insert a new record with these two variables. 

So I also wonder, how to do it efficiently. One way would be to have an Articles_users model. Another way - to have a function in your Articles model with simple query builder commands for this operation, something like:

`function insert_articles_authors($user_id,$article_id)
{
    $data = array(
        'article_id' => $article_id,
        'user_id' => $user_id
    );
    return $this->db->insert('articles_users', $data);
}`

Is it what @avenirer had in mind?
