### ISSUE TITLE
All outputs are string in var_dump 

### ISSUE THREAD

**Issue by shinokada** [avenirer/CodeIgniter-MY_Model#185]
As you can see in the image below, all outputs are string. For example all ids should be integer.

How can I fix it?

![screen shot 2016-11-30 at 7 29 52 am](https://cloud.githubusercontent.com/assets/147320/20731721/d98f8260-b6ce-11e6-946f-d9febae681fc.png)

**Comment by Tpojka** [comment]
Check [this](https://www.sitepoint.com/community/t/var-dump-returns-string-for-integer/71310/16) (now old) article.

**Comment by shinokada** [comment]
Thanks Tpojka.

I didn't know that MySQL returns data with string. Oh dear.
