### ISSUE TITLE
is there any possible way to use "with_*" function to get data from third/fourth level table

### ISSUE THREAD

**Issue by mdn522** [avenirer/CodeIgniter-MY_Model#186]
for example: i have 4 tables

Main Table: "**users**"
(int) id
(varchar) username
(int) setting_group_id

Connector Table: "**setting_groups**"
(int) id

Mapping Table: "**settings_map**"
(int) setting_group_id
(int) setting_id

Settings Table: "**settings**"
(int) id
(varchar) name
(text) value

Note: Users table is a example. there will be many table related to settings table with a "**setting_group_id**" column

now my question is how can i get all settings with "with_*" function.. all i know that i can get row from "setting_groups" table. but i actually want to get all settings with "with_*" function

**Comment by salain** [comment]
Yes.
The manual talks about it
[here](https://github.com/avenirer/CodeIgniter-MY_Model#retrieve-data-from-nested-relationships-or-should-we-say-retrieve-nested-relationships-data)

**Comment by yahyaerturan** [comment]
This is a mind-breaking Model.. Changed my way of working in CI. Thank you. About fourth table I have question: 

I have an hierarchy like:

    Countries > Citites > Counties > Area > Neighborhood

I made it from single country to area, thanks to great manual. Now I am also trying to add neighborhood. ( I know it is not logical in production but just trying to understand my limits )

Relations are set properly. If I comment `Line 11` it works without neighborhood.

```php
1  $data = $this->country_model
2     ->with_cities(
3         array(
4             'fields'=>'name,phone_code',
5             'with'=>array(
6                 'relation'=>'counties',
7                 'fields'=>'name',
8                 'with' => array(
9                     'relation'=>'area',
10                    'fields'=>'name',
11                    'with' => array('neighborhood', 'fields'=>'zip_code')
12                )
13            )
14        )
15    )
16    ->get(212);
```

If I uncomment `Line 11` it gives the following error:

    ErrorException [ Warning ]: array_shift() expects parameter 1 to be array, string given
    APPPATH/core/MY_Model.php [ 1227 ]

Just curious on if I am doing something wrong or nested relation is only available up to 3.

Thanks for the great work again.

**Comment by emrahoruc** [comment]
You missed the index of array.
Try, 
  'with' => array('relation' => 'neighborhood', 'fields'=>'zip_code')

**Comment by salain** [comment]
@zilzurna is right.
But it turn out to be a bug. 
Pr should be merge soon

**Comment by yahyaerturan** [comment]
@zilzurna Of course, I have missed. Works fine now. Thanks. @salain thanks for patch.
