### ISSUE TITLE
Insert method returns false when ID not named id

### ISSUE THREAD

**Issue by vlatkoIT** [avenirer/CodeIgniter-MY_Model#187]
Hi guys,
I tried to find the same problem that i have got to see for my database, but I guess I'm the first. Correct me if I'm wrong.  After I changed the name of one of my **table's ID** from **id** to **post_id**, every time I would insert something I was getting **false**, as if something was wrong during the insertion. The column was set as primary key both in the model and in the database table. The field was **VARCHAR 50**, which I think might be one of the reasons for this issue. Please see the model settings below

```
public $table = 'posts';
    public $primary_key = 'post_id';
//  public $fillable = array();
    public $protected = array('created_at', 'updated_at');
    public $delete_cache_on_save = TRUE;

    public function __construct()
    {
        $this->timestamps = TRUE;
        $this->soft_deletes = FALSE;
        $this->return_as = 'array';

        $this->cache_driver = 'file';
        $this->cache_prefix = 'some';
        parent::__construct();
    }

```
Please let me know if someone else has come up with this issue, or maybe I'm doing something wrong. Hopefully you'll be able to replicate this or give me some sort of fix for it.
Regards

**Comment by avenirer** [comment]
The CI query builder assumes that it should return the primary key which is the key that is automatically given by the mysql database (from autoincrement) on an insert. So the primary key can not be a varchar, but an unsigned int. Hence, the error...

**Comment by vlatkoIT** [comment]
I see, at least it's good that I noticed this after short while. Actually I can add additional id (auto-increment int), so that I don't get insert false flag. Thanks for the prompt reply
