### ISSUE TITLE
adding brackets for multiple "OR" statements

### ISSUE THREAD

**Issue by minivetsystem** [avenirer/CodeIgniter-MY_Model#189]
$this->where(array('username'=>$params['identity'], 'email'=>$params['identity']), 'like', $params['identity'], TRUE);
$this->where('activated', 1);

Above two lines producing below:
**SELECT * FROM `users` WHERE `username` LIKE '%sam%' ESCAPE '!' OR `email` LIKE '%sam%' ESCAPE '!' AND `users`.`activated` = 1**

NO BRACKETS FOR MULTIPLE "OR" CONDITIONS

please help me how can it produce like below:
**SELECT * FROM `users` WHERE (`username` LIKE '%sam%' ESCAPE '!' OR `email` LIKE '%sam%' ESCAPE '!') AND `users`.`activated` = 1**

Thanks

**Comment by salain** [comment]
Hi,
This is the normal behaviour of CI Query builder. 
But you can use group_start and group_end methods to open/close parentheses to group where clause.
Look at CodeIngiter user guide.
However, these methods are not define in MY_Model. You have 2 ways you  can fix that.
First option is describe in issue #74 
or call the method directly on the db object:

```php
$this->db->group_start();
            $this->where('foo','>',1)->where('bar','>',10,TRUE)
$this->db->group_end();
$records = $this->where('foobar','=','something')->get_all();
```

**Comment by minivetsystem** [comment]
i found the solution

$this->where("(`users`.`username` LIKE '%".$params['identity']."%' ESCAPE '!' OR `users`.`email` LIKE '%".$params['identity']."%' ESCAPE '!')", NULL, NULL, FALSE, FALSE, TRUE);

6th parameter would be "TRUE' for a custom string

**Comment by avenirer** [comment]
Congratulations! You are on your path to a great developer :)
