### ISSUE TITLE
Your class is A-, it could be A+ if

### ISSUE THREAD

**Issue by Ihabafia** [avenirer/CodeIgniter-MY_Model#19]
Hi there,

I just saw your class and I think it's the perfect MY_Model class for codeigniter, the only thing I think it's missing is that if you can add the validation in the class like the one for (Jenssegers)
https://github.com/jenssegers/codeigniter-my-model
It will be optimum and it will be the real perfect class.

I think merging it with that class shouldn't be a big issue for a great developer like you.

Thank you, and keep up the good work.

**Comment by avenirer** [comment]
Thank you for your input. Will do my best. :)

**Comment by Ihabafia** [comment]
I will try to do it myself, and I can pass it to you. :)

**Comment by avenirer** [comment]
@Ihabafia Could you give a try to this?

**Comment by Ihabafia** [comment]
I saw this, it's a good start, but then you need to make it more general for insert and update, not for insert only.

Thank you so much for your effort.

**Comment by avenirer** [comment]
I usually make changes and wait for input regarding the changes made. If I have positive response I keep adding. This is the way I work :)
