### ISSUE TITLE
Basic SELECT query

### ISSUE THREAD

**Issue by fresh83** [avenirer/CodeIgniter-MY_Model#192]
Just looking for a  SELECT first_name,last_name WHERE fb_uid='$fb_uid'  query, on the surface seems to not exist.

**Comment by emrahoruc** [comment]
$this->Users_model->fields('first_name, last_name')->get(['fb_id' => $fb_id]);
is that?

**Comment by avenirer** [comment]
$this->users_model->fields('first_name, last_name')->where(array('fb_id'=>$fb_id))->get();
