### ISSUE TITLE
Has many pivot not working correctly?

### ISSUE THREAD

**Issue by ryan1978** [avenirer/CodeIgniter-MY_Model#193]
I've got the following tables:
campaigns (primary key: id)
products (primary key: product_id)
campaigns_products (foreign keys: campaign_id, product_id)

Each campaign can have many products hence the pivot table. I set the association up in the campaign model as such:
$this->has_many_pivot['products'] = array(
			'foreign_model' => 'Product_model',
			'pivot_table' => 'campaigns_products',
			'local_key' => 'id',
			'pivot_local_key' => 'campaign_id',
			'pivot_foreign_key' => 'product_id',
			'foreign_key' => 'product_id',
			'get_relate' => TRUE
		);

This works to a degree but generates the following php error:
  A PHP Error was encountered
  Severity: Notice
  Message: Undefined index: id
  Filename: core/MY_Model.php
  Line Number: 1254
  Backtrace:
  File: /var/www/marketing.isitraining.com/application/core/MY_Model.php
  Line: 1254
  Function: _error_handler
  File: /var/www/marketing.isitraining.com/application/core/MY_Model.php
  Line: 294
  Function: join_temporary_results
  File: /var/www/marketing.isitraining.com/application/core/MY_Model.php
  Line: 965
  Function: _prep_after_read
  File: /var/www/marketing.isitraining.com/application/controllers/Reports.php
  Line: 40
  Function: get_all
  File: /var/www/marketing.isitraining.com/htdocs/index.php
  Line: 320
  Function: require_once

Which is caused by this line in MY_Model.php:
$subs[$the_local_key][$the_foreign_key] = $this->{$relation['foreign_model']}->where($local_key, $result[$local_key])->get();

The errors go away if I change the above line to read:
$subs[$the_local_key][$the_foreign_key] = $this->{$relation['foreign_model']}->where($foreign_key, $result[$foreign_key])->get();

So have I set up my model has_many_pivot up incorrectly somehow or is the code change I made that resolves it for me an actual bug/fix?

**Comment by avenirer** [comment]
To be honest, I haven't met this error on my tests, and I do have a test for this pivot table thing... But also, to be equally honest, I never had a different primary key name in tables (as I see, you have "product_id" as primary key in your products table). Hence that is why I haven't had the error (as any table in my tests has "id" as primary key). Thank you for noticing the bug.
