### ISSUE TITLE
Errors on using hooks with as_dropdown

### ISSUE THREAD

**Issue by dgvirtual** [avenirer/CodeIgniter-MY_Model#194]
I think I have found some bug, but I cannot troubleshoot it.

if I add a function to the very end of My_Model.php: 

<pre>
    public function add_retriever($data)
    {
	    $data['retrieved_by'] = 'Nickolas Cage';
	    return $data;
    }
</pre>

and also add a call to hook in User_model.php at the end of the constructor: 

<pre>
			$this->after_get[]='add_retriever';
</pre>

I do get a field added to the query results (I am using your default Test.php controller to play around), but I also get a few errors on page: 

<pre>
A PHP Error was encountered
Severity: Warning
Message: Illegal string offset 'id'
Filename: core/MY_Model.php
Line Number: 300
Backtrace:
File: /var/www/mymodel/application/core/MY_Model.php
Line: 300
Function: _error_handler
File: /var/www/mymodel/application/core/MY_Model.php
Line: 965
Function: _prep_after_read
File: /var/www/mymodel/application/controllers/Test.php
Line: 47
Function: get_all
File: /var/www/mymodel/index.php
Line: 315
Function: require_once
</pre>
<pre>
A PHP Error was encountered
Severity: Warning
Message: Illegal string offset 'username'
Filename: core/MY_Model.php
Line Number: 300
Backtrace:
File: /var/www/mymodel/application/core/MY_Model.php
Line: 300
Function: _error_handler
File: /var/www/mymodel/application/core/MY_Model.php
Line: 965
Function: _prep_after_read
File: /var/www/mymodel/application/controllers/Test.php
Line: 47
Function: get_all
File: /var/www/mymodel/index.php
Line: 315
Function: require_once
</pre>

These seem to be only related to the dropdown call in the controller: 

<pre>
$this->user_model->as_dropdown('username')->get_all()
</pre>

If I remove this call from the controller, the errors are not shown.

**Comment by avenirer** [comment]
In the add_retriever() method you are assuming to retrieve a single element array. Because of that the array gets an element with a different structure than the one it is used to. You should first check if the $data has only one element or more elements (sizeof()). If it has more than one element, you should iterate through $data and add the "retrieved_by" key to each element of that array.

**Comment by avenirer** [comment]
...Also, you can and should add the function to the model that is using it, not to the MY_Model.

**Comment by dgvirtual** [comment]
OK, thank you for detailed explanation, and sorry for the trouble. Missed this time :)
