### ISSUE TITLE
Polymorphic Relations

### ISSUE THREAD

**Issue by emrahoruc** [avenirer/CodeIgniter-MY_Model#195]
Any plan for Polymorphic relations? Like; https://laravel.com/docs/5.3/eloquent-relationships#polymorphic-relations

**Comment by salain** [comment]
Hi,
You can do it by adding a where clause to the with_* method call.
Here is how I have done it with a table called "notes" that I use to save notes about many records in a few other tables (logs for this example): 
In the "notes" table I have 2 fields belong_id (foreign_key for the relation) and belong_to (model/table to whom the id belongs to).

```php
// relation in the log_model
$this->has_one['note'] = array(
            'foreign_model'=>'note_model',
            'foreign_table'=>'notes',
            'foreign_key'=>'belong_id',
            'local_key'=>'id'
        );

// get records with notes that belong to logs
$records = $this->with_status('fields:name')
            ->with_user_profile('fields:first_name,last_name')
            ->with_truck('fields: driver')
            ->with_note('fields:note','non_exclusive_where:belong_to="logs"') // <- where for logs only 
            ->fields($fld_select)->where('id',$id)
            ->get_all();

```
This is one way of doing it. 
You can also put the where clause in a property of the model to save having to write it
I cannot  find it but I think I also used this with a before_get observer. I will update if/when I find it.
I had started to build it in MY_Model, but I could not get it to work properly (time constraint) and could not find a decent way to make the belong_to  field flexible, so I gave up on it as this works for me.

I hope it helps.

**Comment by emrahoruc** [comment]
@salain 

I did not notice that non_exclusive_where condition. Also second way seems senseful too. I am going to try any of. Thank you very much. 👍
