### ISSUE TITLE
Error while doing soft delete

### ISSUE THREAD

**Issue by asakapab0i** [avenirer/CodeIgniter-MY_Model#196]
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'THEN '1' ELSE `applicant_attachment_id` END, `deleted_at` = CASE WHEN `applican' at line 2

UPDATE `applicant_attachments` SET `applicant_attachment_id` = CASE WHEN `applicant_attachment_id` = THEN '1' ELSE `applicant_attachment_id` END, `deleted_at` = CASE WHEN `applicant_attachment_id` = THEN '2017-01-20 04:59:16' ELSE `deleted_at` END WHERE `applicant_attachments`.`applicant_attachment_id` = 1 AND `applicant_attachment_id` IN()

The line is somewhere in 647

https://github.com/avenirer/CodeIgniter-MY_Model/blob/version-3.0/core/MY_Model.php#L773

I'm not sure if its because of codeigniter version? I'm using CI 3. 

I shoulnt have fix it and pull but I'm too busy right now meeting the deadlines. 

Let me know!

**Comment by salain** [comment]
Hi,
What version of CI are you using? 
This looks like the issue is with CI3.1.2 that affected all batch update. 
Upgrading to 3.1.3 does not take long and fix this issue.

**Comment by asakapab0i** [comment]
Just found out the issue. I did a quick fix but I will update it soon thanks for the reply!

`$index = '`' . $index . '`';`
