### ISSUE TITLE
get all column name from table

### ISSUE THREAD

**Issue by bagoesz21** [avenirer/CodeIgniter-MY_Model#197]
On your code,

> public function _get_table_fields()
>     {
>         if(empty($this->table_fields))
>         {
>             $this->table_fields = $this->_database->list_fields($this->table);
>         }
>         return TRUE;
> }

please, make this method return as table field not **boolean**. i want to get all column name from table.

**Comment by salain** [comment]
Hi,
The method fills the class property $table_fields 
So, you can call the method then use $this->table_fields to get all columns name.
What are you trying to achieve?

**Comment by bagoesz21** [comment]
Hi @salain,
i try to implement my code ..

> $this->load->model("employee_model");
> var_dump($this->employee_model->table_fields);

nothing result, and this ..

> class Pelanggan extends MY_Controller {
> public function myfields(){
>     	return $this->$table_fields;
>     }
> }

nothing result, where i must use **$this->table_fields** to get all columns name ??

**Comment by bagoesz21** [comment]
i solve this problem, make this method in controller ..

public function list_coloumn_table(){
        return $this->db->list_fields($this->table);
}

**Comment by salain** [comment]
You need to fill the array before.
If you add this method in your model is will work:
```php
public function list_column_table(){
   $this->_get_table_fields();  // fills the array if empty
   return $this->table_fields;
}

//use it in your controller or any where else
$this->load->model('model_name');
$var_name = $this->model_name->list_column_table();

```
