### ISSUE TITLE
soft delete error 

### ISSUE THREAD

**Issue by MohammedAli1991** [avenirer/CodeIgniter-MY_Model#198]
class model user
$this->table = 'user';
$this->primary_key = 'id';
$this->timestamps_format = 'Y-m-d H:i:s';
$this->timestamps = true;
$this->soft_deletes = true;

class controller
$status = $this->user_m->delete( $id);

error in query
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'THEN '8' ELSE id END, deleted_at = CASE WHEN id = THEN '2017-01-25 10:53' at line 2

UPDATE user SET id = CASE WHEN id = THEN '8' ELSE id END, deleted_at = CASE WHEN id = THEN '2017-01-25 10:53:59' ELSE deleted_at END WHERE user.id = '8' AND id IN()

**Comment by avenirer** [comment]
did you make sure you have a valid $id?

**Comment by MohammedAli1991** [comment]
yes it is 8 , it exists in query but in wrong place ,i think

**Comment by MohammedAli1991** [comment]
this var_dump before i call delete
..\api\User.php:834:int 8

**Comment by prsudh** [comment]
I am also seeing this same issue...

**Comment by ghost** [comment]
I am also seeing this same error...I just updated from CI 3.1.2 to 3.1.3 and the issue is fixed!

**Comment by avenirer** [comment]
It seems that the issue is CI related: https://forum.codeigniter.com/thread-66522.html?highlight=update_batch

**Comment by MohammedAli1991** [comment]
Thank you very much, it works
