### ISSUE TITLE
get_all + soft delete are not friends :(

### ISSUE THREAD

**Issue by orionstar** [avenirer/CodeIgniter-MY_Model#2]
The get_all() method shows the soft deleted rows too.

**Comment by avenirer** [comment]
Thank you for pointing this out. Correction made. :)

**Comment by orionstar** [comment]
Thanks, now it works! :)

**Comment by avenirer** [comment]
Thank you. Please tell me any problems you encounter or anything you want me to add to the MY_Model.

**Comment by orionstar** [comment]
I switched from Jamie's MY_Model to your's and I will use it in regular basis at work. (The main reason for it is the support of relations with pivot tables and because Jamie abandoned his project last year)
I will post a summary of my opinions to the thread what you created for this stuff in the CI forum in a few week.

**Comment by avenirer** [comment]
Hello @orionstar . Taking a closer look at the model I found out that there was still an error in there. You should load the MY_Model again. Sorry about that.
