### ISSUE TITLE
Does it take care of the N+1 problem

### ISSUE THREAD

**Issue by Ihabafia** [avenirer/CodeIgniter-MY_Model#20]
I am sorry, but this is not an issue or a bug, but a question.  Does MY_Model with relations take care of the N+1 problem.

Which means does it create 101 query to get the 100 record that have a one to many or many to many relations.

Thank you,

**Comment by ngangchill** [comment]
may be 2 query only like as laravel elqnt.

On 6/1/15, Ihabafia notifications@github.com wrote:

> I am sorry, but this is not an issue or a bug, but a question.  Does
> MY_Model with relations take care of the N+1 problem.
> 
> Which means does it create 101 query to get the 100 record that have a one
> to many or many to many relations.
> 
> Thank you,
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/avenirer/CodeIgniter-MY_Model/issues/20

## 

```
->Thnx .
              ©¿©  Förhäd Ähmëd
```

**Comment by avenirer** [comment]
Hello. It does one additional query for every relation requested. If you have a post with many comments it does two queries. If you have a post with multiple authors and many comments it does three queries.
