### ISSUE TITLE
unix time in created_at

### ISSUE THREAD

**Issue by lloricode** [avenirer/CodeIgniter-MY_Model#204]
hi! @avenirer, Is theres a way to save columns `created_at`,`updated_at`, and `deleted_at` as formats `unix` unit time? 

great day guys! :+1:

**Comment by salain** [comment]
set the timestamps_format property to 'timestamp'
$this->timestamps_format=='timestamp'

**Comment by lloricode** [comment]
ah, ok ok, a great thanks @salain
