### ISSUE TITLE
When models are in subdir

### ISSUE THREAD

**Issue by esteban-turnocheck** [avenirer/CodeIgniter-MY_Model#206]
Hi! I've found an issue and solved it. Wanted to show you so you can fix the code. I don't know how to handle it in github (maybe a pull request?, would yo be so kind to explain?).
The issue is that when a controller involved in a relationship is inside a subdir under the /models dir, it causes an error when setting relationships.
Example is as follows:

In usuarios_tank_model

> `

	public function __construct() {

		$this->has_one["profile"] = array("foreign_table" => "user_profiles", "foreign_model" => "v2/user_profile_model", "foreign_key" => "user_id", "local_key" => "id");

		parent::__construct();
	}`

This code gives an error when i do 

> `

	$usuario_tank = $this->ci->usuarios_tank_model->with_profile(array('fields'=>'perfil_id'))->get(array('email' => $email));
`

The error is undefined property Auth::$v2/usuarios_tank_model

If i DON'T set the foreign_table element of the array $has_one['profile'], then it works.

The problem seems to be here: 

> `

	if(array_key_exists('foreign_table',$relation))
                                {
                                    $foreign_table = $relation['foreign_table'];
                                }
                                else
                                {
                                    $model = $this->_parse_model_dir($foreign_model);
                                    $foreign_model = $model['foreign_model'];
                                    $model_dir = $model['model_dir'];
                                    $foreign_model_name = $model['foreign_model_name'];

                                    $this->load->model($model_dir . $foreign_model_name);
                                    $foreign_table = $this->{$foreign_model_name}->table;
                                }
`

Looks to be working ok when 

> `

                                $model = $this->_parse_model_dir($foreign_model);
                                $foreign_model = $model['foreign_model'];
                                $model_dir = $model['model_dir'];
                                $foreign_model_name = $model['foreign_model_name'];

                                if(array_key_exists('foreign_table',$relation))
                                {
                                    $foreign_table = $relation['foreign_table'];
                                }
                                else
                                {
                                    $this->load->model($model_dir . $foreign_model_name);
                                    $foreign_table = $this->{$foreign_model_name}->table;
                                }
`

That's MY_Model Line: 1371
The value of foreign_model_name doesn't get parsed when you set foreign table. So it breaks later because 

> `                        $this->_relationships[$key] = array('relation' => $option, 'relation_key' => $key, 'foreign_model' => strtolower($foreign_model), 'foreign_table' => $foreign_table, 'foreign_key' => $foreign_key, 'local_key' => $local_key);
`

And 'foreign_model' => strtolower($foreign_model) ---> foreign_model = "v2/usuarios_tank_model"

Is this a propper solution? Anywhere else to look for similar behaviour?

Thanks! 

Esteban.

**Comment by avenirer** [comment]
Hello @esteban-turnocheck . Can you please try again? Thank you.

**Comment by esteban-turnocheck** [comment]
Hi! Thanks for the answer and the quick fix!
Yes, it seems to be working now.
Just wondering if 
`                                $this->load->model($model_dir . $foreign_model, $foreign_model_name);
`
on line 1375, doesn't really belong to line 1382, inside the else block, so the model doesn't get loaded unless it's needed to figure out the foreign table name. Only for a slight optimization.
Thanks again!

**Comment by avenirer** [comment]
@esteban-turnocheck in the end you would still load the model, because the with_*() method is called, so I don't think this will affect performance. Or am I wrong?

**Comment by esteban-turnocheck** [comment]
I might be a little confused about the flow here. 
I believe you might be correct, though, since the with_*() method only makes sense if chain is followed by some get() method, right? (like in `model_name->with_xxxx()->get()`. If it wouldn't be, then you would be loading the model twice, because the calls to with_*() and to get() could be made at very different places in the code (once you'd end up loading the model in `$y=model_name->with_xxxx()`, which is the point where it's not necessary if you set the foreign_table, and another in `$y->get()`).
But, again, even when the possibility exists as per the code (the avobe examples, correct me if i'm wrong, are syntactically right) , it don't see it makes any sense to use it that way in any circumstance.
So you are right. In all apparently possible scenarios, you end up loading the model anyways and performance doesn't suffer.
If this is correct, this issue seems to end here! Right?

**Comment by avenirer** [comment]
Well... yo made me take another look at the model. Just to be safe I only loaded the model to find out the table name. But then found other problems which needed correcting. Thank you, @esteban-turnocheck . I really appreciate your (and any user's) input.

**Comment by esteban-turnocheck** [comment]
Glad to help, it only retributes you some of the time you help me save with this great base model. I was using jamie's before, but the lack of pivot table relationships put me on the track to find yours. Thanks!
Will you let me know when you find those problems you mention and there is a new version to download? Or is it already done?

**Comment by avenirer** [comment]
already done. please do try it again.

**Comment by salain** [comment]
@avenirer 
I cannot test it until tomorrow morning. Looking at the code it looks good. 
I will post an update if I find any issue.

**Comment by esteban-turnocheck** [comment]
@avenirer Sorry, i was away in a phone call. Resuming now. I'll test it and let you know. Thanks again!

**Comment by esteban-turnocheck** [comment]
Seems ok from where i can test. It works! :)
