### ISSUE TITLE
I can do in qb in CI, but in core MY_Model, how?

### ISSUE THREAD

**Issue by lloricode** [avenirer/CodeIgniter-MY_Model#209]
sir @avenirer ? I want to generate a long group in query,

```
SELECT *
FROM `subject_offers`
WHERE   (
   (
`subject_offer_start` <= '06:00'
AND `subject_offer_start` <= '06:30'
AND `subject_offer_end` > '06:00'
AND `subject_offer_end` <= '06:30'
  )
OR    (
`subject_offer_start` >= '06:00'
AND `subject_offer_start` < '06:30'
AND `subject_offer_end` >= '06:00'
AND `subject_offer_end` >= '06:30'
  )
OR    (
`subject_offer_start` <= '06:00'
AND `subject_offer_start` < '06:30'
AND `subject_offer_end` > '06:00'
AND `subject_offer_end` >= '06:30'
  )
OR    (
`subject_offer_start` >= '06:00'
AND `subject_offer_start` < '06:30'
AND `subject_offer_end` > '06:00'
AND `subject_offer_end` <= '06:30'
  )
 )
AND   (
`user_id` = '1'
OR `room_id` = '1'
OR `subject_id` = '1'
 )
AND   (
`subject_offer_monday` = 1
OR `subject_offer_wednesday` = 1
OR `subject_offer_thursday` = 1
 )
```

but how dous it in core MY_Model?
thanks you sir, 
[this is my source code](https://github.com/lloricode/ci-capstone/blob/developing/application/libraries/Subject_offer.php#L162)

**Comment by lloricode** [comment]
the only available is `group_by`  what if i will use `or_group_by`?

**Comment by salain** [comment]
Have a look at issue #74

**Comment by lloricode** [comment]
@salain thanks , i will do this now

**Comment by lloricode** [comment]
@salain , you suggest is good, but, why did you not merge your idea?

**Comment by salain** [comment]
Laziness and/or keep forgetting it. 
Also I am not very good with github.
Will try to remember when I get back to my PC.

**Comment by avenirer** [comment]
This is great. Laziness is our greatest asset. :)

**Comment by lloricode** [comment]
owh? hihi,  your damn right guys :D

**Comment by lloricode** [comment]
so  i will modify the core MY_Model?, hmmm i like to PR this, but its not my idea, btw way thanks @salain  @avenirer  :100:
