### ISSUE TITLE
There is a minor error in Pivot query or I didn't get it correct

### ISSUE THREAD

**Issue by Ihabafia** [avenirer/CodeIgniter-MY_Model#21]
Hi, I am using a pivot relations, here is my code:

Group_m.php:

class Group_m extends MY_Model {

```
public $table = 'ion_groups'; // you MUST mention the table name
public $primary_key = 'id'; // you MUST mention the primary key
public $fillable = array(); // If you want, you can set an array with the fields that can be filled by insert/update
public $protected = array(); // ...Or you can set an array with the fields that cannot be filled by insert/update

public function __construct()
{
    $this->timestamps = FALSE;
    $this->soft_deletes = FALSE;
    $this->return_as = 'object';
    $this->has_many_pivot['roles'] = ['role_m', 'id', 'id'];
    parent::__construct();
}

public function get_roles($group_id=null)
{
    $result = $this->with_roles('fields:role_name')->get_all($group_id);
    return $result;
}
```

}

Role_m.php:

class Role_m extends MY_Model {

```
public $table = 'roles'; // you MUST mention the table name
public $primary_key = 'id'; // you MUST mention the primary key
public $fillable = array(); // If you want, you can set an array with the fields that can be filled by insert/update
public $protected = array(); // ...Or you can set an array with the fields that cannot be filled by insert/update

public function __construct()
{
    $this->timestamps = FALSE;
    $this->soft_deletes = FALSE;
    $this->return_as = 'object';
    $this->has_many_pivot['groups'] = ['group_m', 'id', 'id'];
    parent::__construct();
```

}

and here is the query result:

SELECT `roles`.'role_name` FROM `roles` INNER JOIN `ion_groups_roles` ON `roles`.`id` = `ion_groups_roles`.`role_id` INNER JOIN `ion_groups` ON `ion_groups_roles`.`ion_group_id` = `ion_groups`.`id` WHERE `ion_groups`.`id` IN('1')

as  you can see there is a extra \ in the query:
SELECT `roles`.'role_name` FROM

Am I doing something wrong?

Thank you,

**Comment by Ihabafia** [comment]
the \ is not showing it's after 'role_name I am getting \' instead of '

**Comment by avenirer** [comment]
Thank you for reporting, @Ihabafia . Retry now with the modified MY_Model.

**Comment by Ihabafia** [comment]
Thank you so much.

Please give me some time to test it.

By the way do you maintain the Insert in Pivot table the same way you maintain the get from table.

Thank you,

**Comment by avenirer** [comment]
I am planing to add the relations to the delete and update methods too, if that was your question. Sure hope I will find the time :)

**Comment by Ihabafia** [comment]
And how about insert with relation is it made.  And if yes could you put
some examples for one to one and one to many and many to many.

Great work and thank you for your effort.

**Comment by avenirer** [comment]
Sorry about that... I also meant the insert too. Until now, relations were only done for the "read" part.

**Comment by Ihabafia** [comment]
:+1:
