### ISSUE TITLE
Relationship Question

### ISSUE THREAD

**Issue by pyromanci** [avenirer/CodeIgniter-MY_Model#219]
Until a recent project I've never really tired to set any external table relations in any system. I've always handled them manually. I just want to confirm I under stand how the MY_Model relationships work.

If you look at this picture
http://image.prntscr.com/image/2a02d5f98335409eb697052cdd14ecde.png

You can see a client_id field in the projects table, which relates back to a single record in a clients table.
Then the id field of the projects tables could related to many rows in the project_tasks by the field "project_id"

So in the model constructor, I would call these out by doing this correct?

```
$this->has_one['client'] = array('foreign_model'=>'Clients_model','foreign_table'=>'clients','foreign_key'=>'id','local_key'=>'client_id');
$this->has_many['tasks'] = array('foreign_model'=>'Tasks_model','foreign_table'=>'project_tasks','foreign_key'=>'project_id','local_key'=>'id');
```

**Comment by salain** [comment]
Hi it looks right, however there I'd nothing like getting your hands dirty and do some test to get use to it.

**Comment by pyromanci** [comment]
After playing with it was. it took me a bit of reading between the lines, but i learned I could something like: 
```
		$this->load->model('clients');
		$this->clients_model->with_projectsclients(
			array(
				'where' => array('deleted'=>'0'),
				'fields'=>'id,project_name',
				'with' => array(
					array(
						'relation'=>'timesprojects',
						'fields'=>'*count*',
						'where' => array('invoiced'=>'0', 'deleted'=>'0'),
					),
					array(
						'relation'=>'tasksprojects',
						'fields'=>'id,short_description',
						'where' => array('deleted'=>'0'),
						'with' => array(
								'relation'=>'tasktimestasks',
								'fields'=>'*count*',
								'where' => array('invoiced'=>'0', 'deleted'=>'0'),
						)
					),
				),
			)
		)->as_array()->get_all();
```

While i know this could be hazardous because of the amount of data, it was interesting to see how far i could take it.

**Comment by avenirer** [comment]
Wow... this is deep... :)
