### ISSUE TITLE
Strange error:  Unable to locate the specified class: Session.php while loading two related model  in a controller

### ISSUE THREAD

**Issue by ngangchill** [avenirer/CodeIgniter-MY_Model#22]
Blog Model: 

```
  class Blog_m extends MY_Model {

     public $table = 'blog_posts'; 
     public $primary_key = 'postID';
     public $protected = array('postID'); 

   public function __construct() {
       $this->timestamps = TRUE;
       $this->soft_deletes = TRUE;
      $this->has_one['cats'] = array('Bcats_m','catID','catID');
    $this->has_one['user'] = array('User_m','id','userID');
           parent::__construct();
   }

}
```

Category Model:

```
class Bcats_m extends MY_Model {

public $table = 'blog_cats';
public $primary_key = 'catID'; 
public $protected = array('catID'); 

public function __construct() {
       $this->has_many['blog'] = array('Blog_m','catID','catID');
        parent::__construct();
    }
```

Controller:

```
  function __construct() {
        parent::__construct();
        $this->load->model(array('blog_m','bcats_m''));   
       }
```

while loading two or more related model in a  controller it through error. 

error:   

```
   Unable to locate the specified class: Session.php
```

i checked it.error ocurs for loading two or more related model in a controller.

if load single model ( either Blog_m or Bcats_m), it works fine.

**Comment by ngangchill** [comment]
i checked it with some demo  model which are not related to each other. errors only occurs while loading related model.

**Comment by ngangchill** [comment]
$this->blog_m->with_user()->get_all();   also shows same error ...

$this->blog_m->get_all(); // works fine

**Comment by ngangchill** [comment]
sorry, it was my typing  mistake...everything is ok...

please remove this issue

**Comment by avenirer** [comment]
You really scared me there...

**Comment by ngangchill** [comment]
i was also scared too, my whole app was broken, but after searching hard i found my mistake...

and im really sorry for scarring you..
