### ISSUE TITLE
CONCAT whith blank spaces 

### ISSUE THREAD

**Issue by rodyoukai** [avenirer/CodeIgniter-MY_Model#224]
Hi, I am apply this little change in method fields (before sizeof):

        
                if (sizeof($exploded) < 1)
                        {
                            if($field != "(' ')")
                                $field = $this->table . '.' . $field;

                        }
                    }
             

I use this sentence:

$this->usuarios_model->fields("id, CONCAT(nombre,(' '),apellido_paterno, (' '),apellido_materno) AS nombre, email")

This permit use CONCAT whith blank spaces, it is not perfect but solve an issue for me...

Sorry my english is very limited...

**Comment by salain** [comment]
You should use CONCAT_WS , WS means with separator as the first argument. 
To prevent the fields method to mess up your fields when using MySQL functions is to include the table and use an array.
  
```php
$this->user_model->fields(array('id',
'CONCAT_WS(" ",table_name.nombre,table_name.apellido_paterno,table_name.apellido_materno) AS nombre','email'))->get...
```

**Comment by rodyoukai** [comment]
I first tried that, but I got:

execute command denied to user 'user'@'db' for routine 'usuarios.CONCAT_WS'

**Comment by salain** [comment]
Show your code

**Comment by rodyoukai** [comment]
I change sizeof en line 1520 MY_Model.php 

after:

if (sizeof($exploded) < 2)


Now:

if (sizeof($exploded) < 1)


And CONCAT_WS works perfect, Thanks Salain!!!

I eliminated  my modification in MY_Model.php, only chage sizeof...

**Comment by salain** [comment]
Welcome
