### ISSUE TITLE
Validating checkbox array

### ISSUE THREAD

**Issue by shinningweb** [avenirer/CodeIgniter-MY_Model#232]
`<input type="checkbox" name="specialization[]" value="Txtbk" />Textbooks<br />
                      <input type="checkbox" name="specialization[]" value="Strbks" />Story Books<br />
                      <input type="checkbox" name="specialization[]" value="Rlgbks" />Religious<br />
                      <input type="checkbox" name="specialization[]" value="Schbks" />Scholarly Books<br />
                      <input type="checkbox" name="specialization[]" value="Jnlbks" />Journal<br />`
                      
how can i pass a rule to ensure at least one checkbox is selected? in the model?

**Comment by emrahoruc** [comment]
The "required" is enough.

```php
$this->rules = [
    'insert' => [
		'type' => [
	        'field' => 'type',
	        'label' => 'Type',
	        'rules' => 'required|trim|in_list[textbooks,story-books,religious,scholarly-books,journal]',
	    ],
	],
	'update' => [
		'type' => [
	        'field' => 'type',
	        'label' => 'Type',
	        'rules' => 'required|trim|in_list[textbooks,story-books,religious,scholarly-books,journal]',
	    ],
    ]
];
```

**Comment by shinningweb** [comment]
How then do i implode the data and insert to the database after that? Can a callback be used for that? How exactly should it be done?

**Comment by lloricode** [comment]
@shinningweb what method do you used?  `..._model->from_form()->insert()` ? or `..._model->insert($array_data)` ?
 
by the way, you can use `<input type="radio"` to be not complicated the situation

if the reason you used checkbox to uncheck the data, use can add one
 `<input type="radio" value=""`  with no value, then you controller will validated it, if no value dont include it on insert, 

you can use `..._model->insert($array_data)` to manipulate data before insert rather than  `..._model->from_form()->insert()`

**Comment by emrahoruc** [comment]
If so, use the "Observers".

```php

class User_model extends MY_Model
{
	function __construct()
	{
		$this->before_create[] = '_setType';
                $this->before_update[] = '_setType';
		parent::__construct();
	}

	protected function _setType($data)
    	{
        	// .. do your stuff

        	return $data;
    	}
}


```

**Comment by shinningweb** [comment]
@zilzurna thanks for the assistance

` 'specialization' => array('field'=>'specialization[]',
                        'label'=>'Specialization',
                        'rules'=>'required'                      
                        ),`

and this is what i was looking at doing
`    protected function _setType()
    	{
        $areas = $this->input->post('specialization[]');
        $data = implode(",", $data);   

        	return $data;
    	}`

the form fields are
`<?php echo form_error('specialization[]'); ?>
                      
                      
                      <input type="checkbox" name="specialization[]" value="Txtbk" />Textbooks<br />
                      <input type="checkbox" name="specialization[]" value="Strbks" />Story Books<br />
                      <input type="checkbox" name="specialization[]" value="Rlgbks" />Religious<br />
                      <input type="checkbox" name="specialization[]" value="Schbks" />Scholarly Books<br />
                      <input type="checkbox" name="specialization[]" value="Jnlbks" />Journal<br />`

**Comment by shinningweb** [comment]
`<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
* 
*/
class Users_model extends MY_Model

{
    public $table = 'users'; // you MUST mention the table name
    public $primary_key = 'user_id'; // you MUST mention the primary key

public $fillable = array('pub_name','pub_tel','pub_mob','pub_address','pub_email','pub_web','specialization','password','pub_firm','pub_city'); // 
    
    public function __construct()
    {
        $this->before_create[] = '_setType';
        $this->before_update[] = '_setType';
       
        $this->return_as = 'array';
         parent::__construct();
    }
    
    protected function _setType()
    	{
        $areas = $this->input->post('specialization[]');
        $data = implode(",", $data);   

        	return $data;
    	}
    
    public $rules = array(
    
        'insert' => array(

            'pub_name' => array('field'=>'pub_name',
                        'label'=>'Name',
                        'rules'=>'trim|required|min_length[5]|max_length[80]'              
                        ),
            'pub_firm' => array('field'=>'pub_firm',
                        'label'=>'Company name',
                        'rules'=>'trim|required|min_length[5]|max_length[80]'  
                        ),
            'pub_city' => array('field'=>'pub_city',
                        'label'=>'City',
                        'rules'=>'trim|required|min_length[5]|max_length[80]'  
                        ),
            'pub_tel' => array('field'=>'pub_tel',
                        'label'=>'Telephone',
                        'rules'=>'trim|required|is_numeric'                      
                        ),
            'pub_mob' => array('field'=>'pub_mob',
                        'label'=>'Mobile Phone',
                        'rules'=>'trim|required|is_numeric'                      
                        ),
            'pub_address' => array('field'=>'pub_address',
                        'label'=>'Address',
                        'rules'=>'trim|min_length[5]|max_length[255]'                      
                        ),
            'pub_web' => array('field'=>'pub_web',
                        'label'=>'website',
                        'rules'=>'trim|max_length[50]'                      
                        ),
             'password' => array('field'=>'password',
                        'label'=>'password',
                        'rules'=>'required|md5'                      
                        ),
             'specialization' => array('field'=>'specialization[]',
                        'label'=>'Specialization',
                        'rules'=>'required'                      
                        ),
            'pub_email' => array(
                        'field'=>'pub_email',
                        'label'=>'Email',
                        'rules'=>'trim|valid_email|required',
                        'errors' => array ('required' => 'Username/ Email is required',
                                'trim' => 'Error message for rule trim for field email',
                                'valid_email' => 'Email should be valid')
                    )
              ),    
                
        'update' => array(
            
             'pub_name' => array('field'=>'pub_name',
                        'label'=>'Name',
                        'rules'=>'trim|required|min_length[5]|max_length[80]'              
                        ),
            'pub_firm' => array('field'=>'pub_firm',
                        'label'=>'Company name',
                        'rules'=>'trim|required|min_length[5]|max_length[80]'  
                        ),
            'pub_city' => array('field'=>'pub_city',
                        'label'=>'City',
                        'rules'=>'trim|required|min_length[5]|max_length[80]'  
                        ),
            'pub_tel' => array('field'=>'pub_tel',
                        'label'=>'Telephone',
                        'rules'=>'trim|required|is_numeric'                      
                        ),
            'pub_mob' => array('field'=>'pub_mob',
                        'label'=>'Mobile Phone',
                        'rules'=>'trim|required|is_numeric'                      
                        ),
            'pub_address' => array('field'=>'pub_address',
                        'label'=>'Address',
                        'rules'=>'trim|min_length[5]|max_length[255]'                      
                        ),
            'pub_web' => array('field'=>'pub_web',
                        'label'=>'website',
                        'rules'=>'trim|max_length[50]'                      
                        ),
            'specialization' => array('field'=>'specialization',
                        'label'=>'Specialization',
                        'rules'=>'required|callback_ds'                      
                        )
            )                    
    );
    
   
    
    
}
`

**Comment by shinningweb** [comment]
`<form enctype="multipart/form-data" method="post" action="<?php echo base_url();?>page/register">
          <h2>Your Personal Details</h2>
            
          <div class="content">
            <table class="form">
              <tbody>
                <tr>
                  <td><span class="required">*</span> Name:</td>
                    
                  <td> <?php echo form_error('pub_name'); ?> <input class="large-field" type="text" value="<?php echo ($rec['pub_name']); ?>" name="pub_name"></td>
                </tr>
                <tr>
                  <td><span class="required">*</span> Office Phone</td>
                    
                  <td><?php echo form_error('pub_tel'); ?><input class="large-field" type="text" value="<?php echo ($rec['pub_tel']); ?>" name="pub_tel"></td>
                </tr>
                  
                  <tr>
                  <td><span class="required">*</span> Mobile Phone</td>
                  <td><?php echo form_error('pub_mob'); ?><input class="large-field" type="text" value="<?php echo ($rec['pub_mob']); ?>" name="pub_mob"></td>
                </tr>
              
                <tr>
                  <td><span class="required">*</span> Website</td>
                  <td><?php echo form_error('pub_web'); ?><input class="large-field" type="text" value="<?php echo ($rec['pub_web']); ?>" name="pub_web"></td>
                </tr>
                
              </tbody>
            </table>
          </div>
          <h2>Your Address</h2>
          <div class="content">
            <table class="form">
              <tbody>
                <tr>
                  <td>Company name:</td>
                  <td><?php echo form_error('pub_firm'); ?><input class="large-field" type="text" value="<?php echo ($rec['pub_firm']); ?>" name="pub_firm"></td>
                </tr>
              
                <tr>
                  <td><span class="required">*</span> Company Address</td>
                  <td><?php echo form_error('pub_address'); ?><input class="large-field" type="text" value="<?php echo ($rec['pub_address']); ?>" name="pub_address"></td>
                </tr>
                
                <tr>
                  <td><span class="required">*</span> City:</td>
                  <td><?php echo form_error('pub_city'); ?><input class="large-field" type="text" value="<?php echo ($rec['pub_city']); ?>" name="pub_city"></td>
                </tr>
               
                <tr>
                  <td><span class="required">*</span> Specialty:</td>
                  <td>
                      <?php echo form_error('specialization[]'); ?>
                      
                      
                      <input type="checkbox" name="specialization[]" value="Txtbk" />Textbooks<br />
                      <input type="checkbox" name="specialization[]" value="Strbks" />Story Books<br />
                      <input type="checkbox" name="specialization[]" value="Rlgbks" />Religious<br />
                      <input type="checkbox" name="specialization[]" value="Schbks" />Scholarly Books<br />
                      <input type="checkbox" name="specialization[]" value="Jnlbks" />Journal<br />
                      
                    
                    </td>
                </tr>
                  <?php if ($rec['pub_email'] ==''){ ?>

                  <tr>
                  <td><span class="required">*</span> Email:</td>
                  <td><?php echo form_error('pub_email'); ?><input class="large-field" type="text" value="<?php echo ($rec['pub_email']); ?>" name="pub_email"></td>
                </tr>
               
                  <tr>
                  <td><span class="required">*</span> Password:</td>
                  <td><?php echo form_error('password'); ?><input class="large-field" type="password" value="<?php echo ($rec['password']); ?>" name="password"></td>
                </tr>

                  <?php } ?>
                  
              </tbody>
            </table>
          </div>
         
          
          <div class="buttons">
            <div class="left">
             <?php if ($rec['pub_email'] ==''){ ?>
              <input type="submit" class="button" value="Register">
                
              <?php } else {?>
    <input type="submit" class="button" value="Update">
    
<?php }?>
            </div>
          </div>
          </form>`

**Comment by shinningweb** [comment]
`    public function register() //create new or update existing record
{   
	//look for ID in URI and store it in a variable
	if($this->uri->segment(3)){
    $rec_id = $this->uri->segment(3);

    //check DB to see if record exists, if it does keep as an array 
    $record_id = $this->users_model->get($rec_id);
    if($record_id){
    $data['recs'] = $record_id;
    $data['title'] = $record_id['pub_name'];
    } else { $data['users'] = 'No matching record found';}
	} else {
    	$data['recs'] = '';
    	$data['title'] = 'New reg title';
    }
	
	//if we have an ID, it is an update
	if($this->input->post('user_id')){
    
	$ret = $this->users_model->from_form(NULL,NULL,array('user_id'))->update(); 
	vdebug($ret);
   $id = TRUE;
	} else {
    
    //we are doing an insert by default when this controller is evoked
   	$id = $this->users_model->from_form()->insert();}

    if($id === FALSE)
    {

    $data['title'] = 'Register an account';
        $data['page'] = $this->load->view('member/register', $data, TRUE);
		$this->load->view('main', $data);
        
    }
    else //insert was successful, redirect to list of users
    {
        $this->load->library('email');
        
        $this->email->from('info@ghanabookpublishers.org', 'Ghana Book Publishers');
        $this->email->to($this->input->post('pub_email'));
        $this->email->subject('Account Successfully created');
        $mess = 'Congratulations '.$this->input->post('pub_name').'\n Your account at http://ghanabookpublishers.org has been created \n You can login with'.$this->input->post('pub_name').'and the password you provided. Thank you';
        $this->email->message($mess);

        $this->email->send();
        
        $data['title'] = 'Registration successful';
        $data['page'] = 'Registration successful</div>';
		$this->load->view('main', $data);
       //redirect('page/register_success','refresh');
        //var_dump($id);
       
    }

}

    `

**Comment by shinningweb** [comment]
How can i write the _setType function to just implode the specialization array and insert into a specific column 'specialization' ?

**Comment by shinningweb** [comment]
Ok, found the solution, thanks to you all
