### ISSUE TITLE
Allow to use the same set of rules for all actions

### ISSUE THREAD

**Issue by s0x** [avenirer/CodeIgniter-MY_Model#241]
At the moment, rules are stored in an associative array containing a set of rules for each action (insert & update). However you need to specify the same set of rules twice in case there is no difference in validation. I'd suggest to check if rules are given as an associative array. If this is the case stick to the current behavior. Otherwise, use the whole set of rules for all actions.

**Comment by salain** [comment]
If you define only 1 set of rules pass it to the method like this
```php
    public $rules = array(
                    'username' => array(
                            'field'=>'username',
                            'label'=>'Username',
                            'rules'=>'trim|required'),
                    'email' => array(
                            'field'=>'email',
                            'label'=>'Email',
                            'rules'=>'trim|valid_email|required',
                            'errors' => array ('required' => 'Error Message rule "required" for field email',
                                    'trim' = > 'Error message for rule "trim" for field email',
                                    'valid_email' = > 'Error message for rule "valid_email" for field email')
                    ),
                    'id' => array(
                            'field'=>'id',
                            'label'=>'ID',
                            'rules'=>'trim|is_natural_no_zero|required')                 
    );

.....
      $id = $this->user_model->from_form($this->rules)->insert();
       // OR 
     $id = $this->user_model->from_form($this->rules)->update();
```

**Comment by s0x** [comment]
I know that this would work. Though, every caller of from_form needs to be aware of this. The solution I proposed would resolve this without any further action required.

**Comment by salain** [comment]
Right it would simplify the call the from_form if you only have one set of rules. 
However I have not got a situation where the validation rules for update and insert where the same.

**Comment by s0x** [comment]
Actually, I'm using this in a couple of situations already. I've applied the patch to my local copy already to reduce the amount of rules and improve readability. This becomes particularly important if you have a complex model.

**Comment by avenirer** [comment]
Let me take a look at it...

**Comment by agung-wete** [comment]
how this supposed to work ? any example ?
