### ISSUE TITLE
password hide in return user details

### ISSUE THREAD

**Issue by kushanz** [avenirer/CodeIgniter-MY_Model#246]
when fetch user data it has password field. but i want to remove password field. 
`       $this->table = 'users';
        $this->primary_key = 'id';
        $this->protected = array('password');`
i'm using protected method. but it still show the password field..
any solution?..

**Comment by Martyn-Cleroux** [comment]
If you want to select specific fields you can do this:
```
$users = $this->user_model->fields('username,password')->get_all();

$users = $this->user_model->fields(array('users.username', 'users.password', 'group.name')->get_all();
```

**Comment by kushanz** [comment]
i mean can't we restrict specific fields.. I thought $protect method will do it..

**Comment by Martyn-Cleroux** [comment]
Unfortunately the `$fillable` and `$protected` variables only prevent the fields from being filled by insert/update.

**Comment by Martyn-Cleroux** [comment]
You can make the following changes to the `get()` and `get_all()` methods to add the functionality you want. I haven't tested these changes so they may not work as expected. It also does not prevent you from selecting protected fields using the `fields()` method.

**Change this (Line 908):**
```
if($this->_select)
{
    $this->_database->select($this->_select);
}
```

**To:**
```
if(isset($this->_select))
{
    $this->_database->select($this->_select);
}
else
{
    $this->fillable_fields();
    $this->fields($this->_can_be_filled);
    $this->_database->select($this->_select);
}
```

**And change this (Line 983):**
```
if(isset($this->_select))
{
    $this->_database->select($this->_select);
}
```

**To:**
```
if(isset($this->_select))
{
    $this->_database->select($this->_select);
}
else
{
    $this->fillable_fields();
    $this->fields($this->_can_be_filled);
    $this->_database->select($this->_select);
}
```

**Comment by avenirer** [comment]
Use an after_get() hook to unset that field.

**Comment by kushanz** [comment]
Thankz @avenirer. It Works for me..
`$this->after_get[] = 'hidepassword';`
`protected function hidepassword($data)`
       ` {`
                `unset($data['password']);`
                `return $data;`
       ` }`
