### ISSUE TITLE
$this->xxx_model->reset_connection() not working

### ISSUE THREAD

**Issue by Romerski** [avenirer/CodeIgniter-MY_Model#251]
Hi, im working with MY_Model and two databases.

Im doing querys on second database like this: `$this->xxx_model->on('second_db')->get_all();`
Then, im doing `$this->xxx_model->reset_connection();` but nothing happens, still using this database.

But if after that query I do a query on main database model like: `$this->yyy_model->get_all();` obviously it does on default database and all following querys are on default database and not on second one.

Any help? Thanks!

**Comment by avenirer** [comment]
I am really sorry for the tardiness of my reply. If you still need this, could you try now?
