### ISSUE TITLE
From_Form Update - No Show Message Error

### ISSUE THREAD

**Issue by matheusdelima** [avenirer/CodeIgniter-MY_Model#256]
Hello Brothers,

I wish to show the messages of errors when my data for validated and the result be FALSE.
I'm using the method: **$this->Assistidos_model->from_form(NULL,NULL,array('id' => $id))->update()** and when have messeges error the return is false and not the messeges.

**Comment by avenirer** [comment]
if the update returns false, you can use the form validation methods to output the errors:
<?php echo validation_errors(); ?>

**Comment by matheusdelima** [comment]
Ok, Thanks!

**Comment by avenirer** [comment]
@matheusdelima any follow-up on this. If my advice works, please close issue. Thanks.
