### ISSUE TITLE
How to use custom where condition?

### ISSUE THREAD

**Issue by Noushid** [avenirer/CodeIgniter-MY_Model#258]
How to get data like this `$this->db->where('`company` IS NULL')->get('users')->result();`
i have already try this method `$this->user->where('`company` IS NULL')->get_all();`
But result is false.

**Comment by lloricode** [comment]
did you extend your `user` model to `MY_MODEL`?

**Comment by avenirer** [comment]
the get() method only accepts the Id of row as optional parameter.
