### ISSUE TITLE
Missing function / variable

### ISSUE THREAD

**Issue by agung-wete** [avenirer/CodeIgniter-MY_Model#260]
Hi
i think you forgot to change following codes :

https://github.com/avenirer/CodeIgniter-MY_Model/blob/e6e38f43cf03e93bdee8e6ded7a258b79871d999/core/MY_Model.php#L297

https://github.com/avenirer/CodeIgniter-MY_Model/blob/e6e38f43cf03e93bdee8e6ded7a258b79871d999/core/MY_Model.php#L336

https://github.com/avenirer/CodeIgniter-MY_Model/blob/e6e38f43cf03e93bdee8e6ded7a258b79871d999/core/MY_Model.php#L339

**Comment by avenirer** [comment]
Thank you for noticing. I really should make some unit tests :P

**Comment by agung-wete** [comment]
indeed

**Comment by agung-wete** [comment]
also
https://github.com/avenirer/CodeIgniter-MY_Model/blob/0355ba228aa67f692759ed4e948c4d5ba4cb8616/core/MY_Model.php#L312

**Comment by agung-wete** [comment]
https://github.com/avenirer/CodeIgniter-MY_Model/blob/0355ba228aa67f692759ed4e948c4d5ba4cb8616/core/MY_Model.php#L316

https://github.com/avenirer/CodeIgniter-MY_Model/blob/0355ba228aa67f692759ed4e948c4d5ba4cb8616/core/MY_Model.php#L325

**Comment by agung-wete** [comment]
and how do we fill `this->fillable` ? it seems `_set_table_fillable_protected` func not called anywhere

https://github.com/avenirer/CodeIgniter-MY_Model/blob/0355ba228aa67f692759ed4e948c4d5ba4cb8616/core/MY_Model.php#L1926

**Comment by avenirer** [comment]
In my defense.... I was working on another version of MY_Model, and drinking a beer (or was it two beers?). Then thought "fuck it, the actual version is better with some tweaking". But... the beer... was so good...

**Comment by agung-wete** [comment]
Haha. Maybe tag release will help ?
