### ISSUE TITLE
count_rows method $where logic

### ISSUE THREAD

**Issue by mstojanovv** [avenirer/CodeIgniter-MY_Model#262]
Hello.

The count_rows method has an optional first parameter $where which is NULL by default.

You are passing the $where parameter to the **main where method** which is good, but in this case the count_rows where is not compatible with the main where method, what if we want to use the count_rows to pass the same params like we pass to the main where method?

Eq.

`$this->model->count_rows($field_or_array = NULL, $operator_or_value = NULL, $value = NULL, $with_or = FALSE, $with_not = FALSE, $custom_string = FALSE);`

Is PR welcomed for this?

Regards.

**Comment by martyn-c** [comment]
Can't you just do `$this->model->where(...)->count_rows();` ?
