### ISSUE TITLE
error when using return_as array

### ISSUE THREAD

**Issue by agung-wete** [avenirer/CodeIgniter-MY_Model#263]
If using `$this->return_as = 'array';`
this line :
https://github.com/avenirer/CodeIgniter-MY_Model/blob/e46328877685ccdc701249567ec352724c2a6d60/core/MY_Model.php#L914

generate error: `Message:  Trying to get property of non-object`
we need to check 
[$row = is_array($row) ? $row[0] : $row->{0};](url)

**Comment by avenirer** [comment]
thank you.
