### ISSUE TITLE
error table name

### ISSUE THREAD

**Issue by wisnubaldas** [avenirer/CodeIgniter-MY_Model#265]
hi sir,
I use hmvc on my project, on auth module i try to install ion_auth, after i plug it i get the following error:
![tes12](https://user-images.githubusercontent.com/10908214/32766409-6e6fde90-c941-11e7-8a2d-71e0e5ef2efe.png)

the structure of my modules like this:
![tes13](https://user-images.githubusercontent.com/10908214/32766490-ba91fc0e-c941-11e7-9f4c-fec29b8ef909.png)

where is the fault? is there anyone who can help me?

**Comment by vachzar** [comment]
I have the same problem, I even didnt use HMVC

**Comment by agung-wete** [comment]
set $table in your model

**Comment by foxmedo** [comment]
this not the problem i think this class is crazy

**Comment by foxmedo** [comment]
it's not compatible with HMVC
