### ISSUE TITLE
soft delete error

### ISSUE THREAD

**Issue by swearl** [avenirer/CodeIgniter-MY_Model#273]
CI 3.1.8
dbprefix is set to "my_"

$this->soft_deletes = true;

i use get function, error appear.

```
Error Number: 1054

Unknown column 'accounts.deleted_at' in 'where clause'

SELECT * FROM `my_accounts` WHERE `account` = 'admin' AND accounts.deleted_at IS NULL LIMIT 1

Filename: core/MY_Model.php

Line Number: 907
```

the table of deleted_at didn't add the dbprefix.

**Comment by avenirer** [comment]
Hello @swearl . Could you try to change the MY_Model.php line 1922 from:
```php
            $this->table = $this->_get_table_name(get_class($this));
```
to
```php
            $this->table = dbprefix($this->_get_table_name(get_class($this)));
```

and tell me if this solves the problem?

**Comment by swearl** [comment]
what is the dbprefix function?

**Comment by avenirer** [comment]
Isn't it a CodeIgniter function? https://codeigniter.com/user_guide/database/query_builder.html?highlight=dbprefix#CI_DB_query_builder::dbprefix

Did you try it?

**Comment by swearl** [comment]
i see, it means

$this->table = $this->_database->dbprefix($this->_get_table_name(get_class($this)));


thanks, seems work fine.

**Comment by avenirer** [comment]
Could you do a pull request for this?
