### ISSUE TITLE
Unknown column ... in 'field list'

### ISSUE THREAD

**Issue by ghost** [avenirer/CodeIgniter-MY_Model#30]
I'm developing a simple application for which I'm using the MY_Model library and I'm getting an error that I hope you could help me with (I'll write an example of the application I'm developing, not the actual application itself, but the following code was tested and it does throw an error just as my actual application does).

<h4>Main controller:</h4>

``` php
class Main extends MY_Controller {

    public function __construct() {
        parent::__construct();

        $this -> load -> model('user_model');
    }

    public function index()
    {
        // All users
        $users = $this -> user_model -> get_all();

        // Get users' emails with country codes
        $users_with_cc = $this -> user_model -> get_all_with_cc();
    }
}
```

<h4>Users model</h4>

``` php
class User_model extends MY_Model {

    public function __construct () {
        $this -> timestamps = FALSE;
        $this -> has_one['phone'] = array('Phone_model', 'id', 'phone_id');

        parent::__construct();
    }

    public function get_all($where = NULL) {
        $this -> with('phone');
        return parent::get_all($where);
    }

    public function get_all_with_cc() {
        $this -> with('phone') -> fields('users.email, phones.country_code');
        return parent::get_all();
    }
}
```

Basically what I want to do is to store all users in the $users variable, and then have a $users_with_cc variable storing an array of all users but only with their emails and corresponding country code ONLY.

This code throws the following error:

<pre>
A Database Error Occurred

Error Number: 1054

Unknown column 'phones.country_code' in 'field list'

SELECT `users`.`email`, `phones`.`country_code` FROM `users`

Filename: C:/wamp/www/my-app/application/core/MY_Model.php

Line Number: 786
</pre>

Before posting this issue I tried several alternatives that could work, and I found one, but not entirely using MY_Model capabilities.

The solution I found involves changing the get_all_with_cc() method to this:

``` php
public function get_all_with_cc() {
    $this -> fields(array(
        'users.email',
        'phones.country_code'
    ));

    $this -> _database -> join('phones', 'users.phone_id = phones.id', 'left');

    return parent::get_all();
}
```

Although this solution works, I would like to use only the MY_Model library without having to use it mixed with CodeIgniter's active record library. Is there any way I could achieve this?
<br>
Another thing that caught my eye was that, while I was testing a possible solution to this problem, I accidentally changed the order of the $users and $users_with_cc variables, leaving them like this:

``` php
// Get users' emails with country codes
$users_with_cc = $this -> user_model -> get_all_with_cc();

// All users
$users = $this -> user_model -> get_all();
```

Even with the second alternative of the get_all_with_cc() method (the one that worked), I get the same error as before, just by changing the order in which both methods are called. This time I couldn't figure out why this error happens.

Could you help me with this issue?
Sorry about the length, but I'm fairly new to GitHub and I'm not used to it, and I wanted to make myself as clear as possible.

Thanks in advance.

**Comment by avenirer** [comment]
Hello,
Assuming you also have a Phone_model, inside the User_model you can do something like this:

``` php
public function get_all_with_cc() {
        return $this -> fields('email')->with_phone('fields:country_code')->get_all();
    }
```

...although you can simply do all this inside the controller (less writing):

``` php
$users_with_cc = $this->user_model->fields('email')->with_phone('fields:country_code')->get_all();
```

Tell me if it works... and close the issue. Thank you.

**Comment by ghost** [comment]
I just tried your suggestions and it turns out none of them work. BTW I do have a Phone_model.

If I change the get_all_with_cc() method, just as you wrote it, I get the following error:

<pre>
A Database Error Occurred
Error Number: 1064
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3
SELECT * FROM `phones` WHERE phones.id IN()
Filename: C:/wamp/www/tests/my-app/application/core/MY_Model.php
Line Number: 786
</pre>

Part of this error, I think, has to do with the fact that the get_all() method in that context is using my own get_all() method, which I overwrote in my Users_model. However, if I put it the get_all_with_cc() method like this:

``` php
public function get_all_with_cc() {
    $this -> fields('email') -> with_phone('fields:country_code');
    return parent::get_all();
}
```

I also get an error, but a slightly different one:

<pre>
A Database Error Occurred
Error Number: 1064
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3
SELECT `phones`.`country_code`, `phones`.`id` FROM `phones` WHERE phones.id IN()
Filename: C:/wamp/www/tests/my-app/application/core/MY_Model.php
Line Number: 786
</pre>

I also tried changing the controller as you suggested, without the methods in the model, and I get the same error as the second one I just pasted.

**Comment by avenirer** [comment]
well... did you try to disable your get_all() method?

**Comment by avenirer** [comment]
sorry about that... wait a few minutes... I hope I'll get to the problem... just replicated it...

**Comment by ghost** [comment]
I did, and still got the same error as the second one. Actually, I tried disabling my get_all() method and only calling the one in MY_Model from the controller. I even just initialized the $users_with_cc variable, and not the $users variable, and still getting the error.

**Comment by avenirer** [comment]
well... it seems that the problem comes from the fact that you didn't select the field that is used as local key... The following should work until I find another solution...

``` php
public function get_all_with_cc() {
    $this -> fields('phone_id, email') -> with_phone('fields:country_code')->get_all();
}
```

**Comment by ghost** [comment]
I just did a var_dump() on that and I see the following (just as an example):

``` php
array (size=2)
  0 => 
    object(stdClass)[27]
      public 'phone_id' => string '1' (length=1)
      public 'email' => string 'someemail@gmail.com' (length=20)
      public 'phone' => 
        object(stdClass)[28]
          public 'country_code' => string 'AA' (length=2)
  1 => 
    object(stdClass)[29]
      public 'phone_id' => string '2' (length=1)
      public 'email' => string 'someotheremail@gmail.com' (length=24)
      public 'phone' => 
        object(stdClass)[30]
          public 'country_code' => string 'BB' (length=2)
```

What I'm actually needing is an object like this, for example:

``` php
object(stdClass)
    public 'email' => string 'someemail@gmail.com' (length=20)
    public 'country_code' => string 'AA' (length=2)
```

Would it be possible, at this time, to get an object like that using MY_Model?

Moreover, besides the fact that your solution works (however not returning the object I need in my case), could you tell me why does your solution work but the following one (which is similar to yours) doesn't?

``` php
public function get_all_with_cc() {
    return $this -> fields('phone_id, email, phones.country_code') -> with('phone') -> get_all();
}
```

**Comment by avenirer** [comment]
Regarding your question about why what you wrote is not working: Is not working because the model does two queries. One for the user model and one for the relation. In the past there was the possibility to do a one to one relationship in only one query, but, later on, because of the complexity involved when doing more relationships, I gave up on that idea.
