### ISSUE TITLE
Return formatted value from database

### ISSUE THREAD

**Issue by ghost** [avenirer/CodeIgniter-MY_Model#31]
I'm trying to retrieve all holidays from a table called 'holidays', but I want the date of the holiday to be returned already formatted from the database.

If I had to do it with CodeIgniter's active record, it would be something like this:

``` php
$holidays = $this -> db -> select("id, DATE_FORMAT(date, '%d %b %y'), 'holiday' as type", FALSE) -> get('holidays') -> result();
```

From the query I just wrote, you can see I also want to add a custom field called 'type' (which doesn't exist in my 'holidays' table) to the returned 'holiday' object, and assign the value 'holiday' to it, which I will later use in my application to validate the type of holiday (because I have other types of holidays besides 'holiday', such as 'day off').

How could I achieve this only using MY_Model?

Thanks in advance.

**Comment by avenirer** [comment]
I guess that once you retrieve the date you can work on it by using PHP.

**Comment by ghost** [comment]
Wouldn't there be a performance issue if I have to iterate over thousands of results with PHP and applying the date() method? Compared to MySQL's DATE_FORMAT I mean...

My question, I believe, is if I can apply MySQL functions using MY_Model. Can this be achieved?

**Comment by avenirer** [comment]
Although I don't think it works, try with fields()

``` php
fields("id, DATE_FORMAT(date, '%d %b %y'), 'holiday' as type");
```

**Comment by ghost** [comment]
I just tried it and indeed it doesn't work.

I get the following error:

<pre>
A Database Error Occurred
Error Number: 1064
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''%d %b %y'), holidays. 'holiday' as type FROM `holidays`' at line 1
SELECT `holidays`.`id`, holidays. DATE_FORMAT(date, holidays. '%d %b %y'), holidays. 'holiday' as type FROM `holidays`
Filename: C:/wamp/www/my-app/application/core/MY_Model.php
Line Number: 677
</pre>

**Comment by ngangchill** [comment]
thanks to  @salain

Hi,
The list of fields needs to be an array as on line 1153, the string is exploded on every occurrence of a comma.

So every parameter for your format function is interpreted as a field.

I would also add the table name to the fields that are in a format function because line 1158 to 1162 adds the table if you don't have a dot in the field name.

try this:

```
...->fields(array("id, DATE_FORMAT(date, '%d %b %y'), 'holiday' as type"),FALSE);
```
