### ISSUE TITLE
has_many_pivot with more than two tables

### ISSUE THREAD

**Issue by ghost** [avenirer/CodeIgniter-MY_Model#35]
Would it be possible to use the 'has_many_pivot' relationship for more than two tables?

What I'm trying to achieve is to relate three tables with a pivot table.

For example, my first table would be 'users'; the second one, 'groups'; and the third one, 'privileges'.
The pivot table would be 'users_groups_privileges', looking, for example, like this:

| user_id | group_id | privilege_id |
| --- | --- | --- |
| 1 | 1 | 1 |
| 1 | 1 | 2 |
| 1 | 2 | 1 |
| 2 | 1 | 1 |
| 3 | 1 | 1 |
| 3 | 2 | 1 |

Is this possible with MY_Model?

**Comment by avenirer** [comment]
do you have a proposal on how to achieve this?

**Comment by avenirer** [comment]
how about we change the way we define the pivot table key? For example, inside the user_model, instead of doing:

``` php
$this->has_many_pivot['groups'] = array('Group_model','foreign_primary_key','local_primary_key');
```

we're doing:

``` php
$this->has_many_pivot['groups'] = array('Group_model','foreign_primary_key','local_primary_key','users_groups_privileges');
$this->has_many_pivot('privileges'] = array('Privilege_model','foreign_primary_key','local_primary_key','users_groups_privileges');
```
