### ISSUE TITLE
relationship shows error on non existing entry

### ISSUE THREAD

**Issue by ngangchill** [avenirer/CodeIgniter-MY_Model#4]
## Controller:

```
  function view($id = null){
    if($id && is_numeric($id)){
        $this->data['blog'] = $this->blog_model->with('comment|photo')->as_object()->get($id);
        //dump_exit($this->data['blog']);
        $this->display();
    } else {
        show_404();
    }
}
```
## Models

```
  class Blog_model extends \MY_Model
 {
    public function __construct()
   {
    $this->has_many['comment'] = 'Comment_model';
    $this->has_one['category'] = array('Category_model','id','category_id');
    $this->has_one['photo'] = 'Photo_model';
    $this->cache_prefix = 'blog';
    parent::__construct();
 }
 }



    class Comment_model extends \MY_Model
     {
  public function __construct()
 {
    $this->has_one['blog'] = 'Blog_model';
    parent::__construct();
 }
  }





    class Photo_model extends \MY_Model
    {
    public function __construct()
     {
      $this->has_one['blog'] = 'Blog_model';
       $this->cache_prefix = 'photo';
      parent::__construct();
    }
      }
```
## Errors:

A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: model/MY_Model.php

Line Number: 554

Backtrace:

File: E:\web\phpdesktop-chrome-31.8-php-5.6.1\www\application\vendor\fab\model\MY_Model.php
Line: 554
Function: _exception_handler

File: E:\web\phpdesktop-chrome-31.8-php-5.6.1\www\application\vendor\fab\model\MY_Model.php
Line: 699
Function: call_user_func_array

File: E:\web\phpdesktop-chrome-31.8-php-5.6.1\www\application\vendor\fab\model\MY_Model.php
Line: 423
Function: trigger

File: E:\web\phpdesktop-chrome-31.8-php-5.6.1\www\application\modules\blog\controllers\blog.php
Line: 148
Function: get

File: E:\web\phpdesktop-chrome-31.8-php-5.6.1\www\application\modules\blog\controllers\blog.php
Line: 44
Function: view

File: E:\web\phpdesktop-chrome-31.8-php-5.6.1\www\index.php
Line: 275
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: model/MY_Model.php

Line Number: 554

Backtrace:

File: E:\web\phpdesktop-chrome-31.8-php-5.6.1\www\application\vendor\fab\model\MY_Model.php
Line: 554
Function: _exception_handler

File: E:\web\phpdesktop-chrome-31.8-php-5.6.1\www\application\vendor\fab\model\MY_Model.php
Line: 699
Function: call_user_func_array

File: E:\web\phpdesktop-chrome-31.8-php-5.6.1\www\application\vendor\fab\model\MY_Model.php
Line: 423
Function: trigger

File: E:\web\phpdesktop-chrome-31.8-php-5.6.1\www\application\modules\blog\controllers\blog.php
Line: 148
Function: get

File: E:\web\phpdesktop-chrome-31.8-php-5.6.1\www\application\modules\blog\controllers\blog.php
Line: 44
Function: view

File: E:\web\phpdesktop-chrome-31.8-php-5.6.1\www\index.php
Line: 275
Function: require_once

```
   Dump => NULL
```

**Comment by ngangchill** [comment]
i think result should return null without any error...

**Comment by avenirer** [comment]
Hello. Could you please try loading the MY_Model again and send me information on what line the error was encountered? Thank you.

**Comment by avenirer** [comment]
I've managed to repeat the error you've encountered and I hope I've repaired it. Please reload the MY_Model and give it another try. If everything is ok, I would appreciate if you close the issue. Thank you for trying MY_Model.

**Comment by ngangchill** [comment]
solved....

thanks.
