### ISSUE TITLE
Relation with string column seperated comma

### ISSUE THREAD

**Issue by afbora** [avenirer/CodeIgniter-MY_Model#46]
How can i relate the column that string seperated comma? For example:

I have `categories` and `posts` table. The post table have `categories_id` column contains like `3,5,7,9` that category id. 

I tried to implement from `has_many`, but didnt work!

**Comment by Itiho** [comment]
It is many-to-many relationship and need a junction table

![800px-databases-manytomanywjunction](https://cloud.githubusercontent.com/assets/7440821/8891485/fee72c02-32f9-11e5-9e24-ae828130c8e7.jpg)

**Comment by afbora** [comment]
I know that need a new table but sometimes it's good on working single table ;))

In fact, just explode to `column` by comma before running the query, it will work perfect!
