### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by ATofighi** [avenirer/CodeIgniter-MY_Model#5]
Hi,
Can you add something like laravel pagination in the My_Model?
http://laravel.com/docs/5.0/pagination

thanks.

**Comment by avenirer** [comment]
That is rather a view problem, not a model one... For that I would rather use this: https://github.com/accent-interactive/MY_Pagination

**Comment by avenirer** [comment]
Hello @ATofighi ,

Could you give a try to my paginate() method. Thank you. You can find additional info of the method in the read me.

**Comment by ATofighi** [comment]
looks good, Thanks.
I also think you should use `views` for `next_page`, `previous_page` and `all_pages`...

**Comment by avenirer** [comment]
of course you will output those in the view. The example in the read me is only for telling you what methods you can use :)

**Comment by ngangchill** [comment]
nice work..@avenirer
