### ISSUE TITLE
help needed  

### ISSUE THREAD

**Issue by ngangchill** [avenirer/CodeIgniter-MY_Model#50]
i have 3 tables ( table1, table2 , table3).

table1 is related with table 2, table2 is related with table3; there no direct relation between table 1 and table3.
 in this situation, how can i get data from these three tables  using MY_Model.php?
(( has_relation_through)) !!!!
# Tables:
## Table 1

```
  |  id   |  name   |
```
## Table 2

```
  |  id  |  table1_id  |  table3_id  |  some other fieldes   |
```
## Table 3

```
|  id  |  description |  some other fields  |
```

---

With CI Query Builder i can do it. Eg

```
$query = $this->db->select('.........some  required fileds.....')
                    ->from('table1')
                    ->order_by('id', 'ASC')
                    ->join('table2 as p', 'p.table1_id = table1.id')
                    ->join('table3 as r', 'r.id = p.table2_id')
                    ->get()->result();
```

It works fine still now but i dont know is it wrong or right!!

**Comment by avenirer** [comment]
Well... a MY_Model can only do so much... You could either do it with the query builder or use an "after_get" callback. The query you just wrote seems right with a few modifications (those that I can spot now...)

``` php
$query = $this->db->select('.........some  required fileds.....')
                    ->from('table1')
                    ->order_by('table1.id', 'ASC')
                    ->join('table2 as p', 'p.table1_id = table1.id')
                    ->join('table3 as r', 'r.id = p.table2_id')
                    ->get()->result();
```

**Comment by ngangchill** [comment]
would you give me a demo how can I set after_get call back?

what codes  needs within after_get call back?

thnx.
