### ISSUE TITLE
How can I used insert_batch?

### ISSUE THREAD

**Issue by francisalfanta** [avenirer/CodeIgniter-MY_Model#53]
I received an error:
No method with that name (insert_batch) in MY_Model.

when I try to used
$this->crm_temp_model->insert_batch($agents);

**Comment by avenirer** [comment]
just use insert() and put that multidimensional array in there

**Comment by avenirer** [comment]
@francisalfanta could you try again with insert_batch()?

**Comment by avenirer** [comment]
any news?

**Comment by francisalfanta** [comment]
Ah yes. I just did what you said. sorry for the delay response.
