### ISSUE TITLE
Multiple query consecutive on same model

### ISSUE THREAD

**Issue by afbora** [avenirer/CodeIgniter-MY_Model#57]
When the model run twice, i got same result for both.

```
var_dump($this->users_model->get_dropdown('name'));
var_dump($this->users_model->get_all());
```

2nd result is same with first. Is there auto resetting query or should i reset each query as manual?

**Comment by avenirer** [comment]
Yes... I've met that problem when working on something else, but please retry now.

**Comment by afbora** [comment]
You have not any commit about this issue? I tried just now and issue still continue..

**Comment by avenirer** [comment]
Oh... I misunderstood you. Try again, now.

**Comment by afbora** [comment]
It worked but not another issue occured. When i run following code, result is `object` so `form_dropdown` need as `array` format.

```
var_dump($this->skills_model->as_dropdown('name')->get_all());
```

```
array(78) {
  [0]=>
  object(stdClass)#183 (2) {
    ["id"]=>
    string(1) "1"
    ["name"]=>
    string(12) "ActionScript"
  }
  [1]=>
  object(stdClass)#184 (2) {
    ["id"]=>
    string(1) "2"
    ["name"]=>
    string(4) "AJAX"
  }
}
```

**Comment by avenirer** [comment]
ok... try again...

**Comment by afbora** [comment]
Seems perfect! Thanks :+1:
