### ISSUE TITLE
No scaping and timestamp

### ISSUE THREAD

**Issue by leninbooter** [avenirer/CodeIgniter-MY_Model#58]
When not escaping and using time stamp, the date string is not wrapped with quotes so, an error is raised and the operation aborted.

**Comment by afbora** [comment]
Could you share with us the errors?

**Comment by leninbooter** [comment]
Sorry the delay!
There you go:

![screenshot_1](https://cloud.githubusercontent.com/assets/4433824/9097316/2532caf2-3bc3-11e5-812c-e05306946c9d.png)

**Comment by leninbooter** [comment]
@byybora

**Comment by afbora** [comment]
May be we should seperate `update()` method with `set()` for escaping feature? @avenirer you think?

**Comment by leninbooter** [comment]
I'll try it @byybora  thanks. It just came to my mind to condition it in the core script to wrap the date with quotes

**Comment by avenirer** [comment]
how about using NOW() ?
