### ISSUE TITLE
relationship

### ISSUE THREAD

**Issue by svennd** [avenirer/CodeIgniter-MY_Model#59]
I'm probably missing the easy solution but I can't get my head around the relations between databases.  So I have a list with questions (insert by a user) and now I want to get a list with all questions of all users. This should be doable : 

```
class User_model extends MY_Model
{
    public $table = 'users';
    public $primary_key = 'id';

    public function __construct()
    {
      $this->has_many['vragen'] = 'Vragen_model';
        parent::__construct();
    }
}


class Vragen_model extends MY_Model
{
    public $table = 'vragen';
    public $primary_key = 'id';

    public function __construct()
    {
    $this->has_one['user'] = 'User_model';
        parent::__construct();
    }
}

var_dump($this->vragen->with_user()->get_all());
```

But it throws me an error : Unknown column 'users.vragen_id' in 'field list'

SELECT `users`.`username`, `users`.`vragen_id` FROM `users` WHERE `users`.`vragen_id` IN('1')

clearly its searching for a "vragen_id" obv, its just "id" here. How can I make this work ?

**Comment by ngangchill** [comment]
i think its a reverse relationship in Vragen_model.php
try this:

```
   // $this->has_one['phone'] = array('Phone_model','foreign_key','local_key');
   $this->has_one['user'] = array('User_model','user_id','id');  // 
```

**Comment by svennd** [comment]
Hey, Thx, you got me on track :)

```
$this->has_one['user'] = array('User_model', 'id', 'user');
```

I don't really understand the difference, as User_model is also using MY_Model, but it works.

just for reference : user table uses 'id' and vragen uses 'user'.

so join on users on user.id = vragen.user  

But now it works, thx @ngangchill

**Comment by ngangchill** [comment]
:+1:
