### ISSUE TITLE
Missed upload

### ISSUE THREAD

**Issue by orionstar** [avenirer/CodeIgniter-MY_Model#6]
The latest MY_Model.php contains only a function. Something went wrong?! :D

**Comment by avenirer** [comment]
not that I'm aware of...

**Comment by avenirer** [comment]
wtf happend? :)) damn...

**Comment by avenirer** [comment]
sorry about that... I don't know how that happend. I guess I didn't have much sleep lately...

**Comment by orionstar** [comment]
@avenirer No problem. It's cool you spend so much time for free/open source stuff. :)
