### ISSUE TITLE
Model extending database select avg min max sum

### ISSUE THREAD

**Issue by afbora** [avenirer/CodeIgniter-MY_Model#60]
I extended the model avg min max and sum functions like that:

``` php
public function avg($key)
{
    $this->_database->select_avg($key, 'avg');

    return $this;
}
```

I'm getting errors:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '* FROM `bids` WHERE `bids`.`project_id` = '2' AND `bids`.`active` = '1' LIMIT 1' at line 1

SELECT AVG(`amount`) AS `avg`, * FROM `bids` WHERE `bids`.`project_id` = '2' AND `bids`.`active` = '1' LIMIT 1
```

When i remove `,*` from `SELECT AVG(amount) AS avg, * FROM` query, it works. How can i query non select so without `*`?

**Comment by avenirer** [comment]
@byybora give that a try $this->_database->fields()->select_avg($key, 'avg');

**Comment by afbora** [comment]
```
$this->_database->fields()->select_avg($key, 'avg');
```

> Fatal error: Call to undefined method CI_DB_mysqli_driver::fields()

Works with:

```
$this->fields()->_database->select_avg($key, 'avg');
```

:+1:  Thanks ;)

And fixed empty select error https://github.com/avenirer/CodeIgniter-MY_Model/pull/62

**Comment by afbora** [comment]
By the way, i can implement avg, max, min and sum functions if you want..

**Comment by afbora** [comment]
An issue occured. I changed the method like following:

``` php
public function avg($key, $where = array())
{
    $this->where($where);
    $this->_database->select_avg($key, 'avg');
    $this->_database->from($this->table);
    return $this->_database->get()->row('avg');
}
```
