### ISSUE TITLE
Getting single value

### ISSUE THREAD

**Issue by afbora** [avenirer/CodeIgniter-MY_Model#61]
How can i get single value without accessing array or object?

Reference: http://stackoverflow.com/a/2672758/1769465

**Comment by avenirer** [comment]
well... every CodeIgniter query is actually returning an object. So...

**Comment by afbora** [comment]
For example about accessing `name` attribute:

### Now

```
$user = $this->users_model->get($id);
$name = $user->name;
```

### Expected

```
$name = $this->users_model->fetch('name')->get($id);
```

**Comment by prashantnirgun** [comment]
So finally how do we get that any fetch() is added ? What was enhanced and what is the result came ?

**Comment by avenirer** [comment]
the label is added in order to mark the fact that it is a good idea for enhancement. It doesn't mean that there was a result yet.

**Comment by salain** [comment]
@avenirer 
Thank you for not merging my PR about this as it was a dumb one. 
@afbora 
This is already in the CI Query builder, just chain the field you want after the get() 

``` php
$name = $this->users_model->get($id)->name;
// if you are using an array 
$name = $this->users_model->get($id)['name'];
```

**Comment by avenirer** [comment]
:+1:

**Comment by afbora** [comment]
@salain 

```
$name = $this->users_model->get($id)['name'];
```

Ok with this method (Only PHP 5.4+) but for more performance should be query with `SELECT column_name`

**Comment by salain** [comment]
@afbora As per CI website "PHP version 5.4 or newer is recommended."
Also php 5.4 or lower have reach end of life status (http://php.net/eol.php)

As for performance unless you have a huge records in users table or a very small server would be minimal.
But here is a solution (a bit redundant):

``` php
//using object
$name = $this->users_model->fields('name')->get($id)->name;
// using array
$name = $this->users_model->fields('name')->get($id)['name'];
```

While on the subject of performance PHP 5.6 is far superior to all previous version. I have not yet tested PHP 7, but all I heard so far is good.
