### ISSUE TITLE
Return custom result object

### ISSUE THREAD

**Issue by axelf** [avenirer/CodeIgniter-MY_Model#64]
Hi,

is is possible to do a thing like that in the CI-documentation:
http://www.codeigniter.com/userguide3/database/results.html#result-arrays

There i can pass an parameter with the name of the class to instantiate. Now i get back a standard class object and can't use some special getter e.g. formatting values (get_weight_formatted() which is defined in the model) but this class is not instatiated.

**Comment by avenirer** [comment]
don't thinks so, but feel free to do a pull request ;;)
