### ISSUE TITLE
Help Needed: How can set the relation for user friendship with MY_Model

### ISSUE THREAD

**Issue by ngangchill** [avenirer/CodeIgniter-MY_Model#67]
I have a "friends" table.

| id | user_id | friend_id | Blah blah |
| --- | --- | --- | --- |
| 1 | 1 | 2 | xyz |
| --------- | ---------------- | --------------- | ------------------ |
| 2 | 2 | 5 | xyz |
| --------- | ---------------- | --------------- | ------------------ |
| 3 | 4 | 2 | xyz |
| --------- | ---------------- | --------------- | ------------------ |

Query 1: 

```
    $this->friend_m->where(array('user_id' => 1, 'friend_id' => 2)->get();   
```

Query 2: 

```
   $this->friend_m->where(array('user_id' => 2, 'friend_id' => 1)->get();    
```

Problem:

Query 1 return user 2 as friend but at the same time Query 2 return null( they are not friend) though they are friends from either side theoritically.

So my question is how can i relate them using MY_Model to get friends from either side.

Thanks...

**Comment by avenirer** [comment]
Well... as you can see from your own table... the two are not friends. There is no correlation between user_id (2) and friend_id(1).

However, if you want to create a many to many relationship, you should use one more table in which you keep the relations between "friends":

| id | Blah blah |
| --- | --- |
| 1 | xyz |
| --------- | ------------------ |
| 2 | xyz |
| --------- | ------------------ |
| 3 | xyz |
| --------------------------- |  |

| relation_id | user_id |
| --- | --- |
| 1 | 1 |
| --------- | ---------------- |
| 1 | 2 |
| --------- | ---------------- |
| 3 | 2 |
| --------- | ---------------- |
| 3 | 4 |
| --------- | ---------------- |

**Comment by ngangchill** [comment]
Thanks :+1:
