### ISSUE TITLE
Software versioning

### ISSUE THREAD

**Issue by Itiho** [avenirer/CodeIgniter-MY_Model#68]
It would be interesting to create releases for stable versions. 

Examples:
3.1.0 new feature "as_dropdown"
3.2.0 new feature "Count for relationships" (379c7fc18a59c4c892d7949ae15b94a74f0eeb97)
3.2.1 Correct error "Multiple query consecutive on same model" (#57 ce2f9e52a19b823a2b10d3f83f3d565341853f5a)

**Comment by avenirer** [comment]
There are no "stable versions"... :) There's only trial and error...
