### ISSUE TITLE
Any unfield() equivalent?

### ISSUE THREAD

**Issue by francisalfanta** [avenirer/CodeIgniter-MY_Model#69]
Any shortcode for not including fields when trying to select tables? Counter part for fields().

**Comment by avenirer** [comment]
I don't understand. You want to select all from a table except some fields?

**Comment by salain** [comment]
Hey, 
Yes, I think this is what he wants. I would suggest to use an  array in the model to define field sets then use a function to select the field set 

``` PHP
class Som_model extends MY_Model
{
    public $field_sets =array('meaningful_name_for_the_set' => 'field_1,field_2,field_3, ...',
        'another_fields_set' => 'field_1,field_4,field_5',
        'yet_one_more' => 'field_6,field_1');

    public function set_fields($fld_set_name = NULL)
    {
        if($fld_set_name == NULL){
           $this->fields('*');
        } else {
           $this->fields($this->field_sets[$fld_set_name]);
        }
        return $this;
    }
}
```

Usage: 

``` PHP
$this->some_model->set_fields('meaningful_name_for_the_set')->get_all();
```

**Comment by avenirer** [comment]
That's pretty weird... Next someone will ask for a MY_Model that does controllers and views and is activated by voice :P.

**Comment by salain** [comment]
@avenirer how about reading (what is left of) my mind !!

**Comment by avenirer** [comment]
Woooow... never thought of that... That would be really cool... a model that read people's minds... I will reopen this. Maybe we will get a pull request for this.

**Comment by francisalfanta** [comment]
@salain, the script you provided are beyond what I'm looking for.

@avenirer - "You want to select all from a table except some fields?" - Thank you for translating what's in my thought. :)

Currently the My_Model do contain a method

fields($fields)
Allows the user to select only specific columns

In my situation I have 90 fields in one table. I need all fields except for 3 fields when trying to used the get_all() method.

So I am trying to ask if there is a method that to do this?

The title "Any unfield() equivalent?" for this issue was just a thought.

**Comment by salain** [comment]
There is no method to do this. 
You can simplify what I wrote to just a string of fields that you pass to the fields method 

``` PHP
$my_field_set = 'field_1,field_2,..., field_87';
$this->some_model->fields($my_fields_set)->get_all(); 
```

This simple enough.

**Comment by avenirer** [comment]
@francisalfanta why would you retrieve only 87 fields out of 90 fields. I don't think there is a difference in performance at that number. Do you actually want to protect fields from being shown? For that indeed would be interesting to add a property to MY_Model...

**Comment by francisalfanta** [comment]
I see, I will do that. Thanks.

**Comment by fresh83** [comment]
I second the request for a SELECT function . I thought this lib was the coolest thing since sliced bread, but then got sad when I realized I could not control what I select easily.

**Comment by avenirer** [comment]
What do you mean by "a SELECT function"? You have the fields() method.
