### ISSUE TITLE
The paginate() method shows the soft deleted rows too.

### ISSUE THREAD

**Issue by ngangchill** [avenirer/CodeIgniter-MY_Model#7]
The paginate(5, $total_posts) method shows the soft deleted rows too.

**Comment by ngangchill** [comment]
#avenirer have you fixed it?

**Comment by avenirer** [comment]
it shows the soft deleted rows of the relationships? or...

**Comment by avenirer** [comment]
Really sorry about that. Just now I managed to take a look at it...

**Comment by avenirer** [comment]
Fixed... I hope...

**Comment by ngangchill** [comment]
thanks  :smile: 

i'll check it now..
