### ISSUE TITLE
Pivot relationship acts like one-to-one

### ISSUE THREAD

**Issue by Brostin28** [avenirer/CodeIgniter-MY_Model#70]
UPDATE! read the whole manual and tried all the possible ways to setup a has_many_pivot relation.
nothing seems to work.

Hi Avenir,
I would like to perform joins using this in my controller to show extra info about all students' advisers (which I think needs has_many_pivot relationships)
located in  :

```
$this->load->model('Students_model');
$this->data['pair'] = $user = $this->Students_model->with_advisers('fields:first_name a_f_name,last_name a_l_name')->get_all();
```

but the embedded $pair->advisers outputs 1
as I tried `print_r` function on `$pair[$last_key]->advisers`.

Sql query based on CI's profiler:

```
 SELECT `advisers`.`id`, `advisers`.`first_name` `a_f_name`, `advisers`.`last_name` `a_l_name`
FROM `advisers`
WHERE `advisers`.`id` IN('8', '201500019', '201500020')  
```

here is my Students_model:

```
class Students_model extends MY_Model
{

    public $has_many_pivot = array('advisers' => array(
            'model'=>'Advisers_model',
            'pivot_table'=>'advisers_students',
            'local_key'=>'id',
            'pivot_local_key'=>'student_id',
            'pivot_foreign_key'=>'adviser_id',
            'foreign_key'=>'id')
    );

    public function __construct()
    {...
```

and my Adviser's model:

```
class Advisers_model extends MY_Model
{

    public $has_many_pivot = array('students' => array(
            'model'=>'Students_model',
            'pivot_table'=>'advisers_students',
            'local_key'=>'id',
            'pivot_local_key'=>'adviser_id',
            'pivot_foreign_key'=>'student_id',
            'foreign_key'=>'id')
    );

    public function __construct()
    {...
```

My database:
![sdasd](https://cloud.githubusercontent.com/assets/14155674/9950969/56498bce-5df3-11e5-8914-0cd0f682e909.png)

Can you advise on this one?

**Comment by avenirer** [comment]
Hello. Could you try downloading again MY_Model and see if it works?

**Comment by avenirer** [comment]
@Brostin08 did you try it?

**Comment by sergioalcaraz** [comment]
@avenirer I tried it with a similar case and continues to act as one to one

**Comment by avenirer** [comment]
Thank you @Brostin08 and @sergioalcaraz . I really don't know how this happened, but I think I've repaired it... Will close the issue if it's ok with at least one of you :)

**Comment by sergioalcaraz** [comment]
@avenirer I've tested and is working properly thank you

**Comment by Brostin28** [comment]
I'm so sorry I was preoccupied with trying to work on my other projects. I will try it. Thanks!
