### ISSUE TITLE
get_all() without trashed

### ISSUE THREAD

**Issue by MoserDamasceno** [avenirer/CodeIgniter-MY_Model#71]
To get all data without trashed rows and to need use the method 'where()' without a parameter, I have included on line 861 these code below. This way, if not used 'where' parameter and 'soft_deletes' is TRUE, the function _where_trashed() will be executed. Maybe this can be useful to more people.

```
    if(isset($where))
    {
         $this->where($where);
     } elseif ($this->soft_deletes===TRUE) {
          $this->_where_trashed();
     }
```

**Comment by avenirer** [comment]
Hello @MoserDamasceno ,
Isn't the where() method already calling a $this->_where_trashed() on line 555?

**Comment by MoserDamasceno** [comment]
Greetings,
Yes, is it. 
But when I have called $this->model->get_al() without chain where(), the method _where_trashed() is not called.
And I don't think that is a good pratice, use the method where() without a parameter.

**Comment by avenirer** [comment]
Thank you @MoserDamasceno . I didn't noticed that.
