### ISSUE TITLE
Get relate data from many to many relationship

### ISSUE THREAD

**Issue by sergioalcaraz** [avenirer/CodeIgniter-MY_Model#72]
Hi @avenirer, it is necessary to include in the documentation the name of the key to get the data related to the array has_many_pivot (many to many)
Example: 
$this->has_many_pivot['products'] = array(
            'model' => 'Product_model',
            'pivot_table' => 'images_products',
            'local_key' => 'id',
            'pivot_local_key' => 'image_id',
            'pivot_foreign_key' => 'product_id',
            'foreign_key' => 'id',
            'get_relate' => TRUE);

**Comment by avenirer** [comment]
Thank you.
