### ISSUE TITLE
Query with where LIKE operator

### ISSUE THREAD

**Issue by sergioalcaraz** [avenirer/CodeIgniter-MY_Model#73]
Hi I tried to query and I don't find a way to do queries like
SELECT \* FROM BAR WHERE foobar like '%foo%';

**Comment by Tpojka** [comment]
Have you tried something like: `$this->user_model->where('username','%avenirer%')->get();`?

**Comment by sergioalcaraz** [comment]
Yes, I tried but do a sql like SELECT \* FROM `users` WHERE `users`.`username` = '%bar%'  LIMIT 1, thank for reply

**Comment by salain** [comment]
if the operator in not "Equal" you need to add it to the field name like this: 

``` PHP
$this->user_model->where('username LIKE','%avenirer%')->get();
```

**Comment by sergioalcaraz** [comment]
Thank you, @salain, @Tpojka. its work :)
