### ISSUE TITLE
How to use parentheses in WHERE method?

### ISSUE THREAD

**Issue by sergioalcaraz** [avenirer/CodeIgniter-MY_Model#74]
Hi everybody, I've been tried to use parentheses in where sentences like:
SELECT \* FROM FOO WHERE (BAR = 'something' OR BAR = 'something else') AND FOOBAR = 'something',
but I don't find a way to do.
In Codeigniter Querybuilder, I find these methods http://www.codeigniter.com/user_guide/database/query_builder.html#query-grouping.

**Comment by prashantnirgun** [comment]
Good to point out important

**Comment by salain** [comment]
Hi guys,
if you want to use query grouping from the Query_builder add this to  the __call magic method in MY_Model:

``` php
   public function __call($method, $arguments)
       {
 //.....

// Add this to access query_builder functions not defined in MY_Model
            if (method_exists($this->_database, $method)) {
                call_user_func_array(array($this->_database, $method), $arguments);
                return $this;
            }
// End
            $parent_class = get_parent_class($this);

  //....
}

```

This will allow you to use the query_builder methods:

``` php
$records = $this->group_start()
            ->where('foo','>',1)
            ->where('bar','>',10,TRUE)
            ->group_end()
           ->where('foobar','=','something')->get_all();
```

This will produce this query:

``` sql
SELECT * FROM `table` WHERE ( `foo` > 1 OR `bar` > 10 ) AND `foobar` = 'something' 
```

**Comment by francisalfanta** [comment]
Very interesting..In your example where clause 3rd and 4th parameter stands
for?

**Comment by salain** [comment]
The where method is from MY_Model, it overrides the CI query builder method so you must use is as per the documentation of MY_Model (https://github.com/avenirer/CodeIgniter-MY_Model#wherefield_or_array--null-operator_or_value--null-value--null-with_or--false-with_not--false-custom_string--false). 
so in the second where("field name", "operator", value, TRUE)
4th param is to make it OR clause if omitted it will be AND clause. 

I wrote it like that to follow the example in the first post in this issue.

**Comment by xgenvn** [comment]
@salain I tried the operator with LIKE and it seems not work, can you give an example that uses LIKE expression with OR clause of multiple fields? (normally used in fuzzy filtering)? Thanks.

**Comment by salain** [comment]
@xgenvn 
How does this relate to the subject at hand ??
Here it is as specified in the doc and code.

$this->where('FIELD_NAME', 'OPERATOR', 'VALUE')
So 
$this->where('email','like','%@gmail.com');
will make the where clause as WHERE email LIKE '%@gmail.com'

**Comment by xgenvn** [comment]
@salain sorry if it's not fit to the subject. I'm stucking with simple OR clause between two fields.
I've checked the source and tried with:

```
$this->where([['field_name', 'operator', 'value', TRUE'], ['field_name', 'operator', 'value']]) 
```

and 

```
$this->where('field_name', 'operator', 'value', TRUE')->where('field_name', 'operator', 'value', TRUE)
```

Those cases didn't work, and I think it's related with the parentheses or grouping queries.

**Comment by lloricode** [comment]
@salain , hmm what if you create a PR for this?, instead we modify the core.
