### ISSUE TITLE
multiple relations table models

### ISSUE THREAD

**Issue by reginald12** [avenirer/CodeIgniter-MY_Model#76]
hello, 

trying retrieve informations from controller.

i have an ADS table which refer an ADSTYPES table which refer an ADSTYPESLANG  table.
so in my  ADS_model I do

$this->has_one['type'] = array('foreign_model'=>'adstypes_model','foreign_table'=>'adstypes','foreign_key'=>'id','local_key'=>'adstype');
And this is OK.

But when I try to do in the adstypes_model to get all the available lang (or filter by language) in the same time 
        $this->has_many['lang'] = array('foreign_model'=>'adstypeslang_model','foreign_table'=>'adstypeslang','foreign_key'=>'typeid','local_key'=>'id');

It doesnt seems to be correct, no languages records return.

What is the correct way of doing something like that ? 
TRegi

**Comment by ptondereau** [comment]
Hello,

I confirm your problem with this example:

1 User have 1-n Alert(s) and 1 Alert 1-n Message(s)
We have 3 models:
- User_model with $this->has_many['alerts'] = ...
- Alert_model with $this->has_many['messages'] = ...
- Message_model with $this->has_one['alert'] = ...

If in User_model, I have function returning this:

```
return $this->with_alerts()
                  ->with_messages()
                  ->get(1);
```

It limits only to "alerts" level and it doesn't care about nested object(messages).

**Comment by avenirer** [comment]
Ohhhh... Now I understand... You need some sort of "has many through...".

**Comment by ptondereau** [comment]
@avenirer Yes, Eloquent have implemented it

**Comment by salain** [comment]
This is something I will need soon. 
with the example of @rooferz messages is a "child" of alerts, therefore we need to be able to pass with_messages to with_alerts

``` php
$records = $this->with_alerts('fields:fld1,fld2,etc|where: where clause | with_messages')->get(1);
```

But this would make the parameters string for with_alerts too complex to make any sense, so I thing we need to use a multidimensional array. 

``` php
$records = $this->with_alerts(array('fields' =>'fld1,fld2,etc','where' => 'where clause','with' => array('relationship' => 'messages','fields'=> 'fld1,fld2,etc','where'=>'clause')))->get(1);
```

Then add the call to "with_relationship" in join_temporary_results method. 
At the moment, I am not sure how to do this. 

@avenirer does this make sense and should I burn brain cells to figure out the call in join_temporary_results ?

**Comment by avenirer** [comment]
That would rather change the whole way that MY_Model works with relationships... Will think about it.

**Comment by salain** [comment]
@avenirer I think this works and does not change the current relationships
