### ISSUE TITLE
Working with many to many relationships sql ambiguous 

### ISSUE THREAD

**Issue by sergioalcaraz** [avenirer/CodeIgniter-MY_Model#77]
Hi @avenirer, this error is always throws when retrieve like this.
$this->user_model->with_groups("where:`name`='staff'")->get($user_id));
SQL error
Column 'name' in where clause is ambiguous.
The query is
SELECT `groups`.`id`, `groups_users`.`user_id` FROM `groups` LEFT JOIN `groups_users` ON `groups`.`id` = `groups_users`.`group_id` LEFT JOIN `users` ON `groups_users`.`user_id` = `users`.`id` WHERE `name` = 'staff' AND `groups_users`.`user_id` IN('1')

My configuration
$this->has_many_pivot['groups'] = array(
            'foreign_model' => 'Group_model',
            'pivot_table' => 'groups_users',
            'local_key' => 'id',
            'pivot_local_key' => 'user_id',
            'pivot_foreign_key' => 'group_id',
            'foreign_key' => 'id',
            'get_relate' => TRUE
        );
THANK YOU!

**Comment by avenirer** [comment]
In the with_*() method do something like where:groups.name='staff'

**Comment by sergioalcaraz** [comment]
Yeah now is working thank you!!
