### ISSUE TITLE
Using with_* in has_many relationship error.

### ISSUE THREAD

**Issue by sergioalcaraz** [avenirer/CodeIgniter-MY_Model#78]
Hi, when I use with_*("where:`foo`='something'") it give me a error, UNDEFINED INDEX field. I don't know if there is a error in my where sintax.
Thank you

**Comment by avenirer** [comment]
Could you show me some code?

**Comment by sergioalcaraz** [comment]
This is my code.
$this->category_model->with_products("where:products.name='product 1'")->get(1);
My configuration is:
$this->has_many['products'] = array(
            'foreign_model' => 'Product_model',
            'foreign_table' => 'products',
            'foreign_key' => 'category_id',
            'local_key' => 'id');

**Comment by avenirer** [comment]
Sorry @sergioalcaraz, I forgot about this issue. Does it work now?

**Comment by sergioalcaraz** [comment]
Hi @avenirer, It still give me the error
Severity: Notice
Message: Undefined index: fields
Filename: core/MY_Model.php
Line Number: 1070

But it generate correct sql
SELECT *
FROM `products`
WHERE products.name='product 1'
AND `products`.`category_id` IN('1')

**Comment by avenirer** [comment]
did you download the MY_Model again?... because at that line there couldn't be that error.

**Comment by sergioalcaraz** [comment]
Now I download the and give me the error
Severity: Notice
Message: Undefined index: fields
Filename: core/MY_Model.php
Line Number: 1081

**Comment by avenirer** [comment]
you need to mention the fields you want to retrieve from the subquery. when you use with_*("where:foo='something'|fields:id,whatever,anotherfield");

**Comment by sergioalcaraz** [comment]
Hi, sorry I was very busy with other issues, now I test and is working.
Thank you!
