### ISSUE TITLE
created_at, updated_at unix timestamp

### ISSUE THREAD

**Issue by FraOre** [avenirer/CodeIgniter-MY_Model#80]
Hi Adrian, thanks for the good work!

In my DB i have the colums created and changed... but that are INT type because hold data in unix timestamp format.

How can I add the possibility to save the data in that format?

Thanks for your attention!

Francesco

**Comment by FraOre** [comment]
OK I do this... maibe you can marge...

```
/** @var bool | array
 * Enables created_at and updated_at fields
 */
protected $timestamps = TRUE;

protected $unix_timestamp = FALSE;
protected $_created_at_field;
protected $_updated_at_field;
protected $_deleted_at_field;
```

$data[$this->_created_at_field] = ($this->unix_timestamp) ? time() : date('Y-m-d H:i:s');

$data[$this->_updated_at_field] = ($this->unix_timestamp) ? time() : date('Y-m-d H:i:s');

$row[$this->_deleted_at_field] = ($this->unix_timestamp) ? time() : date('Y-m-d H:i:s');

And, in the model: 
function __construct() {

```
$this->unix_timestamp = TRUE;
$this->timestamps = array('created', 'changed');

    parent::__construct();
}
```

**Comment by avenirer** [comment]
@FraOre is this ok? Could you give it a try?

**Comment by FraOre** [comment]
Yes, for me works well!

**Comment by avenirer** [comment]
Thank you for making time to report this to me :+1:
