### ISSUE TITLE
get_all and where()

### ISSUE THREAD

**Issue by ghost** [avenirer/CodeIgniter-MY_Model#82]
Hi, i call 

``` php
  $resp = $this->Test_model->where('contact_id', $id)->get_all();
```

in MY_Model.php 

``` php
public function get_all($where = NULL)
    {
        var_dump($where); <--------- WHERE IS ALWAYS NULL LINE 877
        die();
```

Can you resolve it? Thank's
Marco.

**Comment by avenirer** [comment]
that is an extra where, meant for those that want to put the where as parameter for get_all(). if nothing is passed as parameter, the where() method already does a where condition.

**Comment by ghost** [comment]
Ok...but with this instruction:
public function index_get($id = NULL)
    {
        $resp = $this->Test_model->where('contact_id', $id)->get();

is always NULL why???

  var_dump($id); <--------- NOW PASS THE $id string
        die();
Can you resolve it? Thank's
Marco.

**Comment by ghost** [comment]
IN MY_MODEL.PHP  
public function get($where = NULL)
    {

```
    var_dump($where);
    die();
```

$where is alway null

**Comment by avenirer** [comment]
Well... what you showed me in the index_get() is your own code (not MY_Model's...). It's normal that the $id is NULL as you already gave it a default value of NULL. This is basic programming. Try a PHP tutorial about functions. :)

**Comment by ghost** [comment]
Sorry, thank for your answer..but i don't try any tutorial..because if you try $resp = $this->Test_model->where('contact_id', 12)->get(); your get function on MY_Model return null ..my database table contain 23 record with contact_id = 12.

**Comment by ghost** [comment]
You try to simulate...for me is real bug. Thank's

**Comment by avenirer** [comment]
is index_get in your controller?

**Comment by ghost** [comment]
Yes, i call it with restful server and $id is not null because var_dump($id) result 12.

**Comment by avenirer** [comment]
Can I see your entire controller?

**Comment by ghost** [comment]
Yes. Tomorrow i'll post it. Sorry but i'm not in office now. :-)

**Comment by marcolink77** [comment]
this i s my entire controller:
*************************
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
defined('BASEPATH') OR exit('No direct script access allowed');

require(APPPATH.'/libraries/REST_Controller.php');

class Allegati extends REST_Controller {

    function __construct()
    {
        // Construct the parent class
        parent::__construct();
        $this->load->model('cms/Allegati_model');
    }

    public function index_get ($id = NULL){

         // $id = id_cliente

 
			
          if (!is_null($id))
             {
			 

			
			 $allegati =	$this->Allegati_model->where(array('id_cliente'=>$id))->get();
                //$allegati = $this->Allegati_model->where('id_cliente', '255')->get();
				


                if ($allegati) {

                  $count = count($allegati);

                  $resp  = array(
                     'status' => true,
                     'message' => "Found $count allegati clienti",
                     'data' => $allegati,
                     'count' => $count);

                   $this->response($resp, 200);
                 }
                 else {
                   $resp  = array(
                      'status' => false,
                      'message' => "Allegati clienti non trovati!");
                   $this->response($resp, 404);
                 }
			 
			
				   
				   
             }
            else {
               $resp  = array(
                  'status' => false,
                  'message' => "Impossibile trovare gli allegati specificare un id cliente!");
                   $this->response($resp, 404);
            }

    }

/*
    public function index_post () {
        $categorieclienti    = $this->request->body;

        $crea  = $this->Categorieclienti_model->insert($categorieclienti);
        if ($crea) {
                 $resp  = array(
                   'status' => true,
                   'message' => "Inserimento avvenuto con successo!",
                   'data' => $crea,
                   'count' => '0');
                  $this->response($resp, 201);

            } else {
              $resp  = array(
                 'status' => false,
                 'message' => "Impossibile salvare il record!");
              $this->response($resp, 404);
             }

    }


      public function index_put () {

          $categorieclienti    = $this->request->body;


          if (isset($categorieclienti['id']))
            {
              $crea  = $this->Categorieclienti_model->update($categorieclienti, $categorieclienti['id']);
              if ($crea) {
                   $resp  = array(
                     'status' => true,
                     'message' => "Update avvenuto con successo!",
                     'data' => $crea,
                     'count' => '0');
                    $this->response($resp, 201);

              } else {
                $resp  = array(
                   'status' => false,
                   'message' => "Impossibile aggiornare categorie clienti!");
                $this->response($resp, 404);
               }
            }

        }

    public function index_delete ($id) {

       //var_dump($id);
       //die();
       if (!is_null($id)) {
            $cancella = $this->Categorieclienti_model->delete($id);
            if ($cancella) {
                $resp  = array(
                  'status' => true,
                  'message' => "delete avvenuto con successo!",
                  'data' => $cancella,
                  'count' => '0');
                 $this->response($resp, 200);
               }
               else {
                 $resp  = array(
                    'status' => false,
                    'message' => "Record non Categorie clienti non eliminato!");
                 $this->response($resp, 404);
               }
       } else {
            $resp  = array(
                'status' => false,
                'message' => "Impossibile cancellare specificare un id!");
                 $this->response($resp, 404);
        }

    }
  */

}

Thanks a lot.

**Comment by ghost** [comment]
this is my entire controller:

---

<?php

/*
- To change this license header, choose License Headers in Project Properties.
- To change this template file, choose Tools | Templates
- and open the template in the editor.
  */
  defined('BASEPATH') OR exit('No direct script access allowed');

require(APPPATH.'/libraries/REST_Controller.php');

class Allegati extends REST_Controller {

```
function __construct()
{
    // Construct the parent class
    parent::__construct();
    $this->load->model('cms/Allegati_model');
}

public function index_get ($id = NULL){

     // $id = id_cliente



      if (!is_null($id))
         {




            $allegati = $this->Allegati_model->where('id_cliente', $id)->get();



            if ($allegati) {

              $count = count($allegati);

              $resp  = array(
                 'status' => true,
                 'message' => "Found $count allegati clienti",
                 'data' => $allegati,
                 'count' => $count);

               $this->response($resp, 200);
             }
             else {
               $resp  = array(
                  'status' => false,
                  'message' => "Allegati clienti non trovati!");
               $this->response($resp, 404);
             }




         }
        else {
           $resp  = array(
              'status' => false,
              'message' => "Impossibile trovare gli allegati specificare un id cliente!");
               $this->response($resp, 404);
        }

}
```

/*
    public function index_post () {
        $categorieclienti    = $this->request->body;

```
    $crea  = $this->Categorieclienti_model->insert($categorieclienti);
    if ($crea) {
             $resp  = array(
               'status' => true,
               'message' => "Inserimento avvenuto con successo!",
               'data' => $crea,
               'count' => '0');
              $this->response($resp, 201);

        } else {
          $resp  = array(
             'status' => false,
             'message' => "Impossibile salvare il record!");
          $this->response($resp, 404);
         }

}


  public function index_put () {

      $categorieclienti    = $this->request->body;


      if (isset($categorieclienti['id']))
        {
          $crea  = $this->Categorieclienti_model->update($categorieclienti, $categorieclienti['id']);
          if ($crea) {
               $resp  = array(
                 'status' => true,
                 'message' => "Update avvenuto con successo!",
                 'data' => $crea,
                 'count' => '0');
                $this->response($resp, 201);

          } else {
            $resp  = array(
               'status' => false,
               'message' => "Impossibile aggiornare categorie clienti!");
            $this->response($resp, 404);
           }
        }

    }

public function index_delete ($id) {

   //var_dump($id);
   //die();
   if (!is_null($id)) {
        $cancella = $this->Categorieclienti_model->delete($id);
        if ($cancella) {
            $resp  = array(
              'status' => true,
              'message' => "delete avvenuto con successo!",
              'data' => $cancella,
              'count' => '0');
             $this->response($resp, 200);
           }
           else {
             $resp  = array(
                'status' => false,
                'message' => "Record non Categorie clienti non eliminato!");
             $this->response($resp, 404);
           }
   } else {
        $resp  = array(
            'status' => false,
            'message' => "Impossibile cancellare specificare un id!");
             $this->response($resp, 404);
    }

}
```

  */

}

Thanks a lot

**Comment by avenirer** [comment]
OK... supposing id_cliente 255 exists. if you do a var_dump on $allegati does it return the result?

$allegati = $this->Allegati_model->where('id_cliente', 255)->get();

**Comment by salain** [comment]
@marcolink77 
Is this issue with get_all() or get() ?
As it is in your controller your $count variable will contain the number of fields in the single record from get()
Also, I would echo the last_query or append it to the returned message

``` PHP
$allegati = $this->Allegati_model->where('id_cliente', $id)->get();
$last_query = $this->db->last_query();
...
$resp  = array(
                 'status' => true,
                 'message' => "Found $count allegati clienti, Last Query is: ".$last_query,
...
```

**Comment by ghost** [comment]
Ok...Works.
The problem is a database table..because in the db the "system administrator" arghhh  :-( don't set NULL proprities the deleted_at field. Thanks a lot for all and I'm sorry for lose time.

**Comment by avenirer** [comment]
two hours of my life... wasted. At least one day of your life gone down the drain...

**Comment by ghost** [comment]
..good humor! I hate..system administrator!
