### ISSUE TITLE
soft delete not working 

### ISSUE THREAD

**Issue by prashantnirgun** [avenirer/CodeIgniter-MY_Model#84]
class User_model extends MY_Model
{
    public function __construct()
    {
        $this->table = 'users';
        $this->primary_key = 'id';
        //$this->has_one['details'] = 'User_details_model';
        // $this->has_one['details'] = array('User_details_model','user_id','id');
        //$this->has_one['details'] = array('local_key'=>'id', 'foreign_key'=>'user_id', 'foreign_model'=>'User_details_model');
        //$this->has_many['posts'] = 'Post_model';
        $this->timestamps = TRUE ;
        $this->soft_deletes = TRUE;
        parent::__construct();
    }
}

//controller
class Test extends CI_Controller {
function do_action(){
        $this->load->model('user_model');
        //$this->user_model->insert(array('username'=>'prashant','email'=>'me@me.com','passowrd'=>'abc123'));
        $this->user_model->delete(7);
        $row = $this->user_model->get_all();
        var_dump($row);
 }
}

//Error
You must use the "set" method to update an entry.
Filename: core/MY_Model.php
Line Number: 730

**Comment by avenirer** [comment]
make sure you have "deleted_at" column, make sure you have that particular ID, and if it still doesn't work, do an echo on last query to see what happened.

**Comment by salain** [comment]
Hi,

According to my understanding you need to specify if you want the soft deleted row in your result:
$row = $this->user_model->with_trashed()->get_all();

**Comment by avenirer** [comment]
no... he refers to the fact that he gets an error when soft deleting a row

**Comment by prashantnirgun** [comment]
Yes It working. thanks

**Comment by MohammedAli1991** [comment]
class model user 
     $this->table = 'user';
        $this->primary_key = 'id';
          $this->timestamps_format = 'Y-m-d H:i:s';
        $this->timestamps =  true;
        $this->soft_deletes = true;


class controller 
 $status = $this->user_m->delete( $id);

error in query 
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'THEN '8' ELSE `id` END, `deleted_at` = CASE WHEN `id` = THEN '2017-01-25 10:53' at line 2

UPDATE `user` SET `id` = CASE WHEN `id` = THEN '8' ELSE `id` END, `deleted_at` = CASE WHEN `id` = THEN '2017-01-25 10:53:59' ELSE `deleted_at` END WHERE `user`.`id` = '8' AND `id` IN()
