### ISSUE TITLE
How do we integrate deleted_by & deleted_by_ip field into MY_Model ?

### ISSUE THREAD

**Issue by prashantnirgun** [avenirer/CodeIgniter-MY_Model#85]
considering we are using ion_auth library

//where to add the entry as now a days this become necessary columns in every table for me so I need to automise the process
$board['deleted_by'] = $this->ion_auth->get_user_id();
$board['deleted_from_ip'] = $this->ion_auth->user()->row()->ip_address;

**Comment by avenirer** [comment]
Use the "before_soft_delete" observer.

**Comment by prashantnirgun** [comment]
//user_model
$this->before_soft_delete = array('deletion');

protected function deletion($data)
{
        $this->db->set($this->deleted_by, '1');
        //$data['deleted_by'] = 10; //$this->ion_auth->get_user_id();
        //$board['deleted_from_ip'] = $this->ion_auth->user()->row()->ip_address;
        return $data;
}

still not updating the column values

**Comment by prashantnirgun** [comment]
which one of the about should I used ?
01 $this->db->set($this->deleted_by, '1');
02 $data['deleted_by'] = 10; //$this->ion_auth->get_user_id();

**Comment by avenirer** [comment]
protected function deletion($data)
{
$data['deleted_by'] = 10; //$this->ion_auth->get_user_id();
$data['deleted_from_ip'] = $this->ion_auth->user()->row()->ip_address;
return $data;
}

**Comment by prashantnirgun** [comment]
I am dought full about before_soft_delete observer fire 
//User_Model
$this->before_soft_delete = array('deletion');

protected function deletion($data)
    {
        $data['deleted_by'] = 10; //$this->ion_auth->get_user_id();
        echo 'from deletion ';
        var_dump($data);
        return $data;
    }

//MY_model line no 1370 I added following 2 lines in public function trigger(,,,,){...}
echo $event;
var_dump($data) ;

//It is showing output as follows
after_soft_delete
array (size=2)
  0 => &
    array (size=2)
      'id' => string '28' (length=2)
      'deleted_at' => string '2015-11-06 01:03:31' (length=19)
  'affected_rows' => int 1

UPDATE `users` SET `deleted_at` = CASE WHEN `id` = '28' THEN '2015-11-06 01:03:31' ELSE `deleted_at` END WHERE deleted_at IS NULL AND `users`.`id` = 28 AND `id` IN('28')

its showing only one event ie after_soft_delete that means before_soft_delete not firing.

**Comment by avenirer** [comment]
did you put $this->before_soft_delete... before the constructor? And where are you using it? Can I see the code and not those chaotic things?

**Comment by prashantnirgun** [comment]
class User_model extends MY_Model
{
public function __construct(){
        $this->table = 'users';
        $this->primary_key = 'id';
 'foreign_model'=>'User_details_model');
        //$this->has_many['posts'] = 'Post_model';
       $this->soft_deletes = TRUE;
        $this->timestamps = TRUE ;
        $this->before_soft_delete = array('deletion');
    parent::__construct();
}
protected function deletion($data){
        //$this->db->set($this->deleted_by, '1');
        $data['deleted_by'] = 10; //$this->ion_auth->get_user_id();
        //$board['deleted_from_ip'] = $this->ion_auth->user()->row()->ip_address;
        echo 'from deletion ';

```
    var_dump($data);
    return $data;
```

}
}

**Comment by avenirer** [comment]
what are those echo's in your deletion?

**Comment by prashantnirgun** [comment]
no such i just kept it for checking comment it

**Comment by prashantnirgun** [comment]
inside constructor but before calling parent parent::__construct();

**Comment by prashantnirgun** [comment]
in some part of documentation its written inside constructor but before calling parent:: and in some parts its declare as public class variable in derived class. Which one is to follow ?

Anybody has working code pleased shared

**Comment by prashantnirgun** [comment]
I checked out before_soft_delete observer is not triggering the same method if assigned to called for before_create it works. 

public function __construct(){
$this->table = 'users';
$this->primary_key = 'id';
$this->timestamps = TRUE ;

$this->before_soft_delete = array('deletion');
$this->before_create = array('deletion');
$this->soft_deletes = TRUE;

parent::__construct();

}
protected function deletion($data){
        $data['deleted_by'] = 10; //$this->ion_auth->get_user_id();
        return $data;
}

//Controllter
$this->load->model('user_model');
$this->user_model->insert(array('username'=>'swara','email'=>'me@me.com','passowrd'=>'abc123'));
$this->user_model->delete(41);

//User table data
it put value 10 in column 'deleted_by' inside the new row inserted but not inside soft deleted row ?

**Comment by prashantnirgun** [comment]
Please correct me if I am wrong 

line no 709   if(!empty($before_soft_delete)) Replace with   if(!empty($this->before_soft_delete))
line no 713   if(!empty($before_delete)) Replace with   if(!empty($this->before_delete))

But this Now generating error on line no 731
Severity: Warning
Message: Cannot use a scalar value as an array
Filename: core/MY_Model.php
Line Number: 731

728 foreach($to_update as &$row)
729                {
730                    //$row = $this->trigger('before_soft_delete',$row);
731                    $row[$this->_deleted_at_field] = $this->_the_timestamp();
732                }

I checked out here is $row contained
object(stdClass)[21]
  public 'id' => string '47' (length=2)
  public 'username' => string 'swara' (length=5)
  public 'email' => string 'me@me.com' (length=9)
  public 'password' => string '' (length=0)
  public 'created_at' => string '2015-11-07 01:55:37' (length=19)
  public 'created_by' => null
  public 'updated_at' => null
  public 'updated_by' => null
  public 'deleted_at' => null
  public 'deleted_by' => null

**Comment by prashantnirgun** [comment]
I think Issue is resolved final changes are as follows anybody please check and confirm this

709 /\* if(!empty($before_soft_delete)) // we been handling at line no 730
710            {
711                $to_update = $this->trigger('before_soft_delete',$to_update);
712  } */
713 if(!empty($this->before_delete)) //original was 713 if(!empty($before_delete))
714            {
715                  $to_update = $this->trigger('before_delete',$to_update);
716            }

730 $row = $this->trigger('before_soft_delete',$row); //previously it was commented.

**Comment by avenirer** [comment]
You are right. I will make the changes. Thank you.

**Comment by avenirer** [comment]
Please @prashantnirgun verify.

**Comment by prashantnirgun** [comment]
No now its giving following error

Severity: Warning
Message: Cannot use a scalar value as an array
Filename: core/MY_Model.php
Line Number: 731

**Comment by avenirer** [comment]
that means you didn't return an array from your before soft delete function? Let's refresh on what is sent to the before_soft_delete functions. It is sent a multidimensional array. For example if you want to soft delete a row with id 7 the deletion() function should look like below:

``` php
protected function deletion($data)
{
  foreach($data as &$row)
  {
    $row['deleted_by'] = 10; //$this->ion_auth->get_user_id();
  }
  return $data;
}
```

**Comment by prashantnirgun** [comment]
Thanks it is working perfectly Yes its a multidimensional array. But now the question arises is for "before_create" is only an array. Now problem is both the methods functionality differ in nature feeling not a standardize method. And its not documented anywhere that one receive only an array other expect Multi-dimentional array.

I could say its working now but then update documentation. Thanks avenirer for your efforts for creating such wonderful library and maintaining it. Good work keep it up. If we find it any thing where we can help we will be happy to contribute it. Thanks once again.

**Comment by avenirer** [comment]
Hmm... you are right... Maybe I should change the soft delete so that it receives a single dimension array. Do you mind waiting for me to change it and then try again?

**Comment by prashantnirgun** [comment]
Yep I am ready to wait once my debut option set up I could try to clean it up but right now some how I could not setup debug on Ubuntu + Sublime.

**Comment by avenirer** [comment]
Did the changes @prashantnirgun . Could you try again? Ubuntu and Sublime, not my things :)

``` php
protected function deletion($data)
{
  $data['deleted_by'] = 10; //$this->ion_auth->get_user_id();
  return $data;
}
```

**Comment by prashantnirgun** [comment]
Yes its working fine I don't have any errors & warning for issue raised.
