### ISSUE TITLE
force_delete() is not functioning is there anything wrong i am doing ?

### ISSUE THREAD

**Issue by prashantnirgun** [avenirer/CodeIgniter-MY_Model#86]
Hi

I want to delete the rows which are soft deleted I am using force_delete() but not getting a wrong query can any body help me out. Is there any other method to delete soft deleted rows?

//Soft Delete is on
$this->user_model->force_delete(21);
//$this->user_model->delete(array('deleted_at IS NOT NULL' => 'NULL'));

//output
DELETE FROM `users` WHERE deleted_at IS NULL AND `users`.`id` = 21

//Users table record 
id = 21 , deleted_at = 2015-11-05 20:00:44

**Comment by avenirer** [comment]
@prashantnirgun could you try now?

**Comment by prashantnirgun** [comment]
Yes now its working fine. Thanks for the prompt reply It is providing a great help for me as a newbee. I really appreciate your efforts. good work keep it up.
