### ISSUE TITLE
Previously soft deleted row if we accidently trying to delete cause error

### ISSUE THREAD

**Issue by prashantnirgun** [avenirer/CodeIgniter-MY_Model#88]
Previously soft deleted row if we accudently trying to delete cause following error : 

You must use the "set" method to update an entry.
Filename: core/MY_Model.php
Line Number: 734

**Comment by svennd** [comment]
I can confirm this,

You must use the "set" method to update an entry.
Filename: core/MY_Model.php
Line Number: 773

The part that is responsible is in : /system/database/DB_query_builder.php
the function refered to is : public function set($key, $value = '', $escape = NULL) line: 1282

No idea how to work around this, rather annoying one...

**Comment by avenirer** [comment]
I actually don't understand what are you reffering to... what do you mean by "accudently trying to delete"? What do you mean by "accidentally"? What causes this?

**Comment by svennd** [comment]
$this->user_model->delete($i); twice.  with $soft_delete=true; (in the My_Model.php)

**Comment by svennd** [comment]
a simple example : I wanted to do two queries in one function, the first time the second one failed for a query error, the next time you get the "set" method error, cause the first query was succesfull.

```
public function remove($id)
{
    # soft delete, no panic
    $this->devices->delete((int)$id);
    # also remove it from the other table
    $this->position->delete(array("device" => (int)$id));
 }
```

**Comment by salain** [comment]
This is not a proper solution but a workaround for the time being is to use with_trashed() with the delete method

``` php
$this->user_model->with_trashed()->delete($i);
```

This will avoid the error in the CI Query_Builder

**Comment by salain** [comment]
@avenirer  changing line 765 could fix this 

``` php
//from
if(isset($to_update))
//to
if(isset($to_update) && count($to_update) >0)
```

**Comment by avenirer** [comment]
@salain sounds sane... could you do a PR?

**Comment by salain** [comment]
@avenirer I am not very good with Git. And I am stuck with just a phone at the moment. 
Will do it as soon as I have a PC in my hands.
