### ISSUE TITLE
typographical mistake in documentation

### ISSUE THREAD

**Issue by prashantnirgun** [avenirer/CodeIgniter-MY_Model#89]
//Re commanded to add example of validation in add_user() method inside controller
$rules = $this->user_model->rules['insert'];
$id = $this->user_model->from_form($rules, NULL,NULL)->insert();

//found typographical error in documentation 
public $rules = array(
      'insert' => array(
                            'username' => array(
                            'field'=>'username',
                            'label'=>'Username',
                            'rules'=>'trim|required'),
                    'email' => array(
                            'field'=>'email',
                            'label'=>'Email',
                            'rules'=>'trim|valid_email|required',
                            'errors' => array ('required' => 'Error Message rule "required" for field email',
                                    'trim' = > 'Error message for rule "trim" for field email',
                                    'valid_email' = > 'Error message for rule "valid_email" for field email')
                    //), Insert array end
                    )),
            'update' => array(
                    'username' => array(
                            'field'=>'username',
                            'label'=>'Username',
                            'rules'=>'trim|required'),
                    'email' => array(
                            'field'=>'email',
                            'label'=>'Email',
                            'rules'=>'trim|valid_email|required',
                            'errors' => array ('required' => 'Error Message rule "required" for field email',
                                    //'trim' = > 'Error message for rule "trim" for field email',
                                    'trim' => 'Error message for rule "trim" for field email',
                                    //'valid_email' = > 'Error message for rule "valid_email" for field email')
                                    'valid_email' = > 'Error message for rule "valid_email" for field email')
                    ),
                    'id' => array(
                            'field'=>'id',
                            'label'=>'ID',
                            'rules'=>'trim|is_natural_no_zero|required'),
            )  
    );
//}

**Comment by avenirer** [comment]
Could you do a pull request? or maybe point me to the lines I have to modify?

**Comment by prashantnirgun** [comment]
Readme.me 
line NO original line // replacement
line 149 'trim' = > 'Error message for rule "trim" for field email',  // =>
line 150 'valid_email' = > 'Error message for rule "valid_email" for field email') //=>
line 151 ), // )),
line 163 'trim' = > 'Error message for rule "trim" for field email', //=>
line 164 'valid_email' = > 'Error message for rule "valid_email" for field email') // =>
line 171 ); // ));
line 172 } // not required

bellow is request to add
line 180    $this->load->model('user_model');
line 181 -   $id = $this->user_model->from_form()->insert();
line 181 + $rules = $this->user_model->rules['insert'];
line 182 + $id = $this->user_model->from_form($rules, NULL,NULL)->insert();
