### ISSUE TITLE
fields($fields) methods throughs error while using two table

### ISSUE THREAD

**Issue by ngangchill** [avenirer/CodeIgniter-MY_Model#9]
## Model :

```
    $this->timestamps = TRUE;
    $this->soft_deletes = TRUE;
    $this->has_one['category'] = array('Category_m','id','category_id');
    $this->has_many['comment'] = array('Comment_m','blog_id','id');        
    $this->cache_driver = 'file';
    $this->cache_prefix = 'blog';
```
## Controller:

```
 $blogs= $this->Blog_m->fields(array('blogs.title', 'blogs.slug','categories.id'))->get_all();
```
## Errors:

```
  A Database Error Occurred

  Error Number: 1054

  Unknown column 'categories.id' in 'field list'

 SELECT `blogs`.`title`, `blogs`.`slug`, `categories`.`id` FROM `blogs` WHERE `deleted_at` IS               NULL

 Filename: C:/Program Files (x86)/EasyPHP-DevServer-          14.1VC11/data/localweb/sites/test/application/core/MY_Model.php

 Line Number: 413
```

  if i use 
     $users = $this->Blog_m->with('category')->fields(array('blogs.title', 'blogs.slug','categories.id'))->get_all();   

it also shows same error.

but it works fine with single table:  i.e

```
     $users = $this->Blog_m->fields(array('blogs.title', 'blogs.slug'))->get_all();
```

 ## Without fields() method , it works fine. that is relationship with category model is ok.

```
    $users = $this->Blog_m->with('category')->get_all();
```

**Comment by avenirer** [comment]
I guess those queries you are talking about (that use fields() method in the chain) would work only if you have $this->separate_subqueries set to FALSE inside the constructor. If you don't set that to true, it tries to do separate subqueries... which errors unless I modify the model to first look at what is asked from the database.

**Comment by ngangchill** [comment]
```
       public function __construct()
    {
    $this->timestamps = TRUE;
    $this->soft_deletes = TRUE;

    $this->has_one['category'] = array('Category_m','id','category_id');
    $this->has_many['comment'] = array('Comment_m','blog_id','id');        
    $this->cache_driver = 'file';
    $this->cache_prefix = 'blog';
    parent::__construct();
    $this->separate_subqueries = FALSE;
    }
```

RESULT: 

A Database Error Occurred

Error Number: 1054

Unknown column 'categories.id' in 'field list'

SELECT `blogs`.`title`, `blogs`.`slug`, `categories`.`id` FROM `blogs` WHERE `deleted_at` IS NULL

Filename: C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/sites/test/application/core/MY_Model.php

Line Number: 413

[ im newbee, please dont mind for my stupid queston...

**Comment by avenirer** [comment]
Well... it seems that I am noober than you. I didn't manage to try what I am telling you, but please also do try the following:

$blogs= $this->Blog_m->with('category')->fields(array('blogs.title', 'blogs.slug','categories.id'))->get_all();

...and...

$blogs= $this->Blog_m->with('category',FALSE)->fields(array('blogs.title', 'blogs.slug','categories.id'))->get_all();

**Comment by ngangchill** [comment]
ok. I will try it...

thnx

**Comment by ngangchill** [comment]
First on shows same error. [$blogs= $this->Blog_m->with('category')->fields(array('blogs.title', 'blogs.slug','categories.id'))->get_all();]

second one works fine.  $blogs= $this->Blog_m->with('category',FALSE)->fields(array('blogs.title', 'blogs.slug','categories.id'))->get_all();

**Comment by ngangchill** [comment]
for two tables( blogs & categories) it works fine, but if I use 3 or more tables then??

**Comment by ngangchill** [comment]
one more error with .....->get(1) method.
$users= $this->Blog_m->with('category',FALSE)->fields(array('blogs.title', 'blogs.slug','categories.id'))->get(1);

error:

A Database Error Occurred

Error Number: 1052

Column 'id' in where clause is ambiguous

SELECT `blogs`.`title`, `blogs`.`slug`, `categories`.`id` FROM `blogs` LEFT JOIN `categories` ON `categories`.`id` = `blogs`.`category_id` WHERE `id` = 1 AND `deleted_at` IS NULL LIMIT 1

Filename: C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/sites/test/application/core/MY_Model.php

Line Number: 377

but get() method works when there is no argument. that is    $users= $this->Blog_m->with('category',FALSE)->fields(array('blogs.title', 'blogs.slug','categories.id'))->get();
