### ISSUE TITLE
How to get column data on pivot table?

### ISSUE THREAD

**Issue by kidino** [avenirer/CodeIgniter-MY_Model#91]
I got have_pivot_many working and I am getting data from the foreign table. But how can I get column data on the pivot_table? The attached image is my pivot table. Foreign keys are user_id and project_id. But I also want to access the role column.

![pivot-table](https://cloud.githubusercontent.com/assets/1450433/11531287/afa27b4e-9936-11e5-91e3-b301c7580c46.png)

Here's how I create my model for Project_model.

```
class Project_model extends MY_Model
{
    public function __construct()
    {
        $this->table = 'projects';
        $this->primary_key = 'project_id';

        $this->has_many_pivot['users'] = array(
                    'foreign_model'=>'User_model',
                    'pivot_table'=>'projects_users',
                    'local_key'=>'project_id',
                    'pivot_local_key'=>'project_id', 
                    'pivot_foreign_key'=>'user_id',
                    'foreign_key'=>'id',
                    'get_relate'=>FALSE /* another optional setting, which is explained below */
                );
        parent::__construct();
    }
}
```

**Comment by Tpojka** [comment]
Pivot table shouldn't have anything more than necessary. It is used to get related data from two tables. If role is related to project primarily (and not to user), you should make another pivot table that ties projects and roles and include that part of code in similar way as for `projects_users`.

**Comment by avenirer** [comment]
It is called "pivot table", not "additional table". You should make a "roles" table and a pivot table for "users" and "roles"

**Comment by kidino** [comment]
The case that I have here is where I need to store the user's role in a particular project. There will always be three data that needs to be retrieve -- project-user-role.

Maybe I can change the table above to store role_id instead of ENUM. And then create a role table. But I still need to be able to retrieve the relevent data, which is project_id-user_id-role_id.

I can define two separate have_pivot_many -- one for users and one for roles. This will give me two sets of data
- project with users
- project with roles

And there is no information on which role belongs to which user. The users and the roles are sorted by their respective ids in ascending manner and not in default pivot table order. If it was in default pivot table order, I could've matched them to each other.

Maybe I don't fully understand this MY_Model. I can easily achieve this with a simple SQL and left joins. But how can I use this MY_Model to achieve this?
