### ISSUE TITLE
The with_* function and where parameter where maybe mistake

### ISSUE THREAD

**Issue by virutmath** [avenirer/CodeIgniter-MY_Model#92]
@avenirer 
I just using has_one property and get rows with synstax ( in Controller)
`$list = $this->lessons
                    ->with_courses('where: `archived`=0')
                    ->limit($this->limit, $offset)
                    ->get_all()`

My `has_one` in `lessons model`

`$this->has_one['courses'] = [
            'foreign_model' => 'Series_model',
            'foreign_table' => 'courses',
            'foreign_key' => 'id',
            'local_key' => 'course_id'
        ];`

when I set `$this->limit = 50`, the result `$list` is stdClass
but  when `$this->limit` is enough small like 7, 8.., the result `$list` is array

When I dump `$list`, the result is show as 2 image follow
- with `$limit = 10` : https://gyazo.com/bb5a7fb6f0151e0c3873ea42b43edb50
- with `$limit = 50` : https://gyazo.com/19a95fe7981a9caefded4d9c6b2001a9

Finally I want the result as below, but I have no idea. I using stupid way above and result is not right. 
https://gyazo.com/db35f4477e1dccb6356c29af00006458

Please fix for me. Thank you

**Comment by avenirer** [comment]
This is weird behaviour...
