### ISSUE TITLE
LIKE %% in my_model

### ISSUE THREAD

**Issue by redkowloon** [avenirer/CodeIgniter-MY_Model#93]
Hi, how to perform this sql query using this my_model?

select \* from users where username LIKE '%%%din%%'; 

I read the manual but no explanation regarding these .  

Thank you

**Comment by salain** [comment]
Hi,

``` PHP
/* in the model */
$records = $this->where('username like ', '%din%' )->get_all();
/* in the controller */
$records = $this->user_model->where('username like ', '%din%' )->get_all();
```

I don't know why you would need more than one % , as in SQL 
    % matches any number of characters, even zero characters.
    _ matches exactly one character. 

Regards
