### ISSUE TITLE
Observers $after_get

### ISSUE THREAD

**Issue by dreammonkey** [avenirer/CodeIgniter-MY_Model#94]
hi There,

Great work ! I was using Base model for a long time, this is a very welcome update !

I was messing around with the model and I might have found an issue with the after_get observer....

Say you want to modify some fields in a record using after_get.
The after_get observer only seems to work when fetching a single record -> get(1)
When fetching many records ->get_all() the supplied method gets all the records returned at once (as an array)...

When using return_as 'array' there is no way to distinguish between a single record result and multiple records. (Not an obvious one that is...)

Am I right or should I implement this logic in another way ?

Thanks for your feedback and many thanks for the awesome work you put in this !

**Comment by avenirer** [comment]
Well... a get() would give the after_get observer a single row... while a get_all() would return you multiple rows, right? So you can ask the array that comes inside the after_get observer if it is an associative one (that is the case for a single row) or not (that is the case for multiple rows)... ;)

**Comment by dreammonkey** [comment]
hi @avenirer,

exactly ! but how does one determine consistently (and cheaply) if an array is associative ?
you could check if the array_keys are strings -> in that case the result would be a single record, but I don't think that's a clean solution...

the query object however holds the answer because one could call query->num_rows() on that one, right? But that's not accessible from within the observer, would it be useful to have it as a second argument in the observer method?

I'm just thinking out loud here... ;)

thanks for your speedy answer !

**Comment by avenirer** [comment]
Yes... that would be a nice idea: to send a second paramenter... will think about it.

also

``` php
count(array_filter(array_keys($array), 'is_string');
```

returns true if the $array is associative ;)
