### ISSUE TITLE
Getting objects using with_*() on a many to many realtionship returns an object, not an array

### ISSUE THREAD

**Issue by xgouchet** [avenirer/CodeIgniter-MY_Model#97]
I have a many to many relationship, using a pivot table set up like you do in your sample. My model is a user, with a many to many relationship on groups, and one to many relationship on events

I get my objects like this : 

```
$user = $this->users->with_events()->with_groups()->get_all(); 
```

The problem is that the `events` field on my `$user` object is seen as an array, but the `groups` field is seen es an object, and not an array.  Here's the output of `print_r($user);`

```
stdClass Object
(
    [id] => 42
    [groups] => stdClass Object
        (
            [2] => stdClass Object
                (
                    [id] => 37
                    [name] => admin
                )
        )
    [events] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 2
                    [name] => Mike's Birthday
                )
        )
)
```

As you can see, there's also the issue with the first "key" being 2 and not 0. I'm using Twig and because of this and/or because of the fact that it's an object and not an array I can't iterate on it.

**Comment by xgouchet** [comment]
Okay after digging into this issue, I found the culprit(s). 
Firs of all, in the `join_temporary_results` method, you have this code

```
                if (isset($pivot_table)) {
                    $the_local_key = $result_array[singular($this->table) . '_' . $local_key];
                    if (isset($get_relate) and $get_relate === TRUE) {
                        $subs[$the_local_key][$the_foreign_key] = $this->{$relation['foreign_model']}->where($local_key, $result[$local_key])->get();
                    } else {
                        $subs[$the_local_key][$the_foreign_key] = $result;
                    }
                }
```

This means that the array of linked object are indexed by the key in the pivot table, which IMHO is not really relevent. And because the array does not use continuous indexes, the conversion to object makes it an object; 

Changing the above code to the following fixes the issue for me. Not sure if you want to include this as default behavior but if someone faces the same issue, here's a fix. 

```
                if (isset($pivot_table)) {
                    $the_local_key = $result_array[singular($this->table) . '_' . $local_key];
                    if (isset($get_relate) and $get_relate === TRUE) {
                        $subs[$the_local_key][] = $this->{$relation['foreign_model']}->where($local_key, $result[$local_key])->get();
                    } else {
                        $subs[$the_local_key][] = $result;
                    }
                } 
```

**Comment by avenirer** [comment]
Actually I think that the $foreign_key is the primary key of the related row(s) of the model that your model is in relation with, and not the key in the pivot table. I think it is relevant to know the id of the row that the result is related to.
